### PHASE 1 : Collecting data

In [1]:
# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
# List to capture AI stocks—AI infrastructure and AI-powered companies.
stocks = ["NVDA", "META", "MSFT", "AMD", "GOOGL"]

In [3]:
# df is Dataframe—function which passes in stocks and date range for df.
df = yf.download(tickers=stocks, start="2023-03-15", end="2026-03-15")

[*********************100%***********************]  5 of 5 completed

In [4]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322174  196.210266  259.299255  24.206572
2023-03-16  96.599998   99.497650  203.334320  269.810394  25.518410
2023-03-17  97.839996  100.786987  194.086899  272.965576  25.702248
2023-03-20  96.809998  100.390274  196.269791  265.932312  25.877090
2023-03-21  95.930000  104.059944  200.585907  267.446350  26.175829

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135452  196.240031  260.315204  24.264519  ...
2023-03-16  96.690002  100.360521  204.157859  270.162052  25.565367  ...
2023-03-17  98.750000  101.996980  200.327916  276.775346  26.375651  ...
2023-03-20  96.940002  100.915928  197.807725  271.060860  26.000981  ...
2023-03-21  99.459999  104.238469  201.965083  268.638128  26.368659  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455864  191.447637  253.965577  23.739984
2023-03-16  89.720001   95.411420  196.716257  259.074617  24.005749
2023-03-17  96.660004   99.438135  198.998353  271.822660  25.959020
2023-03-20  96.300003   99.299293  196.934572  270.572427  25.592343
2023-03-21  97.000000  100.420030  201.617802  268.520909  26.156847

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [5]:
df.columns

MultiIndex([( 'Close',   'AMD'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'META'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'NVDA'),
            (  'High',   'AMD'),
            (  'High', 'GOOGL'),
            (  'High',  'META'),
            (  'High',  'MSFT'),
            (  'High',  'NVDA'),
            (   'Low',   'AMD'),
            (   'Low', 'GOOGL'),
            (   'Low',  'META'),
            (   'Low',  'MSFT'),
            (   'Low',  'NVDA'),
            (  'Open',   'AMD'),
            (  'Open', 'GOOGL'),
            (  'Open',  'META'),
            (  'Open',  'MSFT'),
            (  'Open',  'NVDA'),
            ('Volume',   'AMD'),
            ('Volume', 'GOOGL'),
            ('Volume',  'META'),
            ('Volume',  'MSFT'),
            ('Volume',  'NVDA')],
           names=['Price', 'Ticker'])

In [6]:
df.shape

(752, 25)

In [7]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 752 entries, 2023-03-15 to 2026-03-13
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, AMD)     752 non-null    float64
 1   (Close, GOOGL)   752 non-null    float64
 2   (Close, META)    752 non-null    float64
 3   (Close, MSFT)    752 non-null    float64
 4   (Close, NVDA)    752 non-null    float64
 5   (High, AMD)      752 non-null    float64
 6   (High, GOOGL)    752 non-null    float64
 7   (High, META)     752 non-null    float64
 8   (High, MSFT)     752 non-null    float64
 9   (High, NVDA)     752 non-null    float64
 10  (Low, AMD)       752 non-null    float64
 11  (Low, GOOGL)     752 non-null    float64
 12  (Low, META)      752 non-null    float64
 13  (Low, MSFT)      752 non-null    float64
 14  (Low, NVDA)      752 non-null    float64
 15  (Open, AMD)      752 non-null    float64
 16  (Open, GOOGL)    752 non-null    float64
 17  (Open, META)     752 non-null    float64
 18  (Open, MSFT)     752 non-null    float64
 19  (Open, NVDA)     752 non-null    float64
 20  (Volume, AMD)    752 non-null    int64
 21  (Volume, GOOGL)  752 non-null    int64
 22  (Volume, META)   752 non-null    int64
 23  (Volume, MSFT)   752 non-null    int64
 24  (Volume, NVDA)   752 non-null    int64
dtypes: float64(20), int64(5)
memory usage: 152.8 KB

In [8]:
df.describe()

Price        Close                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.828324  178.303726  510.032442  406.722717  110.174772
std      41.766704   59.267770  163.535074   64.594057   53.493754
min      78.209999   95.322174  194.086899  259.299255   24.206572
25%     112.002502  136.263779  335.286385  365.005585   48.840425
50%     141.760002  164.499832  524.088928  409.369659  116.998009
75%     169.445004  190.765556  645.484024  447.321579  146.969254
max     264.329987  343.448242  788.148987  539.825195  207.017273

Price         High                                                  ...  \
Ticker         AMD       GOOGL        META        MSFT        NVDA  ...
count   752.000000  752.000000  752.000000  752.000000  752.000000  ...
mean    149.719827  180.249596  516.432463  410.145541  111.981673  ...
std      42.878968   60.022627  165.473900   64.914353   54.248785  ...
min      85.480003   96.135452  196.240031  260.315204   24.264519  ...
25%     114.395002  137.528329  337.253420  368.108840   49.556451  ...
50%     144.289993  165.989440  532.311006  412.460437  119.131434  ...
75%     172.049995  192.186486  652.566306  450.570323  148.926147  ...
max     267.079987  348.754481  794.384398  552.241938  212.166717  ...

Price         Open                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.924468  178.153442  510.100256  406.707279  110.223178
std      41.941908   59.299622  164.119503   64.850847   53.622100
min      79.220001   92.455864  191.447637  253.965577   23.739984
25%     112.052500  136.271213  335.187082  364.869650   49.125128
50%     142.730003  164.479684  524.796276  410.068683  117.272922
75%     169.307503  190.554032  642.907290  446.764548  147.766464
max     264.190002  347.095646  789.296390  552.023177  208.057150

Price         Volume
Ticker           AMD         GOOGL          META          MSFT          NVDA
count   7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02
mean    5.305591e+07  3.181655e+07  1.695474e+07  2.381806e+07  3.364204e+08
std     2.434066e+07  1.357632e+07  9.409263e+06  1.046421e+07  1.752086e+08
min     7.956800e+06  1.009740e+07  4.726100e+06  5.855900e+06  6.552850e+07
25%     3.606890e+07  2.321348e+07  1.131440e+07  1.726135e+07  1.955628e+08
50%     4.822515e+07  2.849140e+07  1.495705e+07  2.121225e+07  3.052285e+08
75%     6.357465e+07  3.573692e+07  1.942280e+07  2.670622e+07  4.300298e+08
max     2.488596e+08  1.274901e+08  8.844010e+07  1.288553e+08  1.543911e+09

[8 rows x 25 columns]

In [9]:
df.tail()

Price            Close                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  202.679993  306.359985  646.836182  409.410004  182.640106
2026-03-10  203.229996  307.040009  653.510498  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.299805  404.880005  186.029999
2026-03-12  197.740005  303.549988  637.634094  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.184998  395.549988  180.250000

Price             High                                                  ...  \
Ticker             AMD       GOOGL        META        MSFT        NVDA  ...
Date                                                                    ...
2026-03-09  202.970001  306.799988  647.195859  410.209991  182.900102  ...
2026-03-10  206.589996  309.510010  659.735149  410.200012  186.429918  ...
2026-03-11  209.210007  311.420013  658.556170  409.010010  187.619995  ...
2026-03-12  203.619995  308.940002  652.940997  406.119995  184.940002  ...
2026-03-13  199.679993  307.690002  628.631733  404.799988  186.089996  ...

Price             Open                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  189.360001  294.359985  634.236984  404.920013  176.820429
2026-03-10  202.509995  306.170013  653.000925  410.029999  182.390128
2026-03-11  205.110001  306.750000  654.199915  405.570007  185.910004
2026-03-12  202.830002  306.820007  648.195060  404.630005  184.050003
2026-03-13  198.110001  307.010010  623.356281  401.000000  184.919998

Price         Volume
Ticker           AMD     GOOGL      META      MSFT       NVDA
Date
2026-03-09  38877200  29312100  13489700  30131900  177213600
2026-03-10  29139200  23239700   9859300  31706400  179118500
2026-03-11  23076400  24125700   8977200  25512100  145280400
2026-03-12  28886900  24928300  11617500  27263900  155762700
2026-03-13  27561900  23693100  18957600  26848000  160988400

[5 rows x 25 columns]

In [10]:
df["Low"]

Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2023-03-15   86.220001   91.880617  189.354066  253.213371   23.339339
2023-03-16   89.019997   94.717161  194.563156  257.189273   23.872865
2023-03-17   95.940002   99.279443  193.908292  269.927538   25.645297
2023-03-20   92.900002   99.051342  192.132261  263.607366   25.107771
2023-03-21   93.639999  100.390277  196.408681  263.284892   25.358553
...                ...         ...         ...         ...         ...
2026-03-09  189.020004  294.079987  626.243828  403.500000  175.550494
2026-03-10  202.199997  305.570007  648.444828  402.929993  182.000149
2026-03-11  203.630005  305.920013  647.805365  401.589996  184.449997
2026-03-12  196.669998  301.029999  636.355221  401.709991  181.750000
2026-03-13  192.270004  300.440002  609.028522  394.250000  179.940002

[752 rows x 5 columns]

In [11]:
df["Low"]["NVDA"]

Date
2023-03-15     23.339339
2023-03-16     23.872865
2023-03-17     25.645297
2023-03-20     25.107771
2023-03-21     25.358553
                 ...
2026-03-09    175.550494
2026-03-10    182.000149
2026-03-11    184.449997
2026-03-12    181.750000
2026-03-13    179.940002
Name: NVDA, Length: 752, dtype: float64

In [12]:
(df == 0).any().sum()

np.int64(0)

In [13]:
df["Close"]
close_prices = df["Close"]

In [14]:
yf.Ticker("NVDA").news

[{'id': '34b3bb9f-7955-4922-a12f-8166cb5a45f4',
  'content': {'id': '34b3bb9f-7955-4922-a12f-8166cb5a45f4',
   'contentType': 'VIDEO',
   'title': 'Google, Meta, Microsoft, Amazon, Apple earnings: What to expect',
   'description': '<p>Alphabet (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/GOOG/" data-i13n="cpos:1;pos:1">GOOG</a>, <a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/GOOGL/" data-i13n="cpos:2;pos:1">GOOGL</a>), Meta (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/META/" data-i13n="cpos:3;pos:1">META</a>), Microsoft (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/MSFT/" data-i13n="cpos:4;pos:1">MSFT</a>), Amazon (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/AMZN/" data-i13n="cpos:5;pos:1">AMZN</a>), and Apple (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/AAPL/" data-i13n="slk:AAPL;cpos:6;pos:1">AAPL</a>) are all reporting quarterly earnings results this week.</p>\n<p>D.A. Davidson head of technology research Gil Luria joins Yahoo Finance to discuss his outlook for the results and the questions to which he\'ll be looking for answers.</p>',
   'summary': "Alphabet (GOOG, GOOGL), Meta (META), Microsoft (MSFT), Amazon (AMZN), and Apple (AAPL) are all reporting quarterly earnings results this week. D.A. Davidson head of technology research Gil Luria joins Yahoo Finance to discuss his outlook for the results and the questions to which he'll be looking for answers.",
   'pubDate': '2026-04-27T15:12:48Z',
   'displayTime': '',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/W9sjeeYcgOblCuDgy5wslg--~B/aD0zMTg5O3c9NTY3MTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/a2f52010-17e1-11f1-a72f-d329cf096c55_615933d6fff7a404cd702922844a882fe7d02fecfb408b98654c796ca0bec602.com/creatr-uploaded-images/2026-03/a2f52010-17e1-11f1-a72f-d329cf096c55',
    'originalWidth': 5671,
    'originalHeight': 3189,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/W9sjeeYcgOblCuDgy5wslg--~B/aD0zMTg5O3c9NTY3MTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/a2f52010-17e1-11f1-a72f-d329cf096c55_615933d6fff7a404cd702922844a882fe7d02fecfb408b98654c796ca0bec602.com/creatr-uploaded-images/2026-03/a2f52010-17e1-11f1-a72f-d329cf096c55',
      'width': 5671,
      'height': 3189,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/DMuskrdj3N1usxZfBObOtQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/a2f52010-17e1-11f1-a72f-d329cf096c55_615933d6fff7a404cd702922844a882fe7d02fecfb408b98654c796ca0bec602.com/creatr-uploaded-images/2026-03/a2f52010-17e1-11f1-a72f-d329cf096c55',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance Video',
    'url': 'https://finance.yahoo.com/',
    'sourceId': 'video.yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/video/google-meta-microsoft-amazon-apple-earnings-what-to-expect-151248213.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/google-meta-microsoft-amazon-apple-earnings-what-to-expect-151248213.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': {'storylineItems': [{'content': {'id': 'e50d0b1e-10b0-403c-ba84-502c67703aba',
       'contentType': 'VIDEO',
       'isHosted': True,
       'title': 'Nvidia could be undervalued by at least 30%: BofA analyst on Mag 7',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/WExtJULLgvsJq2S6Oz.nYA--~B/aD0xNjM0O3c9MjkwNDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/0b072766-a240-4a8a-842e-c8b24e3c45e9_609e06e92a5cb78c98ebb5228a4084a6c9530d397926e38cb873ac87cb026d37.net/images/2026-04/0b072766-a240-4a8a-842e-c8b24e3c45e9',
        'originalWidth': 2904,
        'originalHeight': 1634,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance Video',
        'sourceId': 'video.yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/video/nvidia-could-be-undervalued-by-at-least-30-bofa-analyst-on-mag-7-150156204.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/nvidia-could-be-undervalued-by-at-least-30-bofa-analyst-on-mag-7-150156204.html'}}},
     {'content': {'id': '107495c2-5ccc-42dd-aafe-88ee251f494a',
       'contentType': 'STORY',
       'isHosted': True,
       'title': 'Have software stocks reached an extreme washout yet?',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/b7739ab0-4236-11f1-bfe7-aa832e8dc688',
        'originalWidth': 4941,
        'originalHeight': 3294,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/news/have-software-stocks-reached-an-extreme-washout-yet-141914857.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/have-software-stocks-reached-an-extreme-washout-yet-141914857.html'}}}]}}},
 {'id': '95203eec-dd1b-45ca-8461-2b10895ad8a1',
  'content': {'id': '95203eec-dd1b-45ca-8461-2b10895ad8a1',
   'contentType': 'STORY',
   'title': "Will Nvidia's explosive rally end soon?",
   'description': '',
   'summary': 'JPMorgan has a warning for Nvidia fans.',
   'pubDate': '2026-04-27T13:34:29Z',
   'displayTime': '2026-04-27T13:34:30Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/50b19ac0-4236-11f1-b6e7-68b5dadcc156',
    'originalWidth': 4864,
    'originalHeight': 3308,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/8XKcKCNqRKaQbE8rRoTlog--~B/aD0zMzA4O3c9NDg2NDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2026-04/50b19ac0-4236-11f1-b6e7-68b5dadcc156',
      'width': 4864,
      'height': 3308,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/iPNvlQswQS1ialdiJ3aK9w--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2026-04/50b19ac0-4236-11f1-b6e7-68b5dadcc156',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/will-nvidias-explosive-rally-end-soon-133429771.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/will-nvidias-explosive-rally-end-soon-133429771.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': {'storylineItems': [{'content': {'id': '2709f15d-ed4e-4050-b639-3eb21459351f',
       'contentType': 'STORY',
       'isHosted': True,
       'title': "Stocks' strong April gains come with 1 potential downside",
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/0babb110-4234-11f1-a7f9-09dbc7f03198',
        'originalWidth': 3990,
        'originalHeight': 2660,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/news/stocks-strong-april-gains-come-with-1-potential-downside-122514320.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/stocks-strong-april-gains-come-with-1-potential-downside-122514320.html'}}},
     {'content': {'id': '69ff5508-e670-4cfa-a4e9-1f2a0f48abfa',
       'contentType': 'STORY',
       'isHosted': True,
       'title': "'A return to optimism': Wall Street strategists are bullish on the AI trade",
       'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/QW.26kmiYfTRiEy3Zd7TgQ--~B/aD01MzI7dz04MDA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-04/84c8e311-44ba-4c1d-83da-a37fa2ebce99',
        'originalWidth': 800,
        'originalHeight': 532,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/article/a-return-to-optimism-wall-street-strategists-are-bullish-on-the-ai-trade-143000172.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/article/a-return-to-optimism-wall-street-strategists-are-bullish-on-the-ai-trade-143000172.html'}}}]}}},
 {'id': '7e8a1996-1434-437a-bc56-4bc50e6a058c',
  'content': {'id': '7e8a1996-1434-437a-bc56-4bc50e6a058c',
   'contentType': 'STORY',
   'title': "Mag 7 earnings bonanza and Powell's home stretch: What to watch this week",
   'description': '',
   'summary': 'Jerome Powell\'s penultimate meeting as Federal Reserve chair and a slate of earnings reports from five out of the seven "Magnificent 7" companies await investors in a busy week ahead.',
   'pubDate': '2026-04-26T11:30:16Z',
   'displayTime': '2026-04-26T17:34:32Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/5ff82710-3ff2-11f1-b79e-7c72edcf109c',
    'originalWidth': 7495,
    'originalHeight': 4451,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/7c.1fyLODDwLbwrU5pQuiw--~B/aD00NDUxO3c9NzQ5NTthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2026-04/5ff82710-3ff2-11f1-b79e-7c72edcf109c',
      'width': 7495,
      'height': 4451,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/BZkXyUpXsbHNd8rYZ_3TIQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2026-04/5ff82710-3ff2-11f1-b79e-7c72edcf109c',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/mag-7-earnings-bonanza-and-powells-home-stretch-what-to-watch-this-week-113016596.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/mag-7-earnings-bonanza-and-powells-home-stretch-what-to-watch-this-week-113016596.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'ea05887f-7fbd-3776-a97d-35682f37656a',
  'content': {'id': 'ea05887f-7fbd-3776-a97d-35682f37656a',
   'contentType': 'STORY',
   'title': "The First 5 Quantum Computing Stocks I'd Buy If I Were Starting From Scratch",
   'description': '',
   'summary': 'Quantum computing is coming faster than most realize.',
   'pubDate': '2026-04-27T16:58:00Z',
   'displayTime': '2026-04-27T16:58:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/19414df28df6d5885be2c6bd62e23702',
    'originalWidth': 1400,
    'originalHeight': 787,
    'caption': 'Image of a quantum computing cell.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/KEj3H4l2.yOufwqpHHzI2w--~B/aD03ODc7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/19414df28df6d5885be2c6bd62e23702',
      'width': 1400,
      'height': 787,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/F5ZbJ9Y4woaal.YwYbZgPg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/19414df28df6d5885be2c6bd62e23702',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/27/the-first-5-quantum-computing-stocks-id-buy-if-i-s/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/first-5-quantum-computing-stocks-165800916.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '516841b3-1274-3397-8b28-08af6dc72913',
  'content': {'id': '516841b3-1274-3397-8b28-08af6dc72913',
   'contentType': 'STORY',
   'title': 'Is Palantir Technologies Stock More Likely to Hit $100 or $200?',
   'description': '',
   'summary': 'The stock has been volatile over the past year, and that trend could continue.',
   'pubDate': '2026-04-27T16:50:00Z',
   'displayTime': '2026-04-27T16:50:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/201fc4de4c64cdc5b31f417c8e673848',
    'originalWidth': 1400,
    'originalHeight': 886,
    'caption': 'A person interacting with artificial intelligence.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/wEtnt3MjwQ1JKDg__VwBzA--~B/aD04ODY7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/201fc4de4c64cdc5b31f417c8e673848',
      'width': 1400,
      'height': 886,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/7YojQFn.KebmcJzFAf2Ydg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/201fc4de4c64cdc5b31f417c8e673848',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/27/is-palantir-technologies-stock-more-likely-to-hit/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/palantir-technologies-stock-more-likely-165000341.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'f9f717d0-6e2a-3469-b2c4-9fdc9ca13971',
  'content': {'id': 'f9f717d0-6e2a-3469-b2c4-9fdc9ca13971',
   'contentType': 'STORY',
   'title': 'Stock Market Today: Dow Dips While Intel Gains; Google Stock Clears Entry, But Note This (Live Coverage)',
   'description': '',
   'summary': 'The Dow Jones index falls Monday. Intel rises but chip stocks lag. Google parent Alphabet clears an entry on the stock market today.',
   'pubDate': '2026-04-27T16:48:23Z',
   'displayTime': '2026-04-27T16:48:23Z',
   'isHosted': False,
   'bypassModal': False,
   'previewUrl': 'https://finance.yahoo.com/m/f9f717d0-6e2a-3469-b2c4-9fdc9ca13971/stock-market-today-dow-dips.html',
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/ibd.com/9f396ea862c35dd587b500d8f3834ecf',
    'originalWidth': 1000,
    'originalHeight': 563,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/2H24A.8wFCLeTEL6Ot9wwQ--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/9f396ea862c35dd587b500d8f3834ecf',
      'width': 1000,
      'height': 563,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/92liOAfFlKKrc3CeXDi6xA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/ibd.com/9f396ea862c35dd587b500d8f3834ecf',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': "Investor's Business Daily",
    'url': 'http://www.investors.com/',
    'sourceId': 'ibd.com'},
   'canonicalUrl': {'url': 'https://www.investors.com/market-trend/stock-market-today/dow-jones-sp500-nasdaq-iran-news-nvidia-stock-nvda/?src=A00220&yptr=yahoo',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': None,
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '60f399cf-06da-3455-bf00-86549d03ed11',
  'content': {'id': '60f399cf-06da-3455-bf00-86549d03ed11',
   'contentType': 'STORY',
   'title': "OpenAI and Microsoft Just Revamped Their Longstanding Partnership. Will This Impact Microsoft's Artificial Intelligence (AI) Moat?",
   'description': '',
   'summary': 'OpenAI and Microsoft have long had a partnership regarding how the two entities do business with one another.',
   'pubDate': '2026-04-27T16:44:41Z',
   'displayTime': '2026-04-27T16:44:41Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/c4d0357026f83e10f9a646f06f6287aa',
    'originalWidth': 1400,
    'originalHeight': 934,
    'caption': 'Two people looking at computer screen.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/jWIoqUi27hRW3wr3pFAi8w--~B/aD05MzQ7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/c4d0357026f83e10f9a646f06f6287aa',
      'width': 1400,
      'height': 934,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/5ZDmmy21sUYgvxHkqGngVQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/c4d0357026f83e10f9a646f06f6287aa',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/27/openai-and-microsoft-just-revamped-their-longstand/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/openai-microsoft-just-revamped-longstanding-164441029.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '9c1b8e2f-0669-3954-a7b5-dc8eaec0e4ee',
  'content': {'id': '9c1b8e2f-0669-3954-a7b5-dc8eaec0e4ee',
   'contentType': 'STORY',
   'title': 'AMD Is Up 65% in April: It’s Not Just Intel Momentum',
   'description': '',
   'summary': 'Shares of Advanced Micro Devices (NASDAQ:AMD) are trading near $333 in midday action Monday, down 4% on the session after Northland cut its rating. Even with today’s pullback, AMD stock is up 65%, one of the most remarkable monthly moves the chip sector has seen this year. The catalyst stack is broader than the headlines ... AMD Is Up 65% in April: It’s Not Just Intel Momentum',
   'pubDate': '2026-04-27T16:42:20Z',
   'displayTime': '2026-04-27T16:42:20Z',

In [15]:
headlines = []

for stock in stocks:
    news = yf.Ticker(stock).news
    for article in news:
        headlines.append({
            "ticker": stock,
            "title": article["content"]["title"],
            "date": article["content"]["pubDate"]
        })

In [16]:
# Show all content and metadata for single headline
yf.Ticker("NVDA").news[0]

{'id': '34b3bb9f-7955-4922-a12f-8166cb5a45f4',
 'content': {'id': '34b3bb9f-7955-4922-a12f-8166cb5a45f4',
  'contentType': 'VIDEO',
  'title': 'Google, Meta, Microsoft, Amazon, Apple earnings: What to expect',
  'description': '<p>Alphabet (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/GOOG/" data-i13n="cpos:1;pos:1">GOOG</a>, <a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/GOOGL/" data-i13n="cpos:2;pos:1">GOOGL</a>), Meta (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/META/" data-i13n="cpos:3;pos:1">META</a>), Microsoft (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/MSFT/" data-i13n="cpos:4;pos:1">MSFT</a>), Amazon (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/AMZN/" data-i13n="cpos:5;pos:1">AMZN</a>), and Apple (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/AAPL/" data-i13n="slk:AAPL;cpos:6;pos:1">AAPL</a>) are all reporting quarterly earnings results this week.</p>\n<p>D.A. Davidson head of technology research Gil Luria joins Yahoo Finance to discuss his outlook for the results and the questions to which he\'ll be looking for answers.</p>',
  'summary': "Alphabet (GOOG, GOOGL), Meta (META), Microsoft (MSFT), Amazon (AMZN), and Apple (AAPL) are all reporting quarterly earnings results this week. D.A. Davidson head of technology research Gil Luria joins Yahoo Finance to discuss his outlook for the results and the questions to which he'll be looking for answers.",
  'pubDate': '2026-04-27T15:12:48Z',
  'displayTime': '',
  'isHosted': True,
  'bypassModal': False,
  'previewUrl': None,
  'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/W9sjeeYcgOblCuDgy5wslg--~B/aD0zMTg5O3c9NTY3MTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/a2f52010-17e1-11f1-a72f-d329cf096c55_615933d6fff7a404cd702922844a882fe7d02fecfb408b98654c796ca0bec602.com/creatr-uploaded-images/2026-03/a2f52010-17e1-11f1-a72f-d329cf096c55',
   'originalWidth': 5671,
   'originalHeight': 3189,
   'caption': '',
   'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/W9sjeeYcgOblCuDgy5wslg--~B/aD0zMTg5O3c9NTY3MTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/a2f52010-17e1-11f1-a72f-d329cf096c55_615933d6fff7a404cd702922844a882fe7d02fecfb408b98654c796ca0bec602.com/creatr-uploaded-images/2026-03/a2f52010-17e1-11f1-a72f-d329cf096c55',
     'width': 5671,
     'height': 3189,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/DMuskrdj3N1usxZfBObOtQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/a2f52010-17e1-11f1-a72f-d329cf096c55_615933d6fff7a404cd702922844a882fe7d02fecfb408b98654c796ca0bec602.com/creatr-uploaded-images/2026-03/a2f52010-17e1-11f1-a72f-d329cf096c55',
     'width': 170,
     'height': 128,
     'tag': '170x128'}]},
  'provider': {'displayName': 'Yahoo Finance Video',
   'url': 'https://finance.yahoo.com/',
   'sourceId': 'video.yahoofinance.com'},
  'canonicalUrl': {'url': 'https://finance.yahoo.com/video/google-meta-microsoft-amazon-apple-earnings-what-to-expect-151248213.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/google-meta-microsoft-amazon-apple-earnings-what-to-expect-151248213.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'metadata': {'editorsPick': True},
  'finance': {'premiumFinance': {'isPremiumNews': False,
    'isPremiumFreeNews': False}},
  'storyline': {'storylineItems': [{'content': {'id': 'e50d0b1e-10b0-403c-ba84-502c67703aba',
      'contentType': 'VIDEO',
      'isHosted': True,
      'title': 'Nvidia could be undervalued by at least 30%: BofA analyst on Mag 7',
      'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/WExtJULLgvsJq2S6Oz.nYA--~B/aD0xNjM0O3c9MjkwNDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/0b072766-a240-4a8a-842e-c8b24e3c45e9_609e06e92a5cb78c98ebb5228a4084a6c9530d397926e38cb873ac87cb026d37.net/images/2026-04/0b072766-a240-4a8a-842e-c8b24e3c45e9',
       'originalWidth': 2904,
       'originalHeight': 1634,
       'caption': '',
       'resolutions': None},
      'provider': {'displayName': 'Yahoo Finance Video',
       'sourceId': 'video.yahoofinance.com'},
      'previewUrl': None,
      'providerContentUrl': '',
      'canonicalUrl': {'url': 'https://finance.yahoo.com/video/nvidia-could-be-undervalued-by-at-least-30-bofa-analyst-on-mag-7-150156204.html'},
      'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/nvidia-could-be-undervalued-by-at-least-30-bofa-analyst-on-mag-7-150156204.html'}}},
    {'content': {'id': '107495c2-5ccc-42dd-aafe-88ee251f494a',
      'contentType': 'STORY',
      'isHosted': True,
      'title': 'Have software stocks reached an extreme washout yet?',
      'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/b7739ab0-4236-11f1-bfe7-aa832e8dc688',
       'originalWidth': 4941,
       'originalHeight': 3294,
       'caption': '',
       'resolutions': None},
      'provider': {'displayName': 'Yahoo Finance',
       'sourceId': 'yahoofinance.com'},
      'previewUrl': None,
      'providerContentUrl': '',
      'canonicalUrl': {'url': 'https://finance.yahoo.com/news/have-software-stocks-reached-an-extreme-washout-yet-141914857.html'},
      'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/have-software-stocks-reached-an-extreme-washout-yet-141914857.html'}}}]}}}

In [17]:
headlines[0]

{'ticker': 'NVDA',
 'title': 'Google, Meta, Microsoft, Amazon, Apple earnings: What to expect',
 'date': '2026-04-27T15:12:48Z'}

In [18]:
len(headlines)

50

In [19]:
# Flatten data

headline_data = pd.DataFrame(headlines)

In [20]:
headline_data.head()

,ticker,title,date
0,NVDA,"Google, Meta, Microsoft, Amazon, Apple earning...",2026-04-27T15:12:48Z
1,NVDA,Will Nvidia's explosive rally end soon?,2026-04-27T13:34:29Z
2,NVDA,Mag 7 earnings bonanza and Powell's home stret...,2026-04-26T11:30:16Z
3,NVDA,The First 5 Quantum Computing Stocks I'd Buy I...,2026-04-27T16:58:00Z
4,NVDA,Is Palantir Technologies Stock More Likely to ...,2026-04-27T16:50:00Z

### PHASE 2 : Sentiment Scoring

In [21]:
from src.sentiment import analyze_sentiment

In [22]:
label_results = []
score_results = []

for title in headline_data["title"]:
    sentiment = analyze_sentiment(title)
    label_results.append(sentiment[0][0]["label"])
    score_results.append(sentiment[0][0]["score"])

In [23]:
headline_data["label"] = label_results
headline_data["score"] = score_results
headline_data

,ticker,title,date,label,score
0,NVDA,"Google, Meta, Microsoft, Amazon, Apple earning...",2026-04-27T15:12:48Z,neutral,0.999750
1,NVDA,Will Nvidia's explosive rally end soon?,2026-04-27T13:34:29Z,neutral,0.999140
2,NVDA,Mag 7 earnings bonanza and Powell's home stret...,2026-04-26T11:30:16Z,positive,0.998653
3,NVDA,The First 5 Quantum Computing Stocks I'd Buy I...,2026-04-27T16:58:00Z,neutral,0.999864
4,NVDA,Is Palantir Technologies Stock More Likely to ...,2026-04-27T16:50:00Z,positive,0.987733
5,NVDA,Stock Market Today: Dow Dips While Intel Gains...,2026-04-27T16:48:23Z,positive,0.397146
6,NVDA,OpenAI and Microsoft Just Revamped Their Longs...,2026-04-27T16:44:41Z,positive,0.999462
7,NVDA,AMD Is Up 65% in April: It’s Not Just Intel Mo...,2026-04-27T16:42:20Z,positive,0.999623
8,NVDA,Why Domino's Pizza Stock Dove Today,2026-04-27T16:30:03Z,neutral,0.999835
9,NVDA,Why AMD Can Stay Hotter Longer Than NVIDIA,2026-04-27T16:26:47Z,positive,0.993110
10,META,"Shell acquiring Arc for $13.6B, China blocks M...",2026-04-27T17:06:44Z,negative,0.749919
11,META,Amazon's 2026 CapEx spend: What Polymarket is ...,2026-04-27T14:34:01Z,neutral,0.999784
12,META,Why this strategist is bullish on Zoom,2026-04-27T10:00:00Z,positive,0.999091
13,META,"Stock Market Today, April 27: Rally Stalls at ...",2026-04-27T17:00:44Z,neutral,0.895516
14,META,Meta loses $2B Manus AI deal after China block...,2026-04-27T16:29:00Z,negative,0.996713
15,META,Nvidia Adding To $5 Trillion Market Cap With B...,2026-04-27T16:17:55Z,positive,0.998903
16,META,Why the Uptick in Layoffs Isn’t as Scary as It...,2026-04-27T16:16:00Z,negative,0.931200
17,META,"These Stocks Are Today’s Movers: Tesla, Qualco...",2026-04-27T16:05:00Z,neutral,0.999887
18,META,AMD CEO Says We’re Only in Year 2 of 10-Year A...,2026-04-27T16:00:52Z,neutral,0.999807
19,META,NBA Legend Shaquille O'Neal Says He's A Glass ...,2026-04-27T15:46:03Z,neutral,0.999824
20,MSFT,Earnings live updates: Domino's stock falls a...,2026-04-27T11:14:14Z,negative,0.996468
21,MSFT,Amazon's 2026 CapEx spend: What Polymarket is ...,2026-04-27T14:34:01Z,neutral,0.999784
22,MSFT,Elon Musk set to face off against Sam Altman i...,2026-04-27T13:30:47Z,neutral,0.999810
23,MSFT,Why this strategist is bullish on Zoom,2026-04-27T10:00:00Z,positive,0.999091
24,MSFT,"Stock Market Today, April 27: Rally Stalls at ...",2026-04-27T17:00:44Z,neutral,0.895516
25,MSFT,Microsoft And OpenAI Partnership Changes. Why ...,2026-04-27T16:57:00Z,neutral,0.819684
26,MSFT,"Microsoft, OpenAI Amend Partnership; Wedbush S...",2026-04-27T16:55:14Z,positive,0.999536
27,MSFT,Microsoft Q3 Earnings Preview — Can Strong Res...,2026-04-27T16:44:56Z,positive,0.999088
28,MSFT,OpenAI and Microsoft Just Revamped Their Longs...,2026-04-27T16:44:41Z,positive,0.999462
29,MSFT,Elon Musk and Sam Altman prepare to face off i...,2026-04-27T16:34:09Z,neutral,0.999797
30,AMD,"Google, Meta, Microsoft, Amazon, Apple earning...",2026-04-27T15:12:48Z,neutral,0.999750
31,AMD,Will Nvidia's explosive rally end soon?,2026-04-27T13:34:29Z,neutral,0.999140
32,AMD,AMD Is Up 65% in April: It’s Not Just Intel Mo...,2026-04-27T16:42:20Z,positive,0.999623
33,AMD,Why AMD Can Stay Hotter Longer Than NVIDIA,2026-04-27T16:26:47Z,positive,0.993110
34,AMD,The 1 Number That Shows Why Nvidia Is Not Done...,2026-04-27T16:22:13Z,positive,0.955640
35,AMD,Intel’s Latest Surge Just Made History. But Th...,2026-04-27T16:02:37Z,positive,0.739845
36,AMD,AMD CEO Says We’re Only in Year 2 of 10-Year A...,2026-04-27T16:00:52Z,neutral,0.999807
37,AMD,Northland Downgrades AMD to Market Perform: Is...,2026-04-27T15:41:50Z,negative,0.997988
38,AMD,Intel Stock Rally Rages On. What UBS Says It U...,2026-04-27T14:39:00Z,negative,0.574612
39,AMD,Jim Cramer Shares Why You Should Buy Advanced ...,2026-04-27T14:21:41Z,neutral,0.999836
40,GOOGL,"Tech stocks today: Qualcomm stock soars, Micro...",2026-04-27T11:35:35Z,positive,0.998760
41,GOOGL,Microsoft And OpenAI Partnership Changes. Why ...,2026-04-27T16:57:00Z,neutral,0.819684
42,GOOGL,Stock Market Today: Dow Dips While Intel Gains...,2026-04-27T16:48:23Z,positive,0.397146
43,GOOGL,"Broadcom, IBD Stock Of The Day, Hovers Near Bu...",2026-04-27T16:37:37Z,neutral,0.999361
44,GOOGL,Google gets pointers from EU regulators on hel...,2026-04-27T16:23:02Z,positive,0.967163
45,GOOGL,The 1 Number That Shows Why Nvidia Is Not Done...,2026-04-27T16:22:13Z,positive,0.955640
46,GOOGL,Nvidia Adding To $5 Trillion Market Cap With B...,2026-04-27T16:17:55Z,positive,0.998903
47,GOOGL,"Apple, Google Crushed California Bill Helping ...",2026-04-27T16:16:00Z,negative,0.982565
48,GOOGL,NBA Legend Shaquille O'Neal Says He's A Glass ...,2026-04-27T15:46:03Z,neutral,0.999824
49,GOOGL,DeepMind researcher raises $1.1B for Ineffable...,2026-04-27T15:44:50Z,positive,0.970825

In [24]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322174  196.210266  259.299255  24.206572
2023-03-16  96.599998   99.497650  203.334320  269.810394  25.518410
2023-03-17  97.839996  100.786987  194.086899  272.965576  25.702248
2023-03-20  96.809998  100.390274  196.269791  265.932312  25.877090
2023-03-21  95.930000  104.059944  200.585907  267.446350  26.175829

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135452  196.240031  260.315204  24.264519  ...
2023-03-16  96.690002  100.360521  204.157859  270.162052  25.565367  ...
2023-03-17  98.750000  101.996980  200.327916  276.775346  26.375651  ...
2023-03-20  96.940002  100.915928  197.807725  271.060860  26.000981  ...
2023-03-21  99.459999  104.238469  201.965083  268.638128  26.368659  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455864  191.447637  253.965577  23.739984
2023-03-16  89.720001   95.411420  196.716257  259.074617  24.005749
2023-03-17  96.660004   99.438135  198.998353  271.822660  25.959020
2023-03-20  96.300003   99.299293  196.934572  270.572427  25.592343
2023-03-21  97.000000  100.420030  201.617802  268.520909  26.156847

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

### Phase 3 : Analyze data

In [25]:
# Reshape data

reshaped_data = df["Close"].stack().reset_index().rename(columns={0: "close", "Ticker": "ticker", "Date": "date"})
reshaped_data.head()

        date ticker       close
0 2023-03-15    AMD   89.680000
1 2023-03-15  GOOGL   95.322174
2 2023-03-15   META  196.210266
3 2023-03-15   MSFT  259.299255
4 2023-03-15   NVDA   24.206572

In [26]:
reshaped_data = reshaped_data.set_index("date")

In [27]:
# Group data by months

# reshaped_data.dtypes

reshaped_data.groupby(["ticker", pd.Grouper(freq="ME")])["close"].mean()

ticker  date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
                         ...
NVDA    2025-11-30    187.962520
        2025-12-31    182.324673
        2026-01-31    186.711894
        2026-02-28    185.701528
        2026-03-31    182.350104
Name: close, Length: 185, dtype: float64

In [28]:
# Explore monthly trends

monthly_close = reshaped_data.groupby(["ticker", pd.Grouper(freq="ME")])["close"].mean()
monthly_close.head()

ticker  date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
Name: close, dtype: float64

In [29]:
reshaped_data.groupby(["ticker", pd.Grouper(freq="QE")])["close"].mean()

ticker  date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
                         ...
NVDA    2025-03-31    126.703981
        2025-06-30    125.817829
        2025-09-30    174.281515
        2025-12-31    186.121490
        2026-03-31    185.429958
Name: close, Length: 65, dtype: float64

In [30]:
# Explore quarterly trends

quarterly_close = reshaped_data.groupby(["ticker", pd.Grouper(freq="QE")])["close"].mean()
quarterly_close.head()

ticker  date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
Name: close, dtype: float64

In [31]:
headline_data.groupby(["ticker", "label"])["label"].count()

ticker  label
AMD     negative    2
        neutral     4
        positive    4
GOOGL   negative    1
        neutral     3
        positive    6
META    negative    3
        neutral     5
        positive    2
MSFT    negative    1
        neutral     5
        positive    4
NVDA    neutral     4
        positive    6
Name: label, dtype: int64

In [32]:
sentiment_count = headline_data.groupby(["ticker", "label"])["label"].count()

In [33]:
headline_data.groupby(["ticker"])["score"].mean()

ticker
AMD      0.925935
GOOGL    0.908987
META     0.957064
MSFT     0.970824
NVDA     0.937432
Name: score, dtype: float64

In [34]:
score_avg = headline_data.groupby(["ticker"])["score"].mean()

In [35]:
first_close = quarterly_close.groupby("ticker").first()
last_close = quarterly_close.groupby("ticker").last()

In [36]:
((last_close - first_close) / first_close) * 100

ticker
AMD      123.770470
GOOGL    214.705783
META     224.733352
MSFT      57.974547
NVDA     603.180105
Name: close, dtype: float64

In [37]:
stock_roc = ((last_close - first_close) / first_close) * 100

In [38]:
# All my analysis variables

# sentiment_count — label counts per ticker
# score_avg — average confidence score per ticker
# quarterly_close — price trend over 12 quarterly_close
# stock_roc — overall % price change over 3 years

In [39]:
headline_data[headline_data["score"] < 0.80]

,ticker,title,date,label,score
5,NVDA,Stock Market Today: Dow Dips While Intel Gains...,2026-04-27T16:48:23Z,positive,0.397146
10,META,"Shell acquiring Arc for $13.6B, China blocks M...",2026-04-27T17:06:44Z,negative,0.749919
35,AMD,Intel’s Latest Surge Just Made History. But Th...,2026-04-27T16:02:37Z,positive,0.739845
38,AMD,Intel Stock Rally Rages On. What UBS Says It U...,2026-04-27T14:39:00Z,negative,0.574612
42,GOOGL,Stock Market Today: Dow Dips While Intel Gains...,2026-04-27T16:48:23Z,positive,0.397146

In [40]:
low_confidence = headline_data[headline_data["score"] < 0.80]

### Phase 4 : Visualize data

In [41]:
quarterly_df = quarterly_close.reset_index()

In [42]:
px.line(
    data_frame=quarterly_df, 
    x="date", 
    y="close", 
    color="ticker", 
    title="Q1 '23—Q2 '26 Quarterly Stock Prices"
    )

In [43]:
sentiment_df = sentiment_count.reset_index(name="count")

In [44]:
# Stacked bar chart
# px.bar(data_frame=sentiment_df, x="ticker", y="count", color="label", title="Recent News Headlines Sentiment")

In [45]:
px.bar(
    data_frame=sentiment_df,
    x="ticker", 
    y="count", 
    color="label", 
    barmode="group",
    title="Recent News Headlines Sentiment", 
    color_discrete_map = {
        "positive": "#48a860", 
        "neutral": "#bebdb8", 
        "negative": "#cd5c5c"
        }
    )

In [46]:
price_chart = px.line(
    data_frame=quarterly_df, 
    x="date", 
    y="close", 
    color="ticker", 
    title="Q1 '23—Q2 '26 Quarterly Stock Prices"
    )

sentiment_chart = px.bar(
    data_frame=sentiment_df,
    x="ticker", 
    y="count", 
    color="label", 
    barmode="group",
    title="Recent News Headlines Sentiment", 
    color_discrete_map = {
        "positive": "#48a860", 
        "neutral": "#bebdb8", 
        "negative": "#cd5c5c"
        }
    )

In [47]:
price_chart.write_html("outputs/price_chart.html")
sentiment_chart.write_html("outputs/sentiment_chart.html")

In [84]:
# Creates empty subplot container

fig = make_subplots(
    rows=2,
    cols=1,
    subplot_titles=("Quarterly Close Price (2023-2026)", "Current News Sentiment by Ticker")
    )

In [85]:
for trace in price_chart.data:
    fig.add_trace(trace, row=1, col=1)

for trace in sentiment_chart.data:
    fig.add_trace(trace, row=2, col=1)

In [86]:
fig.update_layout(
    title_text="AI Stock Performance & Current Sentiment Analysis",
    height=800
)

In [87]:
fig.write_html("outputs/stock_dashboard.html")

In [88]:
quarterly_close.index.get_level_values("date").max()

Timestamp('2026-03-31 00:00:00')

In [89]:
last_close

ticker
AMD      216.165714
GOOGL    318.872785
META     653.582659
MSFT     427.593246
NVDA     185.429958
Name: close, dtype: float64

In [90]:
stock_roc

ticker
AMD      123.770470
GOOGL    214.705783
META     224.733352
MSFT      57.974547
NVDA     603.180105
Name: close, dtype: float64

In [91]:
for ticker in last_close.index:
    fig.add_annotation(
        x = "2026-03-31",
        y = last_close[ticker],
        text = f"+{stock_roc[ticker]:.1f}%",
        font = dict(size=10)
    )

In [92]:
fig

In [94]:
fig.write_html("outputs/stock_dashboard.html")