### PHASE 1 : Collecting data

In [1]:
# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
# List to capture AI stocks—AI infrastructure and AI-powered companies.
stocks = ["NVDA", "META", "MSFT", "AMD", "GOOGL"]

In [3]:
# df is Dataframe—function which passes in stocks and date range for df.
df = yf.download(tickers=stocks, start="2023-03-15", end="2026-03-15")

[*********************100%***********************]  5 of 5 completed

In [4]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322151  196.210236  259.299286  24.206572
2023-03-16  96.599998   99.497658  203.334320  269.810364  25.518410
2023-03-17  97.839996  100.786995  194.086914  272.965668  25.702246
2023-03-20  96.809998  100.390266  196.269775  265.932190  25.877090
2023-03-21  95.930000  104.059937  200.585907  267.446320  26.175827

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135429  196.240001  260.315235  24.264519  ...
2023-03-16  96.690002  100.360529  204.157859  270.162021  25.565367  ...
2023-03-17  98.750000  101.996988  200.327931  276.775439  26.375649  ...
2023-03-20  96.940002  100.915921  197.807710  271.060735  26.000981  ...
2023-03-21  99.459999  104.238461  201.965083  268.638097  26.368657  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455842  191.447607  253.965606  23.739984
2023-03-16  89.720001   95.411427  196.716257  259.074588  24.005749
2023-03-17  96.660004   99.438143  198.998369  271.822751  25.959018
2023-03-20  96.300003   99.299285  196.934557  270.572303  25.592343
2023-03-21  97.000000  100.420022  201.617802  268.520878  26.156845

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [5]:
df.columns

MultiIndex([( 'Close',   'AMD'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'META'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'NVDA'),
            (  'High',   'AMD'),
            (  'High', 'GOOGL'),
            (  'High',  'META'),
            (  'High',  'MSFT'),
            (  'High',  'NVDA'),
            (   'Low',   'AMD'),
            (   'Low', 'GOOGL'),
            (   'Low',  'META'),
            (   'Low',  'MSFT'),
            (   'Low',  'NVDA'),
            (  'Open',   'AMD'),
            (  'Open', 'GOOGL'),
            (  'Open',  'META'),
            (  'Open',  'MSFT'),
            (  'Open',  'NVDA'),
            ('Volume',   'AMD'),
            ('Volume', 'GOOGL'),
            ('Volume',  'META'),
            ('Volume',  'MSFT'),
            ('Volume',  'NVDA')],
           names=['Price', 'Ticker'])

In [6]:
df.shape

(752, 25)

In [7]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 752 entries, 2023-03-15 to 2026-03-13
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, AMD)     752 non-null    float64
 1   (Close, GOOGL)   752 non-null    float64
 2   (Close, META)    752 non-null    float64
 3   (Close, MSFT)    752 non-null    float64
 4   (Close, NVDA)    752 non-null    float64
 5   (High, AMD)      752 non-null    float64
 6   (High, GOOGL)    752 non-null    float64
 7   (High, META)     752 non-null    float64
 8   (High, MSFT)     752 non-null    float64
 9   (High, NVDA)     752 non-null    float64
 10  (Low, AMD)       752 non-null    float64
 11  (Low, GOOGL)     752 non-null    float64
 12  (Low, META)      752 non-null    float64
 13  (Low, MSFT)      752 non-null    float64
 14  (Low, NVDA)      752 non-null    float64
 15  (Open, AMD)      752 non-null    float64
 16  (Open, GOOGL)    752 non-null    float64
 17  (Open, META)     752 non-null    float64
 18  (Open, MSFT)     752 non-null    float64
 19  (Open, NVDA)     752 non-null    float64
 20  (Volume, AMD)    752 non-null    int64
 21  (Volume, GOOGL)  752 non-null    int64
 22  (Volume, META)   752 non-null    int64
 23  (Volume, MSFT)   752 non-null    int64
 24  (Volume, NVDA)   752 non-null    int64
dtypes: float64(20), int64(5)
memory usage: 152.8 KB

In [8]:
df.describe()

Price        Close                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.828324  178.303726  510.032442  406.722717  110.174772
std      41.766704   59.267770  163.535076   64.594056   53.493754
min      78.209999   95.322151  194.086914  259.299286   24.206572
25%     112.002502  136.263775  335.286346  365.005585   48.840425
50%     141.760002  164.499840  524.088867  409.369675  116.998013
75%     169.445004  190.765556  645.484024  447.321579  146.969254
max     264.329987  343.448242  788.148987  539.825195  207.017273

Price         High                                                  ...  \
Ticker         AMD       GOOGL        META        MSFT        NVDA  ...
count   752.000000  752.000000  752.000000  752.000000  752.000000  ...
mean    149.719827  180.249596  516.432463  410.145541  111.981672  ...
std      42.878968   60.022627  165.473901   64.914353   54.248785  ...
min      85.480003   96.135429  196.240001  260.315235   24.264519  ...
25%     114.395002  137.528329  337.253388  368.108833   49.556453  ...
50%     144.289993  165.989440  532.311022  412.460437  119.131434  ...
75%     172.049995  192.186486  652.566306  450.570354  148.926131  ...
max     267.079987  348.754481  794.384398  552.242002  212.166717  ...

Price         Open                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.924468  178.153442  510.100256  406.707280  110.223178
std      41.941908   59.299622  164.119505   64.850846   53.622100
min      79.220001   92.455842  191.447607  253.965606   23.739984
25%     112.052500  136.271205  335.187120  364.869620   49.125131
50%     142.730003  164.479684  524.796369  410.068699  117.272922
75%     169.307503  190.554032  642.907274  446.764570  147.766449
max     264.190002  347.095646  789.296390  552.023241  208.057150

Price         Volume
Ticker           AMD         GOOGL          META          MSFT          NVDA
count   7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02
mean    5.305591e+07  3.181655e+07  1.695474e+07  2.381806e+07  3.364204e+08
std     2.434066e+07  1.357632e+07  9.409263e+06  1.046421e+07  1.752086e+08
min     7.956800e+06  1.009740e+07  4.726100e+06  5.855900e+06  6.552850e+07
25%     3.606890e+07  2.321348e+07  1.131440e+07  1.726135e+07  1.955628e+08
50%     4.822515e+07  2.849140e+07  1.495705e+07  2.121225e+07  3.052285e+08
75%     6.357465e+07  3.573692e+07  1.942280e+07  2.670622e+07  4.300298e+08
max     2.488596e+08  1.274901e+08  8.844010e+07  1.288553e+08  1.543911e+09

[8 rows x 25 columns]

In [9]:
df.tail()

Price            Close                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  202.679993  306.359985  646.836182  409.410004  182.640106
2026-03-10  203.229996  307.040009  653.510498  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.299805  404.880005  186.029999
2026-03-12  197.740005  303.549988  637.634094  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.184998  395.549988  180.250000

Price             High                                                  ...  \
Ticker             AMD       GOOGL        META        MSFT        NVDA  ...
Date                                                                    ...
2026-03-09  202.970001  306.799988  647.195859  410.209991  182.900102  ...
2026-03-10  206.589996  309.510010  659.735149  410.200012  186.429918  ...
2026-03-11  209.210007  311.420013  658.556170  409.010010  187.619995  ...
2026-03-12  203.619995  308.940002  652.940997  406.119995  184.940002  ...
2026-03-13  199.679993  307.690002  628.631733  404.799988  186.089996  ...

Price             Open                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  189.360001  294.359985  634.236984  404.920013  176.820429
2026-03-10  202.509995  306.170013  653.000925  410.029999  182.390128
2026-03-11  205.110001  306.750000  654.199915  405.570007  185.910004
2026-03-12  202.830002  306.820007  648.195060  404.630005  184.050003
2026-03-13  198.110001  307.010010  623.356281  401.000000  184.919998

Price         Volume
Ticker           AMD     GOOGL      META      MSFT       NVDA
Date
2026-03-09  38877200  29312100  13489700  30131900  177213600
2026-03-10  29139200  23239700   9859300  31706400  179118500
2026-03-11  23076400  24125700   8977200  25512100  145280400
2026-03-12  28886900  24928300  11617500  27263900  155762700
2026-03-13  27561900  23693100  18957600  26848000  160988400

[5 rows x 25 columns]

In [10]:
df["Low"]

Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2023-03-15   86.220001   91.880595  189.354036  253.213401   23.339339
2023-03-16   89.019997   94.717169  194.563156  257.189244   23.872865
2023-03-17   95.940002   99.279451  193.908308  269.927629   25.645295
2023-03-20   92.900002   99.051334  192.132246  263.607245   25.107771
2023-03-21   93.639999  100.390270  196.408681  263.284862   25.358552
...                ...         ...         ...         ...         ...
2026-03-09  189.020004  294.079987  626.243828  403.500000  175.550494
2026-03-10  202.199997  305.570007  648.444828  402.929993  182.000149
2026-03-11  203.630005  305.920013  647.805365  401.589996  184.449997
2026-03-12  196.669998  301.029999  636.355221  401.709991  181.750000
2026-03-13  192.270004  300.440002  609.028522  394.250000  179.940002

[752 rows x 5 columns]

In [11]:
df["Low"]["NVDA"]

Date
2023-03-15     23.339339
2023-03-16     23.872865
2023-03-17     25.645295
2023-03-20     25.107771
2023-03-21     25.358552
                 ...
2026-03-09    175.550494
2026-03-10    182.000149
2026-03-11    184.449997
2026-03-12    181.750000
2026-03-13    179.940002
Name: NVDA, Length: 752, dtype: float64

In [12]:
(df == 0).any().sum()

np.int64(0)

In [13]:
df["Close"]
close_prices = df["Close"]

In [14]:
yf.Ticker("NVDA").news

[{'id': '46cf59bf-dcda-4f71-b8a1-905a63977734',
  'content': {'id': '46cf59bf-dcda-4f71-b8a1-905a63977734',
   'contentType': 'STORY',
   'title': 'Intel to report first quarter earnings as CPUs become key to AI growth',
   'description': '',
   'summary': 'Intel will report its first quarter earnings after the bell on Thursday.',
   'pubDate': '2026-04-22T19:15:52Z',
   'displayTime': '2026-04-22T19:15:52Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/iBPAsRQ9SHH.YMV0DXmccQ--~B/aD0yMDAxO3c9MzAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/7e6fc4e3-ece1-4914-b658-b6b2977b63bd',
    'originalWidth': 3000,
    'originalHeight': 2001,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/iBPAsRQ9SHH.YMV0DXmccQ--~B/aD0yMDAxO3c9MzAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/7e6fc4e3-ece1-4914-b658-b6b2977b63bd',
      'width': 3000,
      'height': 2001,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/IJPMZ_TuRV45626GjYLaig--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-04/7e6fc4e3-ece1-4914-b658-b6b2977b63bd',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/intel-to-report-first-quarter-earnings-as-cpus-become-key-to-ai-growth-191552358.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/intel-to-report-first-quarter-earnings-as-cpus-become-key-to-ai-growth-191552358.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': {'storylineItems': [{'content': {'id': '87c00f7d-c454-4024-bd93-3ddac13b2950',
       'contentType': 'STORY',
       'isHosted': True,
       'title': "One new clue that Nvidia's Jensen Huang and TSMC are right about AI demand strength",
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-03/0c7e65e0-2170-11f1-bef7-a44ecaa04b4c',
        'originalWidth': 2547,
        'originalHeight': 1698,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/news/one-new-clue-that-nvidias-jensen-huang-and-tsmc-are-right-about-ai-demand-strength-162138937.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/one-new-clue-that-nvidias-jensen-huang-and-tsmc-are-right-about-ai-demand-strength-162138937.html'}}},
     {'content': {'id': 'cc14e3a7-9bcd-4cca-8962-e7df54671ff3',
       'contentType': 'VIDEO',
       'isHosted': True,
       'title': 'Google takes on Nvidia, announces 2 new AI chips',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/KCX2BuYoBo9OTQzqJNiz7A--~B/aD0yMjE3O3c9Mzk0MzthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/22a40193-bbd0-4c65-ba50-021df95c887d_49a63cf1912982d9d8af7ce4e0897247b55edd64461a0112771e47327ec72aea.net/images/2026-04/22a40193-bbd0-4c65-ba50-021df95c887d',
        'originalWidth': 3943,
        'originalHeight': 2217,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance Video',
        'sourceId': 'video.yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/video/google-takes-on-nvidia-announces-2-new-ai-chips-145915437.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/google-takes-on-nvidia-announces-2-new-ai-chips-145915437.html'}}}]}}},
 {'id': 'bdceca76-2cc8-4055-8c06-db1643cfa02a',
  'content': {'id': 'bdceca76-2cc8-4055-8c06-db1643cfa02a',
   'contentType': 'VIDEO',
   'title': 'GE Vernova stock surges on Q1 earnings, AI data center demand',
   'description': '<p>GE Vernova (<a target="_blank" rel="" class="link" href="https://finance.yahoo.com/quote/GEV/" data-i13n="slk:GEV;cpos:1;pos:1">GEV</a>) stock is surging on Wednesday after beating first quarter earnings estimates.</p>\n<p>Morning Brief Host Julie Hyman and Yahoo Finance Head of News Myles Udland dive into the energy company\'s quarterly results amid the latest forecasts for AI data center demands.</p>',
   'summary': "GE Vernova (GEV) stock is surging on Wednesday after beating first quarter earnings estimates. Morning Brief Host Julie Hyman and Yahoo Finance Head of News Myles Udland dive into the energy company's quarterly results amid the latest forecasts for AI data center demands.",
   'pubDate': '2026-04-22T14:38:59Z',
   'displayTime': '',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/LrWkjX4xesyF1b9pG8OmOA--~B/aD00NTA7dz04MDA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/a29c6141-be45-4337-b913-e3fdee09c7fd_941d159eae5c4852ebc14b6791bc7057c38d63a9df52fce1ab48161481666407.net/images/2026-04/a29c6141-be45-4337-b913-e3fdee09c7fd',
    'originalWidth': 800,
    'originalHeight': 450,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/LrWkjX4xesyF1b9pG8OmOA--~B/aD00NTA7dz04MDA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/a29c6141-be45-4337-b913-e3fdee09c7fd_941d159eae5c4852ebc14b6791bc7057c38d63a9df52fce1ab48161481666407.net/images/2026-04/a29c6141-be45-4337-b913-e3fdee09c7fd',
      'width': 800,
      'height': 450,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/v6dcFeHXTL8p0EWql5xArg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/a29c6141-be45-4337-b913-e3fdee09c7fd_941d159eae5c4852ebc14b6791bc7057c38d63a9df52fce1ab48161481666407.net/images/2026-04/a29c6141-be45-4337-b913-e3fdee09c7fd',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance Video',
    'url': 'https://finance.yahoo.com/',
    'sourceId': 'video.yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/video/ge-vernova-stock-surges-on-q1-earnings-ai-data-center-demand-143859232.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/ge-vernova-stock-surges-on-q1-earnings-ai-data-center-demand-143859232.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}}]

In [15]:
headlines = []

for stock in stocks:
    news = yf.Ticker(stock).news
    for article in news:
        headlines.append({
            "ticker": stock,
            "title": article["content"]["title"],
            "date": article["content"]["pubDate"]
        })

In [16]:
# Show all content and metadata for single headline
yf.Ticker("NVDA").news[0]

{'id': '46cf59bf-dcda-4f71-b8a1-905a63977734',
 'content': {'id': '46cf59bf-dcda-4f71-b8a1-905a63977734',
  'contentType': 'STORY',
  'title': 'Intel to report first quarter earnings as CPUs become key to AI growth',
  'description': '',
  'summary': 'Intel will report its first quarter earnings after the bell on Thursday.',
  'pubDate': '2026-04-22T19:15:52Z',
  'displayTime': '2026-04-22T19:15:52Z',
  'isHosted': True,
  'bypassModal': False,
  'previewUrl': None,
  'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/iBPAsRQ9SHH.YMV0DXmccQ--~B/aD0yMDAxO3c9MzAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/7e6fc4e3-ece1-4914-b658-b6b2977b63bd',
   'originalWidth': 3000,
   'originalHeight': 2001,
   'caption': '',
   'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/iBPAsRQ9SHH.YMV0DXmccQ--~B/aD0yMDAxO3c9MzAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/7e6fc4e3-ece1-4914-b658-b6b2977b63bd',
     'width': 3000,
     'height': 2001,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/IJPMZ_TuRV45626GjYLaig--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-04/7e6fc4e3-ece1-4914-b658-b6b2977b63bd',
     'width': 170,
     'height': 128,
     'tag': '170x128'}]},
  'provider': {'displayName': 'Yahoo Finance',
   'url': 'http://finance.yahoo.com/',
   'sourceId': 'yahoofinance.com'},
  'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/intel-to-report-first-quarter-earnings-as-cpus-become-key-to-ai-growth-191552358.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/intel-to-report-first-quarter-earnings-as-cpus-become-key-to-ai-growth-191552358.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'metadata': {'editorsPick': True},
  'finance': {'premiumFinance': {'isPremiumNews': False,
    'isPremiumFreeNews': False}},
  'storyline': {'storylineItems': [{'content': {'id': '87c00f7d-c454-4024-bd93-3ddac13b2950',
      'contentType': 'STORY',
      'isHosted': True,
      'title': "One new clue that Nvidia's Jensen Huang and TSMC are right about AI demand strength",
      'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-03/0c7e65e0-2170-11f1-bef7-a44ecaa04b4c',
       'originalWidth': 2547,
       'originalHeight': 1698,
       'caption': '',
       'resolutions': None},
      'provider': {'displayName': 'Yahoo Finance',
       'sourceId': 'yahoofinance.com'},
      'previewUrl': None,
      'providerContentUrl': '',
      'canonicalUrl': {'url': 'https://finance.yahoo.com/news/one-new-clue-that-nvidias-jensen-huang-and-tsmc-are-right-about-ai-demand-strength-162138937.html'},
      'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/one-new-clue-that-nvidias-jensen-huang-and-tsmc-are-right-about-ai-demand-strength-162138937.html'}}},
    {'content': {'id': 'cc14e3a7-9bcd-4cca-8962-e7df54671ff3',
      'contentType': 'VIDEO',
      'isHosted': True,
      'title': 'Google takes on Nvidia, announces 2 new AI chips',
      'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/KCX2BuYoBo9OTQzqJNiz7A--~B/aD0yMjE3O3c9Mzk0MzthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/22a40193-bbd0-4c65-ba50-021df95c887d_49a63cf1912982d9d8af7ce4e0897247b55edd64461a0112771e47327ec72aea.net/images/2026-04/22a40193-bbd0-4c65-ba50-021df95c887d',
       'originalWidth': 3943,
       'originalHeight': 2217,
       'caption': '',
       'resolutions': None},
      'provider': {'displayName': 'Yahoo Finance Video',
       'sourceId': 'video.yahoofinance.com'},
      'previewUrl': None,
      'providerContentUrl': '',
      'canonicalUrl': {'url': 'https://finance.yahoo.com/video/google-takes-on-nvidia-announces-2-new-ai-chips-145915437.html'},
      'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/google-takes-on-nvidia-announces-2-new-ai-chips-145915437.html'}}}]}}}

In [17]:
headlines[0]

{'ticker': 'NVDA',
 'title': 'Intel to report first quarter earnings as CPUs become key to AI growth',
 'date': '2026-04-22T19:15:52Z'}

In [18]:
len(headlines)

50

In [19]:
# Flatten data

headline_data = pd.DataFrame(headlines)

In [20]:
headline_data.head()

,ticker,title,date
0,NVDA,Intel to report first quarter earnings as CPUs...,2026-04-22T19:15:52Z
1,NVDA,"GE Vernova stock surges on Q1 earnings, AI dat...",2026-04-22T14:38:59Z
2,NVDA,3 AI Chipmakers With Far More Upside Than AMD,2026-04-22T22:25:00Z
3,NVDA,"After Costco's Surge, Here Are the 3 Best S&P ...",2026-04-22T21:43:07Z
4,NVDA,Strategy (MSTR) Is Essentially a Leveraged Bit...,2026-04-22T21:31:00Z

### PHASE 2 : Sentiment Scoring

In [21]:
from src.sentiment import analyze_sentiment

In [22]:
label_results = []
score_results = []

for title in headline_data["title"]:
    sentiment = analyze_sentiment(title)
    label_results.append(sentiment[0][0]["label"])
    score_results.append(sentiment[0][0]["score"])

In [23]:
headline_data["label"] = label_results
headline_data["score"] = score_results
headline_data

,ticker,title,date,label,score
0,NVDA,Intel to report first quarter earnings as CPUs...,2026-04-22T19:15:52Z,neutral,0.776427
1,NVDA,"GE Vernova stock surges on Q1 earnings, AI dat...",2026-04-22T14:38:59Z,positive,0.999584
2,NVDA,3 AI Chipmakers With Far More Upside Than AMD,2026-04-22T22:25:00Z,neutral,0.668575
3,NVDA,"After Costco's Surge, Here Are the 3 Best S&P ...",2026-04-22T21:43:07Z,neutral,0.985426
4,NVDA,Strategy (MSTR) Is Essentially a Leveraged Bit...,2026-04-22T21:31:00Z,neutral,0.962416
5,NVDA,Adobe Just Announced a Huge Stock Buyback Prog...,2026-04-22T21:11:00Z,positive,0.999164
6,NVDA,Jensen Huang Says ‘Not One Company’ Can Match ...,2026-04-22T21:05:10Z,neutral,0.999798
7,NVDA,NVIDIA Corporation (NVDA) Sets Sight on $11B Q...,2026-04-22T20:48:17Z,positive,0.819867
8,NVDA,Is Micron Starting an Nvidia-Style Run?,2026-04-22T20:34:00Z,neutral,0.999866
9,NVDA,"Nvidia Is Cooling, Microsoft Is Stumbling, and...",2026-04-22T20:30:00Z,negative,0.658117
10,META,"Google takes on Nvidia, announces 2 new AI chips",2026-04-22T14:59:15Z,neutral,0.999854
11,META,Netflix's next attempt at growth takes on TikT...,2026-04-22T11:51:54Z,neutral,0.999827
12,META,"Trump Media has pivoted to crypto, financial s...",2026-04-22T22:01:23Z,negative,0.998130
13,META,Arista Networks Poised to Benefit from Google’...,2026-04-22T21:16:00Z,positive,0.999349
14,META,This Is the Impact of AI on Meta Platforms (ME...,2026-04-22T20:55:29Z,neutral,0.999888
15,META,This Powerhouse AI Stock Just Became More Valu...,2026-04-22T20:26:00Z,positive,0.999368
16,META,ARM Breaks Out Amid Leap from Licensing to In-...,2026-04-22T19:42:00Z,neutral,0.699387
17,META,"The $4,354 Breaking Point — Why a Single Medic...",2026-04-22T17:31:06Z,neutral,0.996242
18,META,META Rides on AI-Optimized Data Centers: What ...,2026-04-22T17:11:00Z,neutral,0.999836
19,META,4 Hot AI Stocks You May Not Have Heard Of: Sho...,2026-04-22T17:00:06Z,neutral,0.999835
20,MSFT,"Google takes on Nvidia, announces 2 new AI chips",2026-04-22T14:59:15Z,neutral,0.999854
21,MSFT,Tesla Q1 earnings: Should investors be betting...,2026-04-22T14:14:49Z,neutral,0.999629
22,MSFT,LinkedIn’s CEO is moving on; please hold your ...,2026-04-22T21:37:34Z,neutral,0.999639
23,MSFT,Arista Networks Poised to Benefit from Google’...,2026-04-22T21:16:00Z,positive,0.999349
24,MSFT,"Nasdaq, S&P 500 Notch Peaks as Earnings Fuel O...",2026-04-22T20:52:32Z,positive,0.999558
25,MSFT,Is Microsoft Corporation (MSFT) a Top AI Play ...,2026-04-22T20:50:18Z,positive,0.694227
26,MSFT,"Nvidia Is Cooling, Microsoft Is Stumbling, and...",2026-04-22T20:30:00Z,negative,0.658117
27,MSFT,Sector Update: Tech Stocks Rise Late Afternoon,2026-04-22T19:52:11Z,positive,0.998181
28,MSFT,Google Will Spend Up to $185 Billion This Year...,2026-04-22T19:19:50Z,positive,0.998572
29,MSFT,"Investor Cuts Stagwell Stake by 500,000 Shares...",2026-04-22T18:49:27Z,neutral,0.994476
30,AMD,"Google takes on Nvidia, announces 2 new AI chips",2026-04-22T14:59:15Z,neutral,0.999854
31,AMD,3 AI Chipmakers With Far More Upside Than AMD,2026-04-22T22:25:00Z,neutral,0.668575
32,AMD,This Is Why Advanced Micro Devices (AMD) Is a ...,2026-04-22T21:49:09Z,neutral,0.998779
33,AMD,Suze Orman Says Put 50% in VOO. Here’s Why She...,2026-04-22T19:51:34Z,neutral,0.999821
34,AMD,"Micron, AMD and Broadcom Shares Jump as AI Chi...",2026-04-22T18:24:18Z,positive,0.999488
35,AMD,AMD's Gross Margin to Contract Sequentially: I...,2026-04-22T17:36:00Z,positive,0.938412
36,AMD,Nvidia vs. AMD: One Is a Generational Buy — Th...,2026-04-22T17:34:41Z,neutral,0.998766
37,AMD,"Micron Soars 6%, AMD Rallies 4%, Broadcom Clim...",2026-04-22T16:08:38Z,positive,0.793903
38,AMD,Why Stifel Analysts Are Watching Intel Stock C...,2026-04-22T15:30:02Z,neutral,0.999823
39,AMD,How ISRG Just Secured The U.S. Market,2026-04-22T15:28:24Z,positive,0.894816
40,GOOGL,"Tech stocks today: Tesla earnings on deck, Goo...",2026-03-13T14:42:20Z,neutral,0.999706
41,GOOGL,"Google takes on Nvidia, announces 2 new AI chips",2026-04-22T14:59:15Z,neutral,0.999854
42,GOOGL,Netflix's next attempt at growth takes on TikT...,2026-04-22T11:51:54Z,neutral,0.999827
43,GOOGL,2 Surging Stocks with Impressive Fundamentals...,2026-04-22T21:33:23Z,negative,0.991882
44,GOOGL,"Stock Market Today, April 22: Alphabet Helps L...",2026-04-22T21:30:37Z,positive,0.999360
45,GOOGL,Arista Networks Poised to Benefit from Google’...,2026-04-22T21:16:00Z,positive,0.999349
46,GOOGL,Texas Announces Probe of Music Streaming Platf...,2026-04-22T21:15:00Z,neutral,0.999872
47,GOOGL,Jensen Huang Says ‘Not One Company’ Can Match ...,2026-04-22T21:05:10Z,neutral,0.999798
48,GOOGL,Google Cloud Launches $750 Million Partner Fun...,2026-04-22T21:04:00Z,positive,0.997974
49,GOOGL,"Stocks to Watch: United, Spirit, Boeing, Tesla",2026-04-22T20:54:12Z,neutral,0.999838

In [24]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322151  196.210236  259.299286  24.206572
2023-03-16  96.599998   99.497658  203.334320  269.810364  25.518410
2023-03-17  97.839996  100.786995  194.086914  272.965668  25.702246
2023-03-20  96.809998  100.390266  196.269775  265.932190  25.877090
2023-03-21  95.930000  104.059937  200.585907  267.446320  26.175827

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135429  196.240001  260.315235  24.264519  ...
2023-03-16  96.690002  100.360529  204.157859  270.162021  25.565367  ...
2023-03-17  98.750000  101.996988  200.327931  276.775439  26.375649  ...
2023-03-20  96.940002  100.915921  197.807710  271.060735  26.000981  ...
2023-03-21  99.459999  104.238461  201.965083  268.638097  26.368657  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455842  191.447607  253.965606  23.739984
2023-03-16  89.720001   95.411427  196.716257  259.074588  24.005749
2023-03-17  96.660004   99.438143  198.998369  271.822751  25.959018
2023-03-20  96.300003   99.299285  196.934557  270.572303  25.592343
2023-03-21  97.000000  100.420022  201.617802  268.520878  26.156845

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

### Phase 3 : Analyze data

In [25]:
# Reshape data

reshaped_data = df["Close"].stack().reset_index().rename(columns={0: "close", "Ticker": "ticker", "Date": "date"})
reshaped_data.head()

        date ticker       close
0 2023-03-15    AMD   89.680000
1 2023-03-15  GOOGL   95.322151
2 2023-03-15   META  196.210236
3 2023-03-15   MSFT  259.299286
4 2023-03-15   NVDA   24.206572

In [26]:
reshaped_data = reshaped_data.set_index("date")

In [27]:
# Group data by months

# reshaped_data.dtypes

reshaped_data.groupby(["ticker", pd.Grouper(freq="ME")])["close"].mean()

ticker  date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
                         ...
NVDA    2025-11-30    187.962520
        2025-12-31    182.324673
        2026-01-31    186.711894
        2026-02-28    185.701528
        2026-03-31    182.350104
Name: close, Length: 185, dtype: float64

In [28]:
# Explore monthly trends

monthly_close = reshaped_data.groupby(["ticker", pd.Grouper(freq="ME")])["close"].mean()
monthly_close.head()

ticker  date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
Name: close, dtype: float64

In [29]:
reshaped_data.groupby(["ticker", pd.Grouper(freq="QE")])["close"].mean()

ticker  date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
                         ...
NVDA    2025-03-31    126.703980
        2025-06-30    125.817829
        2025-09-30    174.281514
        2025-12-31    186.121490
        2026-03-31    185.429958
Name: close, Length: 65, dtype: float64

In [30]:
# Explore quarterly trends

quarterly_close = reshaped_data.groupby(["ticker", pd.Grouper(freq="QE")])["close"].mean()
quarterly_close.head()

ticker  date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
Name: close, dtype: float64

In [31]:
headline_data.groupby(["ticker", "label"])["label"].count()

ticker  label
AMD     neutral     6
        positive    4
GOOGL   negative    1
        neutral     6
        positive    3
META    negative    1
        neutral     7
        positive    2
MSFT    negative    1
        neutral     4
        positive    5
NVDA    negative    1
        neutral     6
        positive    3
Name: label, dtype: int64

In [32]:
sentiment_count = headline_data.groupby(["ticker", "label"])["label"].count()

In [33]:
headline_data.groupby(["ticker"])["score"].mean()

ticker
AMD      0.929224
GOOGL    0.998746
META     0.969171
MSFT     0.934160
NVDA     0.886924
Name: score, dtype: float64

In [34]:
score_avg = headline_data.groupby(["ticker"])["score"].mean()

In [35]:
first_close = quarterly_close.groupby("ticker").first()
last_close = quarterly_close.groupby("ticker").last()

In [36]:
((last_close - first_close) / first_close) * 100

ticker
AMD      123.770470
GOOGL    214.705787
META     224.733363
MSFT      57.974538
NVDA     603.180113
Name: close, dtype: float64

In [37]:
stock_roc = ((last_close - first_close) / first_close) * 100

In [38]:
# All my analysis variables

# sentiment_count — label counts per ticker
# score_avg — average confidence score per ticker
# quarterly_close — price trend over 12 quarterly_close
# stock_roc — overall % price change over 3 years

In [39]:
headline_data[headline_data["score"] < 0.80]

,ticker,title,date,label,score
0,NVDA,Intel to report first quarter earnings as CPUs...,2026-04-22T19:15:52Z,neutral,0.776427
2,NVDA,3 AI Chipmakers With Far More Upside Than AMD,2026-04-22T22:25:00Z,neutral,0.668575
9,NVDA,"Nvidia Is Cooling, Microsoft Is Stumbling, and...",2026-04-22T20:30:00Z,negative,0.658117
16,META,ARM Breaks Out Amid Leap from Licensing to In-...,2026-04-22T19:42:00Z,neutral,0.699387
25,MSFT,Is Microsoft Corporation (MSFT) a Top AI Play ...,2026-04-22T20:50:18Z,positive,0.694227
26,MSFT,"Nvidia Is Cooling, Microsoft Is Stumbling, and...",2026-04-22T20:30:00Z,negative,0.658117
31,AMD,3 AI Chipmakers With Far More Upside Than AMD,2026-04-22T22:25:00Z,neutral,0.668575
37,AMD,"Micron Soars 6%, AMD Rallies 4%, Broadcom Clim...",2026-04-22T16:08:38Z,positive,0.793903

In [40]:
low_confidence = headline_data[headline_data["score"] < 0.80]

### Phase 4 : Visualize data

In [41]:
quarterly_df = quarterly_close.reset_index()

In [42]:
px.line(
    data_frame=quarterly_df, 
    x="date", 
    y="close", 
    color="ticker", 
    title="Q1 '23—Q2 '26 Quarterly Stock Prices"
    )

In [43]:
sentiment_df = sentiment_count.reset_index(name="count")

In [44]:
# Stacked bar chart
# px.bar(data_frame=sentiment_df, x="ticker", y="count", color="label", title="Recent News Headlines Sentiment")

In [45]:
px.bar(
    data_frame=sentiment_df,
    x="ticker", 
    y="count", 
    color="label", 
    barmode="group",
    title="Recent News Headlines Sentiment", 
    color_discrete_map = {
        "positive": "#48a860", 
        "neutral": "#bebdb8", 
        "negative": "#cd5c5c"
        }
    )

In [46]:
price_chart = px.line(
    data_frame=quarterly_df, 
    x="date", 
    y="close", 
    color="ticker", 
    title="Q1 '23—Q2 '26 Quarterly Stock Prices"
    )

sentiment_chart = px.bar(
    data_frame=sentiment_df,
    x="ticker", 
    y="count", 
    color="label", 
    barmode="group",
    title="Recent News Headlines Sentiment", 
    color_discrete_map = {
        "positive": "#48a860", 
        "neutral": "#bebdb8", 
        "negative": "#cd5c5c"
        }
    )

In [47]:
price_chart.write_html("outputs/price_chart.html")
sentiment_chart.write_html("outputs/sentiment_chart.html")

In [48]:
# Creates empty subplot container

fig = make_subplots(
    rows=2,
    cols=1,
    subplot_titles=("Quarterly Close Price (2023-2026)", "Current News Sentiment by Ticker")
    )

In [49]:
for trace in price_chart.data:
    fig.add_trace(trace, row=1, col=1)

for trace in sentiment_chart.data:
    fig.add_trace(trace, row=2, col=1)

In [50]:
fig.update_layout(
    title_text="AI Stock Performance & Current Sentiment Analysis",
    height=800
)

In [51]:
fig.write_html("outputs/stock_dashboard.html")

In [52]:
quarterly_close.index.get_level_values("date").max()

Timestamp('2026-03-31 00:00:00')