### PHASE 1 : Collecting data

In [53]:
# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
# List to capture AI stocks—AI infrastructure and AI-powered companies.
stocks = ["NVDA", "META", "MSFT", "AMD", "GOOGL"]

In [3]:
# df is Dataframe—function which passes in stocks and date range for df.
df = yf.download(tickers=stocks, start="2023-03-15", end="2026-03-15")

[*********************100%***********************]  5 of 5 completed

In [4]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322159  196.210220  259.299347  24.206568
2023-03-16  96.599998   99.497643  203.334305  269.810364  25.518410
2023-03-17  97.839996  100.787003  194.086899  272.965637  25.702246
2023-03-20  96.809998  100.390274  196.269791  265.932220  25.877089
2023-03-21  95.930000  104.059937  200.585892  267.446381  26.175829

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135437  196.239986  260.315296  24.264515  ...
2023-03-16  96.690002  100.360514  204.157844  270.162021  25.565367  ...
2023-03-17  98.750000  101.996996  200.327916  276.775408  26.375649  ...
2023-03-20  96.940002  100.915928  197.807725  271.060767  26.000979  ...
2023-03-21  99.459999  104.238461  201.965068  268.638158  26.368659  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455850  191.447592  253.965666  23.739980
2023-03-16  89.720001   95.411413  196.716243  259.074588  24.005749
2023-03-17  96.660004   99.438150  198.998353  271.822721  25.959018
2023-03-20  96.300003   99.299293  196.934572  270.572334  25.592341
2023-03-21  97.000000  100.420022  201.617787  268.520939  26.156847

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [5]:
df.columns

MultiIndex([( 'Close',   'AMD'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'META'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'NVDA'),
            (  'High',   'AMD'),
            (  'High', 'GOOGL'),
            (  'High',  'META'),
            (  'High',  'MSFT'),
            (  'High',  'NVDA'),
            (   'Low',   'AMD'),
            (   'Low', 'GOOGL'),
            (   'Low',  'META'),
            (   'Low',  'MSFT'),
            (   'Low',  'NVDA'),
            (  'Open',   'AMD'),
            (  'Open', 'GOOGL'),
            (  'Open',  'META'),
            (  'Open',  'MSFT'),
            (  'Open',  'NVDA'),
            ('Volume',   'AMD'),
            ('Volume', 'GOOGL'),
            ('Volume',  'META'),
            ('Volume',  'MSFT'),
            ('Volume',  'NVDA')],
           names=['Price', 'Ticker'])

In [6]:
df.shape

(752, 25)

In [7]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 752 entries, 2023-03-15 to 2026-03-13
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, AMD)     752 non-null    float64
 1   (Close, GOOGL)   752 non-null    float64
 2   (Close, META)    752 non-null    float64
 3   (Close, MSFT)    752 non-null    float64
 4   (Close, NVDA)    752 non-null    float64
 5   (High, AMD)      752 non-null    float64
 6   (High, GOOGL)    752 non-null    float64
 7   (High, META)     752 non-null    float64
 8   (High, MSFT)     752 non-null    float64
 9   (High, NVDA)     752 non-null    float64
 10  (Low, AMD)       752 non-null    float64
 11  (Low, GOOGL)     752 non-null    float64
 12  (Low, META)      752 non-null    float64
 13  (Low, MSFT)      752 non-null    float64
 14  (Low, NVDA)      752 non-null    float64
 15  (Open, AMD)      752 non-null    float64
 16  (Open, GOOGL)    752 non-null    float64
 17  (Open, META)     752 non-null    float64
 18  (Open, MSFT)     752 non-null    float64
 19  (Open, NVDA)     752 non-null    float64
 20  (Volume, AMD)    752 non-null    int64
 21  (Volume, GOOGL)  752 non-null    int64
 22  (Volume, META)   752 non-null    int64
 23  (Volume, MSFT)   752 non-null    int64
 24  (Volume, NVDA)   752 non-null    int64
dtypes: float64(20), int64(5)
memory usage: 152.8 KB

In [8]:
df.describe()

Price        Close                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.828324  178.303726  510.032443  406.722718  110.174772
std      41.766704   59.267770  163.535076   64.594055   53.493754
min      78.209999   95.322159  194.086899  259.299347   24.206568
25%     112.002502  136.263779  335.286346  365.005585   48.840421
50%     141.760002  164.499832  524.088898  409.369659  116.998013
75%     169.445004  190.765568  645.484024  447.321556  146.969254
max     264.329987  343.448242  788.148987  539.825195  207.017273

Price         High                                                  ...  \
Ticker         AMD       GOOGL        META        MSFT        NVDA  ...
count   752.000000  752.000000  752.000000  752.000000  752.000000  ...
mean    149.719827  180.249597  516.432464  410.145543  111.981672  ...
std      42.878968   60.022627  165.473902   64.914351   54.248785  ...
min      85.480003   96.135437  196.239986  260.315296   24.264515  ...
25%     114.395002  137.528345  337.253430  368.108810   49.556456  ...
50%     144.289993  165.989432  532.311036  412.460421  119.131438  ...
75%     172.049995  192.186474  652.566306  450.570331  148.926147  ...
max     267.079987  348.754481  794.384398  552.242002  212.166717  ...

Price         Open                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.924468  178.153442  510.100257  406.707281  110.223178
std      41.941908   59.299621  164.119505   64.850845   53.622100
min      79.220001   92.455850  191.447592  253.965666   23.739980
25%     112.052500  136.271213  335.187120  364.869620   49.125136
50%     142.730003  164.479676  524.796369  410.068699  117.272922
75%     169.307503  190.554028  642.907274  446.764578  147.766464
max     264.190002  347.095646  789.296390  552.023241  208.057150

Price         Volume
Ticker           AMD         GOOGL          META          MSFT          NVDA
count   7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02
mean    5.305591e+07  3.181655e+07  1.695474e+07  2.381806e+07  3.364204e+08
std     2.434066e+07  1.357632e+07  9.409263e+06  1.046421e+07  1.752086e+08
min     7.956800e+06  1.009740e+07  4.726100e+06  5.855900e+06  6.552850e+07
25%     3.606890e+07  2.321348e+07  1.131440e+07  1.726135e+07  1.955628e+08
50%     4.822515e+07  2.849140e+07  1.495705e+07  2.121225e+07  3.052285e+08
75%     6.357465e+07  3.573692e+07  1.942280e+07  2.670622e+07  4.300298e+08
max     2.488596e+08  1.274901e+08  8.844010e+07  1.288553e+08  1.543911e+09

[8 rows x 25 columns]

In [9]:
df.tail()

Price            Close                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  202.679993  306.359985  646.836182  409.410004  182.640106
2026-03-10  203.229996  307.040009  653.510498  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.299805  404.880005  186.029999
2026-03-12  197.740005  303.549988  637.634094  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.184998  395.549988  180.250000

Price             High                                                  ...  \
Ticker             AMD       GOOGL        META        MSFT        NVDA  ...
Date                                                                    ...
2026-03-09  202.970001  306.799988  647.195859  410.209991  182.900102  ...
2026-03-10  206.589996  309.510010  659.735149  410.200012  186.429918  ...
2026-03-11  209.210007  311.420013  658.556170  409.010010  187.619995  ...
2026-03-12  203.619995  308.940002  652.940997  406.119995  184.940002  ...
2026-03-13  199.679993  307.690002  628.631733  404.799988  186.089996  ...

Price             Open                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  189.360001  294.359985  634.236984  404.920013  176.820429
2026-03-10  202.509995  306.170013  653.000925  410.029999  182.390128
2026-03-11  205.110001  306.750000  654.199915  405.570007  185.910004
2026-03-12  202.830002  306.820007  648.195060  404.630005  184.050003
2026-03-13  198.110001  307.010010  623.356281  401.000000  184.919998

Price         Volume
Ticker           AMD     GOOGL      META      MSFT       NVDA
Date
2026-03-09  38877200  29312100  13489700  30131900  177213600
2026-03-10  29139200  23239700   9859300  31706400  179118500
2026-03-11  23076400  24125700   8977200  25512100  145280400
2026-03-12  28886900  24928300  11617500  27263900  155762700
2026-03-13  27561900  23693100  18957600  26848000  160988400

[5 rows x 25 columns]

In [10]:
df["Low"]

Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2023-03-15   86.220001   91.880602  189.354021  253.213460   23.339336
2023-03-16   89.019997   94.717154  194.563141  257.189244   23.872865
2023-03-17   95.940002   99.279458  193.908292  269.927599   25.645295
2023-03-20   92.900002   99.051342  192.132261  263.607275   25.107769
2023-03-21   93.639999  100.390270  196.408666  263.284922   25.358553
...                ...         ...         ...         ...         ...
2026-03-09  189.020004  294.079987  626.243828  403.500000  175.550494
2026-03-10  202.199997  305.570007  648.444828  402.929993  182.000149
2026-03-11  203.630005  305.920013  647.805365  401.589996  184.449997
2026-03-12  196.669998  301.029999  636.355221  401.709991  181.750000
2026-03-13  192.270004  300.440002  609.028522  394.250000  179.940002

[752 rows x 5 columns]

In [11]:
df["Low"]["NVDA"]

Date
2023-03-15     23.339336
2023-03-16     23.872865
2023-03-17     25.645295
2023-03-20     25.107769
2023-03-21     25.358553
                 ...
2026-03-09    175.550494
2026-03-10    182.000149
2026-03-11    184.449997
2026-03-12    181.750000
2026-03-13    179.940002
Name: NVDA, Length: 752, dtype: float64

In [12]:
(df == 0).any().sum()

np.int64(0)

In [13]:
df["Close"]
close_prices = df["Close"]

In [14]:
yf.Ticker("NVDA").news

[{'id': '60b59ce6-a10a-4ded-922e-6fe6f99b1728',
  'content': {'id': '60b59ce6-a10a-4ded-922e-6fe6f99b1728',
   'contentType': 'STORY',
   'title': 'What to watch as Nvidia, AMD, and Broadcom report earnings',
   'description': '',
   'summary': 'Google, Meta, and Amazon are spending billions on AI infrastructure. Now, investors want to see the receipts.',
   'pubDate': '2026-04-21T13:16:36Z',
   'displayTime': '2026-04-21T13:16:36Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/3CCfzNk9UjQk6OZTI3b5Zg--~B/aD0yMjIzO3c9MzA3ODthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
    'originalWidth': 3078,
    'originalHeight': 2223,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/3CCfzNk9UjQk6OZTI3b5Zg--~B/aD0yMjIzO3c9MzA3ODthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
      'width': 3078,
      'height': 2223,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/KJIQVp4LonAqhUFpDXMi7g--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/what-to-watch-as-nvidia-amd-and-broadcom-report-earnings-131636149.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/what-to-watch-as-nvidia-amd-and-broadcom-report-earnings-131636149.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'e9dd8703-e753-34fe-a0bc-5985e48b4939',
  'content': {'id': 'e9dd8703-e753-34fe-a0bc-5985e48b4939',
   'contentType': 'STORY',
   'title': 'Want to Be a Millionaire? Buy Wall Street Tested Chainlink (LINK).',
   'description': '',
   'summary': 'This little token could have significant upside potential.',
   'pubDate': '2026-04-21T20:04:08Z',
   'displayTime': '2026-04-21T20:04:08Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/e4a8ee8f5f125cfaa809c8a639cb67e9',
    'originalWidth': 1400,
    'originalHeight': 787,
    'caption': 'A visualization of a blockchain.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/AJsr1SjQ_t_gWe30d_4MzQ--~B/aD03ODc7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/e4a8ee8f5f125cfaa809c8a639cb67e9',
      'width': 1400,
      'height': 787,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/xTFW.TndgpKbk1jy_pTRZw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/e4a8ee8f5f125cfaa809c8a639cb67e9',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/want-to-be-a-millionaire-buy-wallstreettested-chai/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/crypto/articles/want-millionaire-buy-wall-street-200408257.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '8db26b7a-b264-3b79-bd7b-7093c148a085',
  'content': {'id': '8db26b7a-b264-3b79-bd7b-7093c148a085',
   'contentType': 'STORY',
   'title': 'NVIDIA CEO Jensen Huang Says Manufacturing Bottlenecks Are a ‘2–3 Year Problem.’ Here’s What That Means for Investors',
   'description': '',
   'summary': '“Once you can build one, you can build 10. And once you can build 10, you can build a million.” That is how NVIDIA (NASDAQ:NVDA) CEO Jensen Huang frames the manufacturing bottleneck question that keeps some investors up at night. The logic is simple, and the implications for NVIDIA shareholders are worth unpacking carefully. What ... NVIDIA CEO Jensen Huang Says Manufacturing Bottlenecks Are a ‘2–3 Year Problem.’ Here’s What That Means for Investors',
   'pubDate': '2026-04-21T20:01:54Z',
   'displayTime': '2026-04-21T20:01:54Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/7e8b755be5e39c4d8225bffd07d9493a',
    'originalWidth': 1376,
    'originalHeight': 768,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Sxmmd3UIks0NlFa5gG.T.w--~B/aD03Njg7dz0xMzc2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/7e8b755be5e39c4d8225bffd07d9493a',
      'width': 1376,
      'height': 768,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/FtAps67nNTMWnhamSPc7ew--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/7e8b755be5e39c4d8225bffd07d9493a',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/04/21/nvidia-ceo-jensen-huang-says-manufacturing-bottlenecks-are-a-2-3-year-problem-heres-what-that-means-for-investors/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/nvidia-ceo-jensen-huang-says-200154452.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '8f19316c-c7cb-3c43-b71e-9992e2a556b1',
  'content': {'id': '8f19316c-c7cb-3c43-b71e-9992e2a556b1',
   'contentType': 'STORY',
   'title': 'Small Caps, Big Possibilities With This Cheap Schwab ETF',
   'description': '',
   'summary': 'With the Schwab International Small-Cap Equity ETF, investors need not fear international small caps. They can embrace this potent asset class.',
   'pubDate': '2026-04-21T19:50:00Z',
   'displayTime': '2026-04-21T19:50:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/f957d69741f73769da3fcd7448b2ae63',
    'originalWidth': 1400,
    'originalHeight': 933,
    'caption': 'A passport and a visa on a map.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/wXur7CWO9nR248KL16PGOg--~B/aD05MzM7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/f957d69741f73769da3fcd7448b2ae63',
      'width': 1400,
      'height': 933,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/vg6kO9qf7qFXogWApQwLcQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/f957d69741f73769da3fcd7448b2ae63',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/small-caps-big-possibilities-with-this-schwab-etf/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/small-caps-big-possibilities-cheap-195000953.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '40a69939-9508-338b-90cb-f7a10bfeed2c',
  'content': {'id': '40a69939-9508-338b-90cb-f7a10bfeed2c',
   'contentType': 'STORY',
   'title': "Is Netflix Stock a Buy on the Dip? Here's What History Says",
   'description': '',
   'summary': 'The smart money is betting on Netflix.',
   'pubDate': '2026-04-21T19:50:00Z',
   'displayTime': '2026-04-21T19:50:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/921f09bc9d77d22a164103d3c7620205',
    'originalWidth': 1200,
    'originalHeight': 800,
    'caption': 'Netflix logo.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Dk4TexYQcaE1pFrcwcYKCg--~B/aD04MDA7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/921f09bc9d77d22a164103d3c7620205',
      'width': 1200,
      'height': 800,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/aM7tTc9iJWsRYhen3tqeUA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/921f09bc9d77d22a164103d3c7620205',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/is-netflix-stock-a-buy-on-the-dip-heres-what-histo/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/netflix-stock-buy-dip-heres-195000892.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'c4c575d6-d619-338b-b1f7-b339f2aaa0f3',
  'content': {'id': 'c4c575d6-d619-338b-b1f7-b339f2aaa0f3',
   'contentType': 'STORY',
   'title': 'Prediction Market Giants Kalshi, Polymarket Eye Perpetual Futures Push: Report',
   'description': '',
   'summary': 'The leading prediction market firms are reportedly planning to push deeper into derivatives by supporting perpetual futures trading.',
   'pubDate': '2026-04-21T19:41:50Z',
   'displayTime': '2026-04-21T19:41:50Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/decrypt_157/2a3ade658456f6d8fbb945ea8b3ad365',
    'originalWidth': 1280,
    'originalHeight': 720,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ARtipaHNUcphC3x_QBtk0g--~B/aD03MjA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/decrypt_157/2a3ade658456f6d8fbb945ea8b3ad365',
      'width': 1280,
      'height': 720,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/41EqlhDwQLp2PTGTLjqI0w--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/decrypt_157/2a3ade658456f6d8fbb945ea8b3ad365',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'decrypt',
    'url': 'https://decrypt.co/',
    'sourceId': 'decrypt_157'},
   'canonicalUrl': {'url': 'https://decrypt.co/365070/prediction-market-giants-kalshi-polymarket-perpetual-futures',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/options/articles/prediction-market-giants-kalshi-polymarket-194150219.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'a54776a7-4dee-348a-ae76-fc7c55201e52',
  'content': {'id': 'a54776a7-4dee-348a-ae76-fc7c55201e52',
   'contentType': 'STORY',
   'title': 'American Airlines Has Denied Rumors of a Merger With United. Here Are 2 Others Factors Dragging Down the Stock Right Now.',
   'description': '',
   'summary': 'American Airlines issued a statement yesterday, refuting the idea of a potential merger with United Airlines.',
   'pubDate': '2026-04-21T19:34:10Z',
   'displayTime': '2026-04-21T19:34:10Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/b005c64531ceb018e5f7de07f69e561e',
    'originalWidth': 1400,
    'originalHeight': 787,
    'caption': 'Two people sitting across table from one another.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/alTszKW_ErRTvo.s4ewj7w--~B/aD03ODc7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/b005c64531ceb018e5f7de07f69e561e',
      'width': 1400,
      'height': 787,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/eLqXXlYPw29FFhLfJB4A6A--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/b005c64531ceb018e5f7de07f69e561e',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/american-airlines-has-denied-rumors-of-a-merger-wi/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/american-airlines-denied-rumors-merger-193410083.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '6baf6b65-382b-3677-8cc6-8dcb8c7220d5',
  'content': {'id': '6baf6b65-382b-3677-8cc6-8dcb8c7220d5',
   'contentType': 'STORY',
   'title': 'Why Constellation Energy Stock Is Falling Today',
   'description': '',
   'summary': 'With the company reporting no news, what could be motivating investors to click the sell button?',
   'pubDate': '2026-04-21T19:21:19Z',
   'displayTime': '2026-04-21T19:21:19Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/e5481e732becf0c3bde61e4938f3038d',
    'originalWidth': 1200,
    'originalHeight': 800,
    'caption': 'cooling towers of nuclear power plant at sunset.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/3aXY3ZvoyI73AY8zhPjmKQ--~B/aD04MDA7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/e5481e732becf0c3bde61e4938f3038d',
      'width': 1200,
      'height': 800,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/cHkF67tvlv_AivAiX05jvw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/e5481e732becf0c3bde61e4938f3038d',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/why-constellation-energy-stock-is-falling-today/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/why-constellation-energy-stock-falling-192119581.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '869f3ac4-5a0e-307b-825c-462e2ed935db',
  'content': {'id': '869f3ac4-5a0e-307b-825c-462e2ed935db',
   'contentType': 'STORY',
   'title': "If Tech Giants Keep on Making Their Own Chips, Is Nvidia's Stock Destined to Crash?",
   'description': '',
   'summary': "Nvidia's valuation depends heavily on investor expectations of future growth.",
   'pubDate': '2026-04-21T19:20:00Z',
   'displayTime': '2026-04-21T19:20:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/923b9229de975dbfba8353368d6a78c5',
    'originalWidth': 1400,
    'originalHeight': 787,
    'caption': 'Image of an artificial intelligence chip.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/jAXO8fvKVsKeZ7VHCVSLEQ--~B/aD03ODc7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/923b9229de975dbfba8353368d6a78c5',
      'width': 1400,
      'height': 787,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/uhwTW7uRbSPWcxTeoVZYcA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/923b9229de975dbfba8353368d6a78c5',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/if-tech-giants-keep-on-making-their-own-chips-is-n/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/tech-giants-keep-making-own-192000750.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '24d4ed43-e42a-3226-a198-f25e4f7b7a02',
  'content': {'id': '24d4ed43-e42a-3226-a198-f25e4f7b7a02',
   'contentType': 'STORY',
   'title': 'Want To Be A Millionaire? Buy Inflation‑Hedging PAX Gold',
   'description': '',
   'summary': 'This gold-tracking cryptocurrency is a great alternative to gold bars and gold ETFs.',
   'pubDate': '2026-04-21T19:06:28Z',
   'displayTime': '2026-04-21T19:06:28Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/9e24d48ce79467b37298275a9b0db3bc',
    'originalWidth': 1400,
    'originalHeight': 762,
    'caption': 'A magnifying glass on top of a chart tracking the price of gold.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/q07MxlfruRF5nGZqysg7.Q--~B/aD03NjI7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/9e24d48ce79467b37298275a9b0db3bc',
      'width': 1400,
      'height': 762,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/KRQpgflnJoMbOqqPS5UxPA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/9e24d48ce79467b37298275a9b0db3bc',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/want-to-be-a-millionaire-buy-inflationhedging-pax/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/crypto/articles/want-millionaire-buy-inflation-hedging-190628167.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}}]

In [15]:
headlines = []

for stock in stocks:
    news = yf.Ticker(stock).news
    for article in news:
        headlines.append({
            "ticker": stock,
            "title": article["content"]["title"],
            "date": article["content"]["pubDate"]
        })

In [16]:
# Show all content and metadata for single headline
yf.Ticker("NVDA").news[0]

{'id': '60b59ce6-a10a-4ded-922e-6fe6f99b1728',
 'content': {'id': '60b59ce6-a10a-4ded-922e-6fe6f99b1728',
  'contentType': 'STORY',
  'title': 'What to watch as Nvidia, AMD, and Broadcom report earnings',
  'description': '',
  'summary': 'Google, Meta, and Amazon are spending billions on AI infrastructure. Now, investors want to see the receipts.',
  'pubDate': '2026-04-21T13:16:36Z',
  'displayTime': '2026-04-21T13:16:36Z',
  'isHosted': True,
  'bypassModal': False,
  'previewUrl': None,
  'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/3CCfzNk9UjQk6OZTI3b5Zg--~B/aD0yMjIzO3c9MzA3ODthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
   'originalWidth': 3078,
   'originalHeight': 2223,
   'caption': '',
   'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/3CCfzNk9UjQk6OZTI3b5Zg--~B/aD0yMjIzO3c9MzA3ODthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
     'width': 3078,
     'height': 2223,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/KJIQVp4LonAqhUFpDXMi7g--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
     'width': 170,
     'height': 128,
     'tag': '170x128'}]},
  'provider': {'displayName': 'Yahoo Finance',
   'url': 'http://finance.yahoo.com/',
   'sourceId': 'yahoofinance.com'},
  'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/what-to-watch-as-nvidia-amd-and-broadcom-report-earnings-131636149.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/what-to-watch-as-nvidia-amd-and-broadcom-report-earnings-131636149.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'metadata': {'editorsPick': True},
  'finance': {'premiumFinance': {'isPremiumNews': False,
    'isPremiumFreeNews': False}},
  'storyline': None}}

In [17]:
headlines[0]

{'ticker': 'NVDA',
 'title': 'What to watch as Nvidia, AMD, and Broadcom report earnings',
 'date': '2026-04-21T13:16:36Z'}

In [18]:
len(headlines)

50

In [19]:
# Flatten data

headline_data = pd.DataFrame(headlines)

In [20]:
headline_data.head()

,ticker,title,date
0,NVDA,"What to watch as Nvidia, AMD, and Broadcom rep...",2026-04-21T13:16:36Z
1,NVDA,Want to Be a Millionaire? Buy Wall Street Test...,2026-04-21T20:04:08Z
2,NVDA,NVIDIA CEO Jensen Huang Says Manufacturing Bot...,2026-04-21T20:01:54Z
3,NVDA,"Small Caps, Big Possibilities With This Cheap ...",2026-04-21T19:50:00Z
4,NVDA,Is Netflix Stock a Buy on the Dip? Here's What...,2026-04-21T19:50:00Z

### PHASE 2 : Sentiment Scoring

In [21]:
from src.sentiment import analyze_sentiment

In [22]:
label_results = []
score_results = []

for title in headline_data["title"]:
    sentiment = analyze_sentiment(title)
    label_results.append(sentiment[0][0]["label"])
    score_results.append(sentiment[0][0]["score"])

In [23]:
headline_data["label"] = label_results
headline_data["score"] = score_results
headline_data

,ticker,title,date,label,score
0,NVDA,"What to watch as Nvidia, AMD, and Broadcom rep...",2026-04-21T13:16:36Z,neutral,0.999814
1,NVDA,Want to Be a Millionaire? Buy Wall Street Test...,2026-04-21T20:04:08Z,neutral,0.999874
2,NVDA,NVIDIA CEO Jensen Huang Says Manufacturing Bot...,2026-04-21T20:01:54Z,negative,0.969722
3,NVDA,"Small Caps, Big Possibilities With This Cheap ...",2026-04-21T19:50:00Z,neutral,0.998388
4,NVDA,Is Netflix Stock a Buy on the Dip? Here's What...,2026-04-21T19:50:00Z,positive,0.945987
5,NVDA,"Prediction Market Giants Kalshi, Polymarket Ey...",2026-04-21T19:41:50Z,positive,0.685272
6,NVDA,American Airlines Has Denied Rumors of a Merge...,2026-04-21T19:34:10Z,negative,0.987574
7,NVDA,Why Constellation Energy Stock Is Falling Today,2026-04-21T19:21:19Z,negative,0.996761
8,NVDA,"If Tech Giants Keep on Making Their Own Chips,...",2026-04-21T19:20:00Z,negative,0.976464
9,NVDA,Want To Be A Millionaire? Buy Inflation‑Hedgin...,2026-04-21T19:06:28Z,neutral,0.999843
10,META,"Meta to track employee keystrokes to train AI,...",2026-04-21T18:08:25Z,neutral,0.999873
11,META,Meta breaks ground on over $1 billion data cen...,2026-04-21T20:35:03Z,neutral,0.999869
12,META,"Google, Apple Lead Earnings Barrage. Get Ready.",2026-04-21T20:13:16Z,neutral,0.999526
13,META,What AI Bubble? Why JPMorgan Says AI Stocks Ha...,2026-04-21T19:13:07Z,positive,0.997595
14,META,Earnings Are Set to Surge 18% This Year. The B...,2026-04-21T18:19:00Z,positive,0.999571
15,META,Meta Secures Power From Noon Energy to Serve D...,2026-04-21T16:41:19Z,neutral,0.999865
16,META,The AI Spending Spree Is Far from Over,2026-04-21T16:10:00Z,neutral,0.999661
17,META,Meta Platforms Tests WhatsApp Premium Features,2026-04-21T15:22:41Z,neutral,0.999880
18,META,UBS Hikes Meta Platforms’ Target From $872 to ...,2026-04-21T14:55:39Z,positive,0.999337
19,META,Bitcoin To $250K? Billionaire Investor Tim Dra...,2026-04-21T14:46:03Z,negative,0.996766
20,MSFT,Everything to know about Apple's incoming CEO ...,2026-04-21T19:56:00Z,neutral,0.999861
21,MSFT,Apple vs. Microsoft: Which is better positione...,2026-04-21T14:37:36Z,neutral,0.989495
22,MSFT,"Google, Apple Lead Earnings Barrage. Get Ready.",2026-04-21T20:13:16Z,neutral,0.999526
23,MSFT,Microsoft must face $2.8 billion UK lawsuit ov...,2026-04-21T20:01:46Z,neutral,0.976704
24,MSFT,Sector Update: Tech Stocks Higher Late Afternoon,2026-04-21T19:56:27Z,positive,0.855470
25,MSFT,"Gates Foundation to Cut 20% of Staff, Review E...",2026-04-21T19:21:00Z,negative,0.684795
26,MSFT,What AI Bubble? Why JPMorgan Says AI Stocks Ha...,2026-04-21T19:13:07Z,positive,0.997595
27,MSFT,Microsoft Eyes Q3 Reset as AI Demand Builds,2026-04-21T18:21:57Z,negative,0.634086
28,MSFT,Earnings Are Set to Surge 18% This Year. The B...,2026-04-21T18:19:00Z,positive,0.999571
29,MSFT,"Microsoft cuts Game Pass Ultimate price, drops...",2026-04-21T17:48:01Z,negative,0.980031
30,AMD,"What to watch as Nvidia, AMD, and Broadcom rep...",2026-04-21T13:16:36Z,neutral,0.999814
31,AMD,Wells Fargo Says Tech Still Looks Compelling –...,2026-04-21T17:59:03Z,positive,0.998068
32,AMD,AMD Stock Hits Record Highs – Is It Too Late T...,2026-04-21T16:41:47Z,positive,0.995640
33,AMD,Should You Add Intel Stock to Your Portfolio A...,2026-04-21T15:54:00Z,neutral,0.999856
34,AMD,Seagate's Massive 616% Run in a Year: Time to ...,2026-04-21T13:45:00Z,positive,0.989101
35,AMD,Earnings Growth & Price Strength Make Advanced...,2026-04-21T13:30:03Z,positive,0.999251
36,AMD,"Nasdaq Composite Jumps on Earnings Momentum, A...",2026-04-21T13:08:10Z,positive,0.998560
37,AMD,Cerebras and Other Nvidia Rivals Just Made Key...,2026-04-21T10:30:00Z,neutral,0.684852
38,AMD,Is Super Micro (SMCI) One of the Top Hidden AI...,2026-04-21T10:19:00Z,neutral,0.999858
39,AMD,Assessing Celestica (TSX:CLS) Valuation After ...,2026-04-21T06:05:22Z,positive,0.999177
40,GOOGL,Everything to know about Apple's incoming CEO ...,2026-04-21T19:56:00Z,neutral,0.999861
41,GOOGL,Tech stocks today: Apple stock falls as Wall S...,2026-03-13T14:42:20Z,negative,0.991617
42,GOOGL,"Google, Apple Lead Earnings Barrage. Get Ready.",2026-04-21T20:13:16Z,neutral,0.999526
43,GOOGL,Microsoft must face $2.8 billion UK lawsuit ov...,2026-04-21T20:01:46Z,neutral,0.976704
44,GOOGL,The World's First Commercial Fusion Power Plan...,2026-04-21T19:18:24Z,neutral,0.999320
45,GOOGL,What AI Bubble? Why JPMorgan Says AI Stocks Ha...,2026-04-21T19:13:07Z,positive,0.997595
46,GOOGL,Heard on the Street | Apple’s New Boss Needs t...,2026-04-21T19:06:15Z,neutral,0.999666
47,GOOGL,Apple CEO Transition Follows $3.66 Trillion Va...,2026-04-21T18:58:54Z,positive,0.887436
48,GOOGL,Earnings Are Set to Surge 18% This Year. The B...,2026-04-21T18:19:00Z,positive,0.999571
49,GOOGL,Nvidia vs. Google. The AI Chips Battle Is Abou...,2026-04-21T17:36:00Z,neutral,0.999750

In [24]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322159  196.210220  259.299347  24.206568
2023-03-16  96.599998   99.497643  203.334305  269.810364  25.518410
2023-03-17  97.839996  100.787003  194.086899  272.965637  25.702246
2023-03-20  96.809998  100.390274  196.269791  265.932220  25.877089
2023-03-21  95.930000  104.059937  200.585892  267.446381  26.175829

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135437  196.239986  260.315296  24.264515  ...
2023-03-16  96.690002  100.360514  204.157844  270.162021  25.565367  ...
2023-03-17  98.750000  101.996996  200.327916  276.775408  26.375649  ...
2023-03-20  96.940002  100.915928  197.807725  271.060767  26.000979  ...
2023-03-21  99.459999  104.238461  201.965068  268.638158  26.368659  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455850  191.447592  253.965666  23.739980
2023-03-16  89.720001   95.411413  196.716243  259.074588  24.005749
2023-03-17  96.660004   99.438150  198.998353  271.822721  25.959018
2023-03-20  96.300003   99.299293  196.934572  270.572334  25.592341
2023-03-21  97.000000  100.420022  201.617787  268.520939  26.156847

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

### Phase 3 : Analyze data

In [25]:
# Reshape data

reshaped_data = df["Close"].stack().reset_index().rename(columns={0: "close", "Ticker": "ticker", "Date": "date"})
reshaped_data.head()

        date ticker       close
0 2023-03-15    AMD   89.680000
1 2023-03-15  GOOGL   95.322159
2 2023-03-15   META  196.210220
3 2023-03-15   MSFT  259.299347
4 2023-03-15   NVDA   24.206568

In [26]:
reshaped_data = reshaped_data.set_index("date")

In [27]:
# Group data by months

# reshaped_data.dtypes

reshaped_data.groupby(["ticker", pd.Grouper(freq="ME")])["close"].mean()

ticker  date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
                         ...
NVDA    2025-11-30    187.962520
        2025-12-31    182.324673
        2026-01-31    186.711894
        2026-02-28    185.701528
        2026-03-31    182.350104
Name: close, Length: 185, dtype: float64

In [28]:
# Explore monthly trends

monthly_close = reshaped_data.groupby(["ticker", pd.Grouper(freq="ME")])["close"].mean()
monthly_close.head()

ticker  date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
Name: close, dtype: float64

In [29]:
reshaped_data.groupby(["ticker", pd.Grouper(freq="QE")])["close"].mean()

ticker  date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
                         ...
NVDA    2025-03-31    126.703979
        2025-06-30    125.817829
        2025-09-30    174.281515
        2025-12-31    186.121489
        2026-03-31    185.429958
Name: close, Length: 65, dtype: float64

In [30]:
# Explore quarterly trends

quarterly_close = reshaped_data.groupby(["ticker", pd.Grouper(freq="QE")])["close"].mean()
quarterly_close.head()

ticker  date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
Name: close, dtype: float64

In [31]:
headline_data.groupby(["ticker", "label"])["label"].count()

ticker  label
AMD     neutral     4
        positive    6
GOOGL   negative    1
        neutral     6
        positive    3
META    negative    1
        neutral     6
        positive    3
MSFT    negative    3
        neutral     4
        positive    3
NVDA    negative    4
        neutral     4
        positive    2
Name: label, dtype: int64

In [32]:
sentiment_count = headline_data.groupby(["ticker", "label"])["label"].count()

In [33]:
headline_data.groupby(["ticker"])["score"].mean()

ticker
AMD      0.966418
GOOGL    0.985105
META     0.999194
MSFT     0.911713
NVDA     0.955970
Name: score, dtype: float64

In [34]:
score_avg = headline_data.groupby(["ticker"])["score"].mean()

In [35]:
first_close = quarterly_close.groupby("ticker").first()
last_close = quarterly_close.groupby("ticker").last()

In [36]:
((last_close - first_close) / first_close) * 100

ticker
AMD      123.770470
GOOGL    214.705783
META     224.733373
MSFT      57.974532
NVDA     603.180113
Name: close, dtype: float64

In [37]:
stock_roc = ((last_close - first_close) / first_close) * 100

In [38]:
# All my analysis variables

# sentiment_count — label counts per ticker
# score_avg — average confidence score per ticker
# quarterly_close — price trend over 12 quarterly_close
# stock_roc — overall % price change over 3 years

In [39]:
headline_data[headline_data["score"] < 0.80]

,ticker,title,date,label,score
5,NVDA,"Prediction Market Giants Kalshi, Polymarket Ey...",2026-04-21T19:41:50Z,positive,0.685272
25,MSFT,"Gates Foundation to Cut 20% of Staff, Review E...",2026-04-21T19:21:00Z,negative,0.684795
27,MSFT,Microsoft Eyes Q3 Reset as AI Demand Builds,2026-04-21T18:21:57Z,negative,0.634086
37,AMD,Cerebras and Other Nvidia Rivals Just Made Key...,2026-04-21T10:30:00Z,neutral,0.684852

In [40]:
low_confidence = headline_data[headline_data["score"] < 0.80]

### Phase 4 : Visualize data

In [41]:
quarterly_df = quarterly_close.reset_index()

In [42]:
px.line(
    data_frame=quarterly_df, 
    x="date", 
    y="close", 
    color="ticker", 
    title="Q1 '23—Q2 '26 Quarterly Stock Prices"
    )

In [43]:
sentiment_df = sentiment_count.reset_index(name="count")

In [44]:
# Stacked bar chart
# px.bar(data_frame=sentiment_df, x="ticker", y="count", color="label", title="Recent News Headlines Sentiment")

In [45]:
px.bar(
    data_frame=sentiment_df,
    x="ticker", 
    y="count", 
    color="label", 
    barmode="group",
    title="Recent News Headlines Sentiment", 
    color_discrete_map = {
        "positive": "#48a860", 
        "neutral": "#bebdb8", 
        "negative": "#cd5c5c"
        }
    )

In [46]:
price_chart = px.line(
    data_frame=quarterly_df, 
    x="date", 
    y="close", 
    color="ticker", 
    title="Q1 '23—Q2 '26 Quarterly Stock Prices"
    )

sentiment_chart = px.bar(
    data_frame=sentiment_df,
    x="ticker", 
    y="count", 
    color="label", 
    barmode="group",
    title="Recent News Headlines Sentiment", 
    color_discrete_map = {
        "positive": "#48a860", 
        "neutral": "#bebdb8", 
        "negative": "#cd5c5c"
        }
    )

In [47]:
price_chart.write_html("outputs/price_chart.html")
sentiment_chart.write_html("outputs/sentiment_chart.html")

In [ ]:
# Creates empty subplot container

fig = make_subplots(rows=2, cols=1)

In [62]:
for trace in price_chart.data:
    fig.add_trace(trace, row=1, col=1)

for trace in sentiment_chart.data:
    fig.add_trace(trace, row=2, col=1)

In [63]:
fig.update_layout(
    title_text="AI Stock Performance & Current Sentiment Analysis"
)

In [64]:
fig.write_html("outputs/stock_dashboard.html")