### PHASE 1 : Collecting data

In [81]:
# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np

In [82]:
# List to capture AI stocks—AI infrastructure and AI-powered companies.
stocks = ["NVDA", "META", "MSFT", "AMD", "GOOGL"]

In [83]:
# df is Dataframe—function which passes in stocks and date range for df.
df = yf.download(tickers=stocks, start="2023-03-15", end="2026-03-15")

[*********************100%***********************]  5 of 5 completed

In [84]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322166  196.210266  259.299316  24.206568
2023-03-16  96.599998   99.497658  203.334335  269.810364  25.518412
2023-03-17  97.839996  100.786995  194.086899  272.965607  25.702244
2023-03-20  96.809998  100.390274  196.269760  265.932220  25.877090
2023-03-21  95.930000  104.059937  200.585922  267.446381  26.175827

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135444  196.240031  260.315265  24.264515  ...
2023-03-16  96.690002  100.360529  204.157874  270.162021  25.565369  ...
2023-03-17  98.750000  101.996988  200.327916  276.775377  26.375647  ...
2023-03-20  96.940002  100.915928  197.807694  271.060767  26.000981  ...
2023-03-21  99.459999  104.238461  201.965099  268.638158  26.368657  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455857  191.447637  253.965636  23.739980
2023-03-16  89.720001   95.411427  196.716272  259.074588  24.005751
2023-03-17  96.660004   99.438143  198.998353  271.822690  25.959016
2023-03-20  96.300003   99.299293  196.934541  270.572334  25.592343
2023-03-21  97.000000  100.420022  201.617818  268.520939  26.156845

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [85]:
df.columns

MultiIndex([( 'Close',   'AMD'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'META'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'NVDA'),
            (  'High',   'AMD'),
            (  'High', 'GOOGL'),
            (  'High',  'META'),
            (  'High',  'MSFT'),
            (  'High',  'NVDA'),
            (   'Low',   'AMD'),
            (   'Low', 'GOOGL'),
            (   'Low',  'META'),
            (   'Low',  'MSFT'),
            (   'Low',  'NVDA'),
            (  'Open',   'AMD'),
            (  'Open', 'GOOGL'),
            (  'Open',  'META'),
            (  'Open',  'MSFT'),
            (  'Open',  'NVDA'),
            ('Volume',   'AMD'),
            ('Volume', 'GOOGL'),
            ('Volume',  'META'),
            ('Volume',  'MSFT'),
            ('Volume',  'NVDA')],
           names=['Price', 'Ticker'])

In [86]:
df.shape

(752, 25)

In [87]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 752 entries, 2023-03-15 to 2026-03-13
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, AMD)     752 non-null    float64
 1   (Close, GOOGL)   752 non-null    float64
 2   (Close, META)    752 non-null    float64
 3   (Close, MSFT)    752 non-null    float64
 4   (Close, NVDA)    752 non-null    float64
 5   (High, AMD)      752 non-null    float64
 6   (High, GOOGL)    752 non-null    float64
 7   (High, META)     752 non-null    float64
 8   (High, MSFT)     752 non-null    float64
 9   (High, NVDA)     752 non-null    float64
 10  (Low, AMD)       752 non-null    float64
 11  (Low, GOOGL)     752 non-null    float64
 12  (Low, META)      752 non-null    float64
 13  (Low, MSFT)      752 non-null    float64
 14  (Low, NVDA)      752 non-null    float64
 15  (Open, AMD)      752 non-null    float64
 16  (Open, GOOGL)    752 non-null    float64
 17  (Open, META)     752 non-null    float64
 18  (Open, MSFT)     752 non-null    float64
 19  (Open, NVDA)     752 non-null    float64
 20  (Volume, AMD)    752 non-null    int64
 21  (Volume, GOOGL)  752 non-null    int64
 22  (Volume, META)   752 non-null    int64
 23  (Volume, MSFT)   752 non-null    int64
 24  (Volume, NVDA)   752 non-null    int64
dtypes: float64(20), int64(5)
memory usage: 152.8 KB

In [88]:
df.describe()

Price        Close                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.828324  178.303726  510.032441  406.722717  110.174772
std      41.766704   59.267770  163.535077   64.594057   53.493754
min      78.209999   95.322166  194.086899  259.299316   24.206568
25%     112.002502  136.263767  335.286362  365.005554   48.840426
50%     141.760002  164.499825  524.088928  409.369659  116.998013
75%     169.445004  190.765568  645.484070  447.321587  146.969254
max     264.329987  343.448242  788.148987  539.825256  207.017273

Price         High                                                  ...  \
Ticker         AMD       GOOGL        META        MSFT        NVDA  ...
count   752.000000  752.000000  752.000000  752.000000  752.000000  ...
mean    149.719827  180.249596  516.432462  410.145541  111.981672  ...
std      42.878968   60.022627  165.473902   64.914354   54.248785  ...
min      85.480003   96.135444  196.240031  260.315265   24.264515  ...
25%     114.395002  137.528329  337.253398  368.108833   49.556457  ...
50%     144.289993  165.989432  532.311038  412.460421  119.131434  ...
75%     172.049995  192.186474  652.566306  450.570315  148.926135  ...
max     267.079987  348.754481  794.384398  552.242002  212.166717  ...

Price         Open                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.924468  178.153442  510.100256  406.707279  110.223178
std      41.941908   59.299622  164.119506   64.850847   53.622100
min      79.220001   92.455857  191.447637  253.965636   23.739980
25%     112.052500  136.271228  335.187120  364.869635   49.125134
50%     142.730003  164.479676  524.796369  410.068683  117.272922
75%     169.307503  190.554028  642.907274  446.764593  147.766460
max     264.190002  347.095646  789.296390  552.023241  208.057150

Price         Volume
Ticker           AMD         GOOGL          META          MSFT          NVDA
count   7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02
mean    5.305591e+07  3.181655e+07  1.695474e+07  2.381806e+07  3.364204e+08
std     2.434066e+07  1.357632e+07  9.409263e+06  1.046421e+07  1.752086e+08
min     7.956800e+06  1.009740e+07  4.726100e+06  5.855900e+06  6.552850e+07
25%     3.606890e+07  2.321348e+07  1.131440e+07  1.726135e+07  1.955628e+08
50%     4.822515e+07  2.849140e+07  1.495705e+07  2.121225e+07  3.052285e+08
75%     6.357465e+07  3.573692e+07  1.942280e+07  2.670622e+07  4.300298e+08
max     2.488596e+08  1.274901e+08  8.844010e+07  1.288553e+08  1.543911e+09

[8 rows x 25 columns]

In [89]:
df.tail()

Price            Close                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  202.679993  306.359985  646.836182  409.410004  182.640106
2026-03-10  203.229996  307.040009  653.510498  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.299805  404.880005  186.029999
2026-03-12  197.740005  303.549988  637.634094  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.184998  395.549988  180.250000

Price             High                                                  ...  \
Ticker             AMD       GOOGL        META        MSFT        NVDA  ...
Date                                                                    ...
2026-03-09  202.970001  306.799988  647.195859  410.209991  182.900102  ...
2026-03-10  206.589996  309.510010  659.735149  410.200012  186.429918  ...
2026-03-11  209.210007  311.420013  658.556170  409.010010  187.619995  ...
2026-03-12  203.619995  308.940002  652.940997  406.119995  184.940002  ...
2026-03-13  199.679993  307.690002  628.631733  404.799988  186.089996  ...

Price             Open                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  189.360001  294.359985  634.236984  404.920013  176.820429
2026-03-10  202.509995  306.170013  653.000925  410.029999  182.390128
2026-03-11  205.110001  306.750000  654.199915  405.570007  185.910004
2026-03-12  202.830002  306.820007  648.195060  404.630005  184.050003
2026-03-13  198.110001  307.010010  623.356281  401.000000  184.919998

Price         Volume
Ticker           AMD     GOOGL      META      MSFT       NVDA
Date
2026-03-09  38877200  29312100  13489700  30131900  177213600
2026-03-10  29139200  23239700   9859300  31706400  179118500
2026-03-11  23076400  24125700   8977200  25512100  145280400
2026-03-12  28886900  24928300  11617500  27263900  155762700
2026-03-13  27561900  23693100  18957600  26848000  160988400

[5 rows x 25 columns]

In [90]:
df["Low"]

Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2023-03-15   86.220001   91.880610  189.354066  253.213430   23.339336
2023-03-16   89.019997   94.717169  194.563170  257.189244   23.872867
2023-03-17   95.940002   99.279451  193.908292  269.927568   25.645293
2023-03-20   92.900002   99.051342  192.132231  263.607275   25.107771
2023-03-21   93.639999  100.390270  196.408696  263.284922   25.358552
...                ...         ...         ...         ...         ...
2026-03-09  189.020004  294.079987  626.243828  403.500000  175.550494
2026-03-10  202.199997  305.570007  648.444828  402.929993  182.000149
2026-03-11  203.630005  305.920013  647.805365  401.589996  184.449997
2026-03-12  196.669998  301.029999  636.355221  401.709991  181.750000
2026-03-13  192.270004  300.440002  609.028522  394.250000  179.940002

[752 rows x 5 columns]

In [91]:
df["Low"]["NVDA"]

Date
2023-03-15     23.339336
2023-03-16     23.872867
2023-03-17     25.645293
2023-03-20     25.107771
2023-03-21     25.358552
                 ...
2026-03-09    175.550494
2026-03-10    182.000149
2026-03-11    184.449997
2026-03-12    181.750000
2026-03-13    179.940002
Name: NVDA, Length: 752, dtype: float64

In [92]:
(df == 0).any().sum()

np.int64(0)

In [93]:
df["Close"]
close_prices = df["Close"]

In [94]:
yf.Ticker("NVDA").news

[{'id': '60b59ce6-a10a-4ded-922e-6fe6f99b1728',
  'content': {'id': '60b59ce6-a10a-4ded-922e-6fe6f99b1728',
   'contentType': 'STORY',
   'title': 'What to watch as Nvidia, AMD, and Broadcom report earnings',
   'description': '',
   'summary': 'Google, Meta, and Amazon are spending billions on AI infrastructure. Now, investors want to see the receipts.',
   'pubDate': '2026-04-21T13:16:36Z',
   'displayTime': '2026-04-21T13:16:36Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/3CCfzNk9UjQk6OZTI3b5Zg--~B/aD0yMjIzO3c9MzA3ODthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
    'originalWidth': 3078,
    'originalHeight': 2223,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/3CCfzNk9UjQk6OZTI3b5Zg--~B/aD0yMjIzO3c9MzA3ODthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
      'width': 3078,
      'height': 2223,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/KJIQVp4LonAqhUFpDXMi7g--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/what-to-watch-as-nvidia-amd-and-broadcom-report-earnings-131636149.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/what-to-watch-as-nvidia-amd-and-broadcom-report-earnings-131636149.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'b1ea9761-7125-3b77-986a-ef57976876b1',
  'content': {'id': 'b1ea9761-7125-3b77-986a-ef57976876b1',
   'contentType': 'STORY',
   'title': 'The Space Race Is Heating Up. Here Are 3 Stocks Worth Watching Right Now.',
   'description': '',
   'summary': "SpaceX isn't the only space company worth watching. It's just the most expensive.",
   'pubDate': '2026-04-21T17:02:00Z',
   'displayTime': '2026-04-21T17:02:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/a9277ba510b708660a83278edcd98c2b',
    'originalWidth': 1400,
    'originalHeight': 739,
    'caption': 'Astronaut in a space suit in space over Earth.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/7.Jqv0wQ0xnurWkI7hw0WA--~B/aD03Mzk7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/a9277ba510b708660a83278edcd98c2b',
      'width': 1400,
      'height': 739,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/RIXIxfBI2MDcmnXhoWgg8Q--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/a9277ba510b708660a83278edcd98c2b',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/space-race-heating-up-3-stocks-worth-owning/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/space-race-heating-3-stocks-170200041.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '954177c2-869b-328d-8fab-0a464217b7d4',
  'content': {'id': '954177c2-869b-328d-8fab-0a464217b7d4',
   'contentType': 'STORY',
   'title': 'AMD Stock Hits Record Highs – Is It Too Late To Buy?',
   'description': '',
   'summary': 'While AMD (AMD) recently breached record highs in April 2026, many investors viewing the stock’s 100x trailing multiple conclude the valuation is unsustainable. (See AMD valuation metrics.',
   'pubDate': '2026-04-21T16:41:47Z',
   'displayTime': '2026-04-21T16:41:47Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/trefis_142/21472cc541eddccb9d7006b756f72e45',
    'originalWidth': 1920,
    'originalHeight': 1280,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/RuzvG8kA5o_InMSxxcxA.w--~B/aD0xMjgwO3c9MTkyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/trefis_142/21472cc541eddccb9d7006b756f72e45',
      'width': 1920,
      'height': 1280,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/DaD8hw3m5TeWX0ceTp87og--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/trefis_142/21472cc541eddccb9d7006b756f72e45',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Trefis',
    'url': 'https://www.trefis.com/',
    'sourceId': 'trefis_142'},
   'canonicalUrl': {'url': 'https://www.trefis.com/articles/597042/amd-stock-hits-record-highs-is-it-too-late-to-buy/2026-04-21?source=yahoo&from=AMD-2026-04-21',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/amd-stock-hits-record-highs-164147850.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'd3bce214-4824-35dd-86ff-6906aada174b',
  'content': {'id': 'd3bce214-4824-35dd-86ff-6906aada174b',
   'contentType': 'STORY',
   'title': 'Why Tractor Supply Stock Crashed Today',
   'description': '',
   'summary': 'Tractor Supply stock may shift into higher gear later in the year -- but it still costs too much.',
   'pubDate': '2026-04-21T16:40:29Z',
   'displayTime': '2026-04-21T16:40:29Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/2968e3004455ce453ea68694fe273757',
    'originalWidth': 1400,
    'originalHeight': 934,
    'caption': 'Farmer on a tractor in a field.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Z6_lPdhYtxbuMOpi4F0JNQ--~B/aD05MzQ7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/2968e3004455ce453ea68694fe273757',
      'width': 1400,
      'height': 934,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/XgkgkE1HNSr9XWYa4y4d8g--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/2968e3004455ce453ea68694fe273757',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/why-tractor-supply-stock-crashed-today/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/why-tractor-supply-stock-crashed-164029188.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '34387ed0-5fb5-3695-b97b-c96356f049ba',
  'content': {'id': '34387ed0-5fb5-3695-b97b-c96356f049ba',
   'contentType': 'STORY',
   'title': 'UnitedHealth Group Surprises Wall Street. Is It Time to Load Up on the Beaten-Down Buffett Stock?',
   'description': '',
   'summary': 'A year after shocking the market by missing on earnings, UnitedHealth Group manages to delight.',
   'pubDate': '2026-04-21T16:23:31Z',
   'displayTime': '2026-04-21T16:23:31Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/766728ea0c04376049a4f83dfcd48994',
    'originalWidth': 1400,
    'originalHeight': 865,
    'caption': 'Stamps that read "Medicare" and "Medicaid"',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/9.6dZen1Me4yDaHA8VqlOA--~B/aD04NjU7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/766728ea0c04376049a4f83dfcd48994',
      'width': 1400,
      'height': 865,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/vMXeaX_P.lrzwlGlXchNZA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/766728ea0c04376049a4f83dfcd48994',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/unitedhealth-group-surprises-wall-street-is-it-tim/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/healthcare/articles/unitedhealth-group-surprises-wall-street-162331272.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '7cc550ab-1ae4-3e32-bf7d-d812b7d3c307',
  'content': {'id': '7cc550ab-1ae4-3e32-bf7d-d812b7d3c307',
   'contentType': 'STORY',
   'title': 'Apple vs. Microsoft: What\'s the Better "Magnificent Seven" Stock to Buy in 2026?',
   'description': '',
   'summary': 'These stocks have both been strong, market-beating investments over the past decade, but their growth strategies differ.',
   'pubDate': '2026-04-21T16:20:00Z',
   'displayTime': '2026-04-21T16:20:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/377655fef7b50cc3a6c9f69a44a19903',
    'originalWidth': 1200,
    'originalHeight': 801,
    'caption': 'Person using a computer which utilizes artificial intelligence.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/n80rs2_E6zAN98l6TzkiDw--~B/aD04MDE7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/377655fef7b50cc3a6c9f69a44a19903',
      'width': 1200,
      'height': 801,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/UnlxSs_WeAsgsyqyd6yQmQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/377655fef7b50cc3a6c9f69a44a19903',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/apple-vs-microsoft-whats-the-better-magnificient-s/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/apple-vs-microsoft-whats-better-162000421.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '72feb235-b24d-3256-98de-3bf832cf0e9e',
  'content': {'id': '72feb235-b24d-3256-98de-3bf832cf0e9e',
   'contentType': 'STORY',
   'title': 'Nvidia Stock-Split: 2 Years and $1.5 Trillion Later, Can It Reach $1,200 Again?',
   'description': '',
   'summary': "If the stock price rose to $1,200 again, Nvidia's market cap would be a whopping $28 trillion.",
   'pubDate': '2026-04-21T16:10:00Z',
   'displayTime': '2026-04-21T16:10:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/8ae8b4deed95a70ece16ef728507ef09',
    'originalWidth': 1200,
    'originalHeight': 800,
    'caption': 'A trader looks at charts.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/lYjo6fJK9aXGb8fe0vHfkQ--~B/aD04MDA7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/8ae8b4deed95a70ece16ef728507ef09',
      'width': 1200,
      'height': 800,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/k40GIwmMZ1p7HbWazncQ3g--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/8ae8b4deed95a70ece16ef728507ef09',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/nvidia-stock-1200-price-target-timeline/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/nvidia-stock-split-2-years-161000451.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '83b8feef-14de-3fbe-b36b-e488284f130e',
  'content': {'id': '83b8feef-14de-3fbe-b36b-e488284f130e',
   'contentType': 'STORY',
   'title': 'Why Palo Alto Networks Stock Popped Today',
   'description': '',
   'summary': 'AI will not eat this software stock.',
   'pubDate': '2026-04-21T16:09:19Z',
   'displayTime': '2026-04-21T16:09:19Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/ad006a787487777a882f01300e78d77d',
    'originalWidth': 1400,
    'originalHeight': 933,
    'caption': 'Gold question mark over a rising green stock market arrow laid out on graph paper.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/D8FCzJEUqAJoTKol.PM2Yg--~B/aD05MzM7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/ad006a787487777a882f01300e78d77d',
      'width': 1400,
      'height': 933,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/n1dlsreGWS51vpxYq27a2g--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/ad006a787487777a882f01300e78d77d',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/why-palo-alto-networks-stock-popped-today/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/why-palo-alto-networks-stock-160919723.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '4cf2af46-e52d-347f-a35f-7761197fb350',
  'content': {'id': '4cf2af46-e52d-347f-a35f-7761197fb350',
   'contentType': 'STORY',
   'title': 'Forget (XRP) Ripple: This Cryptocurrency Has A Real Moat',
   'description': '',
   'summary': 'Ethereum offers more stable returns with clearer long-term catalysts.',
   'pubDate': '2026-04-21T16:04:43Z',
   'displayTime': '2026-04-21T16:04:43Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/946e6743ea11b38cfadf363bea3b45ef',
    'originalWidth': 1400,
    'originalHeight': 933,
    'caption': 'A digital illustration of virtual Ether tokens.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/PMPLUTiM.7dDN53zgnihGw--~B/aD05MzM7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/946e6743ea11b38cfadf363bea3b45ef',
      'width': 1400,
      'height': 933,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/q5BgJNAt070Xxa4LUUFWew--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/946e6743ea11b38cfadf363bea3b45ef',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/21/forget-xrp-ripple-this-cryptocurrency-has-a-real-m/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/crypto/articles/forget-xrp-ripple-cryptocurrency-real-160443351.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'fa8e7ebe-a1d1-3dea-95eb-eda9e5f02c5a',
  'content': {'id': 'fa8e7ebe-a1d1-3dea-95eb-eda9e5f02c5a',
   'contentType': 'STORY',
   'title': 'Intel results to show if supply chain issues are dimming its AI ambitions',
   'description': '',
   'summary': "Intel investors on Thursday will focus on its efforts to sort out \u200csupply chain issues that have limited the company's \u200cability to ramp up chip production to meet rising demand from businesses \u200badopting AI-related services.  Intel has warned that supply constraints for its server chips that are used alongside graphics processors made by companies such as Nvidia will be most acute in \u200cthe first quarter before \u2060easing in the second.  • Intel is expected to report a 1.9% decline in first-quarter revenue \u2060to $12.42 billion and a near 90% drop in adjusted earnings per share, according to data compiled by LSEG.",
   'pubDate': '2026-04-21T16:01:55Z',
   'displayTime': '2026-04-21T16:01:55Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/reuters-finance.com/12feead8e7775d74b114d919571c2756',
    'originalWidth': 800,
    'originalHeight': 533,
    'caption': 'FILE PHOTO: Illustration shows Intel logo',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/TXYUnufG.wVVR00wM9dc8Q--~B/aD01MzM7dz04MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/reuters-finance.com/12feead8e7775d74b114d919571c2756',
      'width': 800,
      'height': 533,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/2gXANDbxZ8j_UujO0ZDHPg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/reuters-finance.com/12feead8e7775d74b114d919571c2756',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Reuters',
    'url': 'http://www.reuters.com/',
    'sourceId': 'reuters-finance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/intel-results-show-supply-chain-160155896.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/intel-results-show-supply-chain-160155896.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}}]

In [95]:
headlines = []

for stock in stocks:
    news = yf.Ticker(stock).news
    for article in news:
        headlines.append({
            "ticker": stock,
            "title": article["content"]["title"],
            "date": article["content"]["pubDate"]
        })

In [96]:
# Show all content and metadata for single headline
yf.Ticker("NVDA").news[0]

{'id': '60b59ce6-a10a-4ded-922e-6fe6f99b1728',
 'content': {'id': '60b59ce6-a10a-4ded-922e-6fe6f99b1728',
  'contentType': 'STORY',
  'title': 'What to watch as Nvidia, AMD, and Broadcom report earnings',
  'description': '',
  'summary': 'Google, Meta, and Amazon are spending billions on AI infrastructure. Now, investors want to see the receipts.',
  'pubDate': '2026-04-21T13:16:36Z',
  'displayTime': '2026-04-21T13:16:36Z',
  'isHosted': True,
  'bypassModal': False,
  'previewUrl': None,
  'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/3CCfzNk9UjQk6OZTI3b5Zg--~B/aD0yMjIzO3c9MzA3ODthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
   'originalWidth': 3078,
   'originalHeight': 2223,
   'caption': '',
   'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/3CCfzNk9UjQk6OZTI3b5Zg--~B/aD0yMjIzO3c9MzA3ODthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
     'width': 3078,
     'height': 2223,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/KJIQVp4LonAqhUFpDXMi7g--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-04/52c3a9d3-c1b0-4932-a197-9bd623d3d341',
     'width': 170,
     'height': 128,
     'tag': '170x128'}]},
  'provider': {'displayName': 'Yahoo Finance',
   'url': 'http://finance.yahoo.com/',
   'sourceId': 'yahoofinance.com'},
  'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/what-to-watch-as-nvidia-amd-and-broadcom-report-earnings-131636149.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/what-to-watch-as-nvidia-amd-and-broadcom-report-earnings-131636149.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'metadata': {'editorsPick': True},
  'finance': {'premiumFinance': {'isPremiumNews': False,
    'isPremiumFreeNews': False}},
  'storyline': None}}

In [97]:
headlines[0]

{'ticker': 'NVDA',
 'title': 'What to watch as Nvidia, AMD, and Broadcom report earnings',
 'date': '2026-04-21T13:16:36Z'}

In [98]:
len(headlines)

50

In [99]:
# Flatten data

headline_data = pd.DataFrame(headlines)

In [100]:
headline_data.head()

,ticker,title,date
0,NVDA,"What to watch as Nvidia, AMD, and Broadcom rep...",2026-04-21T13:16:36Z
1,NVDA,The Space Race Is Heating Up. Here Are 3 Stock...,2026-04-21T17:02:00Z
2,NVDA,AMD Stock Hits Record Highs – Is It Too Late T...,2026-04-21T16:41:47Z
3,NVDA,Why Tractor Supply Stock Crashed Today,2026-04-21T16:40:29Z
4,NVDA,UnitedHealth Group Surprises Wall Street. Is I...,2026-04-21T16:23:31Z

### PHASE 2 : Sentiment Scoring

In [101]:
from src.sentiment import analyze_sentiment

In [102]:
label_results = []
score_results = []

for title in headline_data["title"]:
    sentiment = analyze_sentiment(title)
    label_results.append(sentiment[0][0]["label"])
    score_results.append(sentiment[0][0]["score"])

In [103]:
headline_data["label"] = label_results
headline_data["score"] = score_results
headline_data

,ticker,title,date,label,score
0,NVDA,"What to watch as Nvidia, AMD, and Broadcom rep...",2026-04-21T13:16:36Z,neutral,0.999814
1,NVDA,The Space Race Is Heating Up. Here Are 3 Stock...,2026-04-21T17:02:00Z,neutral,0.999842
2,NVDA,AMD Stock Hits Record Highs – Is It Too Late T...,2026-04-21T16:41:47Z,positive,0.995640
3,NVDA,Why Tractor Supply Stock Crashed Today,2026-04-21T16:40:29Z,negative,0.992066
4,NVDA,UnitedHealth Group Surprises Wall Street. Is I...,2026-04-21T16:23:31Z,neutral,0.989130
5,NVDA,"Apple vs. Microsoft: What's the Better ""Magnif...",2026-04-21T16:20:00Z,neutral,0.999272
6,NVDA,Nvidia Stock-Split: 2 Years and $1.5 Trillion ...,2026-04-21T16:10:00Z,neutral,0.935394
7,NVDA,Why Palo Alto Networks Stock Popped Today,2026-04-21T16:09:19Z,positive,0.954411
8,NVDA,Forget (XRP) Ripple: This Cryptocurrency Has A...,2026-04-21T16:04:43Z,neutral,0.999664
9,NVDA,Intel results to show if supply chain issues a...,2026-04-21T16:01:55Z,negative,0.998181
10,META,"What to watch as Nvidia, AMD, and Broadcom rep...",2026-04-21T13:16:36Z,neutral,0.999814
11,META,Meta Secures Power From Noon Energy to Serve D...,2026-04-21T16:41:19Z,neutral,0.999865
12,META,The AI Spending Spree is Far from Over,2026-04-21T16:10:00Z,neutral,0.999094
13,META,Meta Platforms Tests WhatsApp Premium Features,2026-04-21T15:22:41Z,neutral,0.999880
14,META,UBS Hikes Meta Platforms’ Target From $872 to ...,2026-04-21T14:55:39Z,positive,0.999337
15,META,Bitcoin To $250K? Billionaire Investor Tim Dra...,2026-04-21T14:46:03Z,negative,0.996766
16,META,Qualcomm’s Best Run in Years Barely Puts a Den...,2026-04-21T14:45:01Z,positive,0.665380
17,META,What AI Bubble? Why JPMorgan Says AI Stocks Ha...,2026-04-21T14:37:55Z,positive,0.997595
18,META,Meta Is Spending $48 Billion With CoreWeave an...,2026-04-21T14:28:00Z,positive,0.927876
19,META,"Caterpillar Stock Can Gain 20%, Analyst Says. ...",2026-04-21T14:08:00Z,positive,0.999651
20,MSFT,"Microsoft cuts Xbox subscription prices, bucki...",2026-04-21T16:00:00Z,positive,0.999324
21,MSFT,Apple vs. Microsoft: Which is better positione...,2026-04-21T14:37:36Z,neutral,0.989495
22,MSFT,US Equity Indexes Slip as Investors Await Fate...,2026-04-21T17:00:03Z,negative,0.997667
23,MSFT,Microsoft must face $2.8 billion UK lawsuit ov...,2026-04-21T16:49:17Z,neutral,0.976704
24,MSFT,AMD Stock Hits Record Highs – Is It Too Late T...,2026-04-21T16:41:47Z,positive,0.995640
25,MSFT,"Apple vs. Microsoft: What's the Better ""Magnif...",2026-04-21T16:20:00Z,neutral,0.999272
26,MSFT,The AI Spending Spree is Far from Over,2026-04-21T16:10:00Z,neutral,0.999094
27,MSFT,Microsoft vs. Alibaba: Which Cloud Titan Is th...,2026-04-21T15:23:00Z,neutral,0.995745
28,MSFT,Microsoft's Dynamics 365 Adoption Deepens: Is ...,2026-04-21T15:06:00Z,positive,0.999421
29,MSFT,What AI Bubble? Why JPMorgan Says AI Stocks Ha...,2026-04-21T14:37:55Z,positive,0.997595
30,AMD,"What to watch as Nvidia, AMD, and Broadcom rep...",2026-04-21T13:16:36Z,neutral,0.999814
31,AMD,AMD Stock Hits Record Highs – Is It Too Late T...,2026-04-21T16:41:47Z,positive,0.995640
32,AMD,Should You Add Intel Stock to Your Portfolio A...,2026-04-21T15:54:00Z,neutral,0.999856
33,AMD,Seagate's Massive 616% Run in a Year: Time to ...,2026-04-21T13:45:00Z,positive,0.989101
34,AMD,Earnings Growth & Price Strength Make Advanced...,2026-04-21T13:30:03Z,positive,0.999251
35,AMD,"Nasdaq Composite Jumps on Earnings Momentum, A...",2026-04-21T13:08:10Z,positive,0.998560
36,AMD,Cerebras and Other Nvidia Rivals Just Made Key...,2026-04-21T10:30:00Z,neutral,0.684852
37,AMD,Is Super Micro (SMCI) One of the Top Hidden AI...,2026-04-21T10:19:00Z,neutral,0.999858
38,AMD,Assessing Celestica (TSX:CLS) Valuation After ...,2026-04-21T06:05:22Z,positive,0.999177
39,AMD,Celestica Inc. (CLS): One of the Best AI Data ...,2026-04-20T21:00:07Z,neutral,0.998926
40,GOOGL,New Apple CEO John Ternus faces 7 big challeng...,2026-04-20T23:37:30Z,negative,0.731528
41,GOOGL,"What to watch as Nvidia, AMD, and Broadcom rep...",2026-04-21T13:16:36Z,neutral,0.999814
42,GOOGL,Alphabet’s SpaceX Stake Puts Fresh Focus On No...,2026-04-21T17:07:06Z,neutral,0.847953
43,GOOGL,Microsoft must face $2.8 billion UK lawsuit ov...,2026-04-21T16:49:17Z,neutral,0.976704
44,GOOGL,Morningstar to lease big chunk of Loop’s Thomp...,2026-04-21T16:42:08Z,neutral,0.998226
45,GOOGL,Amazon To Invest Up To $25 Billion In AI Start...,2026-04-21T16:39:24Z,positive,0.999017
46,GOOGL,Is Amazon Stock Overvalued?,2026-04-21T16:32:02Z,negative,0.987610
47,GOOGL,Google’s Quantum AI Just Spooked Ripple Into B...,2026-04-21T16:27:59Z,negative,0.992735
48,GOOGL,The AI Spending Spree is Far from Over,2026-04-21T16:10:00Z,neutral,0.999094
49,GOOGL,Intel results to show if supply chain issues a...,2026-04-21T16:01:55Z,negative,0.998181

In [104]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322166  196.210266  259.299316  24.206568
2023-03-16  96.599998   99.497658  203.334335  269.810364  25.518412
2023-03-17  97.839996  100.786995  194.086899  272.965607  25.702244
2023-03-20  96.809998  100.390274  196.269760  265.932220  25.877090
2023-03-21  95.930000  104.059937  200.585922  267.446381  26.175827

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135444  196.240031  260.315265  24.264515  ...
2023-03-16  96.690002  100.360529  204.157874  270.162021  25.565369  ...
2023-03-17  98.750000  101.996988  200.327916  276.775377  26.375647  ...
2023-03-20  96.940002  100.915928  197.807694  271.060767  26.000981  ...
2023-03-21  99.459999  104.238461  201.965099  268.638158  26.368657  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455857  191.447637  253.965636  23.739980
2023-03-16  89.720001   95.411427  196.716272  259.074588  24.005751
2023-03-17  96.660004   99.438143  198.998353  271.822690  25.959016
2023-03-20  96.300003   99.299293  196.934541  270.572334  25.592343
2023-03-21  97.000000  100.420022  201.617818  268.520939  26.156845

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

### Phase 3 : Analyze data

In [105]:
# Reshape data

reshaped_data = df["Close"].stack().reset_index().rename(columns={0: "close", "Ticker": "ticker", "Date": "date"})
reshaped_data.head()

        date ticker       close
0 2023-03-15    AMD   89.680000
1 2023-03-15  GOOGL   95.322166
2 2023-03-15   META  196.210266
3 2023-03-15   MSFT  259.299316
4 2023-03-15   NVDA   24.206568

In [106]:
reshaped_data = reshaped_data.set_index("date")

In [107]:
# Group data by months

# reshaped_data.dtypes

reshaped_data.groupby(["ticker", pd.Grouper(freq="ME")])["close"].mean()

ticker  date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
                         ...
NVDA    2025-11-30    187.962520
        2025-12-31    182.324673
        2026-01-31    186.711894
        2026-02-28    185.701528
        2026-03-31    182.350104
Name: close, Length: 185, dtype: float64

In [108]:
# Explore monthly trends

monthly_close = reshaped_data.groupby(["ticker", pd.Grouper(freq="ME")])["close"].mean()
monthly_close.head()

ticker  date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
Name: close, dtype: float64

In [109]:
reshaped_data.groupby(["ticker", pd.Grouper(freq="QE")])["close"].mean()

ticker  date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
                         ...
NVDA    2025-03-31    126.703980
        2025-06-30    125.817829
        2025-09-30    174.281514
        2025-12-31    186.121490
        2026-03-31    185.429958
Name: close, Length: 65, dtype: float64

In [110]:
# Explore quarterly trends

quarterly_close = reshaped_data.groupby(["ticker", pd.Grouper(freq="QE")])["close"].mean()
quarterly_close.head()

ticker  date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
Name: close, dtype: float64

In [111]:
headline_data.groupby(["ticker", "label"])["label"].count()

ticker  label
AMD     neutral     5
        positive    5
GOOGL   negative    4
        neutral     5
        positive    1
META    negative    1
        neutral     4
        positive    5
MSFT    negative    1
        neutral     5
        positive    4
NVDA    negative    2
        neutral     6
        positive    2
Name: label, dtype: int64

In [112]:
sentiment_count = headline_data.groupby(["ticker", "label"])["label"].count()

In [113]:
headline_data.groupby(["ticker"])["score"].mean()

ticker
AMD      0.966503
GOOGL    0.953086
META     0.958526
MSFT     0.994996
NVDA     0.986341
Name: score, dtype: float64

In [114]:
score_avg = headline_data.groupby(["ticker"])["score"].mean()

In [ ]:
first_close = quarterly_close.groupby("ticker").first()
last_close = quarterly_close.groupby("ticker").last()

In [ ]:
((last_close - first_close) / first_close) * 100

ticker
AMD      123.770470
GOOGL    214.705780
META     224.733363
MSFT      57.974540
NVDA     603.180117
Name: close, dtype: float64

In [ ]:
stock_roc = ((last_close - first_close) / first_close) * 100

In [ ]:
# All my analysis variables

# sentiment_count — label counts per ticker
# score_avg — average confidence score per ticker
# quarterly_close — price trend over 12 quarterly_close
# stock_roc — overall % price change over 3 years

In [119]:
headline_data[headline_data["score"] < 0.80]

,ticker,title,date,label,score
16,META,Qualcomm’s Best Run in Years Barely Puts a Den...,2026-04-21T14:45:01Z,positive,0.665380
36,AMD,Cerebras and Other Nvidia Rivals Just Made Key...,2026-04-21T10:30:00Z,neutral,0.684852
40,GOOGL,New Apple CEO John Ternus faces 7 big challeng...,2026-04-20T23:37:30Z,negative,0.731528

In [ ]:
low_confidence = headline_data[headline_Data["score"] < 0.80]

### Phase 4 : Visualize data
Note: GOOGL has 2-3 low confidence scores, MSFT has 1.