### PHASE 1 : Collecting data

In [2]:
# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np
import sqlite3
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [3]:
conn = sqlite3.connect("headline_db.sqlite")
cursor = conn.cursor()

In [4]:
cursor.execute(
    "CREATE TABLE IF NOT EXISTS prices(ticker TEXT, date TEXT, close REAL)"
)

In [5]:
cursor.execute(
    "CREATE TABLE IF NOT EXISTS headlines(ticker TEXT, date TEXT, title TEXT, label TEXT, score REAL)"
)

In [6]:
conn.commit()

In [7]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
cursor.fetchall()

[('prices',), ('headlines',)]

In [8]:
# List to capture AI stocks—AI infrastructure and AI-powered companies.
stocks = ["NVDA", "META", "MSFT", "AMD", "GOOGL"]

In [9]:
# df is Dataframe—function which passes in stocks and date range for df.
df = yf.download(tickers=stocks, start="2023-03-15", end="2026-03-15")

[*********************100%***********************]  5 of 5 completed

In [10]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322166  196.210236  259.299286  24.206573
2023-03-16  96.599998   99.497643  203.334351  269.810394  25.518408
2023-03-17  97.839996  100.787003  194.086899  272.965698  25.702244
2023-03-20  96.809998  100.390282  196.269760  265.932251  25.877090
2023-03-21  95.930000  104.059944  200.585922  267.446289  26.175829

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135444  196.240001  260.315235  24.264521  ...
2023-03-16  96.690002  100.360514  204.157890  270.162052  25.565365  ...
2023-03-17  98.750000  101.996996  200.327916  276.775470  26.375647  ...
2023-03-20  96.940002  100.915936  197.807694  271.060798  26.000981  ...
2023-03-21  99.459999  104.238469  201.965099  268.638066  26.368659  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455857  191.447607  253.965606  23.739986
2023-03-16  89.720001   95.411413  196.716287  259.074617  24.005747
2023-03-17  96.660004   99.438150  198.998353  271.822782  25.959016
2023-03-20  96.300003   99.299300  196.934541  270.572365  25.592343
2023-03-21  97.000000  100.420030  201.617818  268.520847  26.156847

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [11]:
df.columns

MultiIndex([( 'Close',   'AMD'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'META'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'NVDA'),
            (  'High',   'AMD'),
            (  'High', 'GOOGL'),
            (  'High',  'META'),
            (  'High',  'MSFT'),
            (  'High',  'NVDA'),
            (   'Low',   'AMD'),
            (   'Low', 'GOOGL'),
            (   'Low',  'META'),
            (   'Low',  'MSFT'),
            (   'Low',  'NVDA'),
            (  'Open',   'AMD'),
            (  'Open', 'GOOGL'),
            (  'Open',  'META'),
            (  'Open',  'MSFT'),
            (  'Open',  'NVDA'),
            ('Volume',   'AMD'),
            ('Volume', 'GOOGL'),
            ('Volume',  'META'),
            ('Volume',  'MSFT'),
            ('Volume',  'NVDA')],
           names=['Price', 'Ticker'])

In [12]:
df.shape

(752, 25)

In [13]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 752 entries, 2023-03-15 to 2026-03-13
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, AMD)     752 non-null    float64
 1   (Close, GOOGL)   752 non-null    float64
 2   (Close, META)    752 non-null    float64
 3   (Close, MSFT)    752 non-null    float64
 4   (Close, NVDA)    752 non-null    float64
 5   (High, AMD)      752 non-null    float64
 6   (High, GOOGL)    752 non-null    float64
 7   (High, META)     752 non-null    float64
 8   (High, MSFT)     752 non-null    float64
 9   (High, NVDA)     752 non-null    float64
 10  (Low, AMD)       752 non-null    float64
 11  (Low, GOOGL)     752 non-null    float64
 12  (Low, META)      752 non-null    float64
 13  (Low, MSFT)      752 non-null    float64
 14  (Low, NVDA)      752 non-null    float64
 15  (Open, AMD)      752 non-null    float64
 16  (Open, GOOGL)    752 non-null    float64
 17  (Open, META)     752 non-null    float64
 18  (Open, MSFT)     752 non-null    float64
 19  (Open, NVDA)     752 non-null    float64
 20  (Volume, AMD)    752 non-null    int64
 21  (Volume, GOOGL)  752 non-null    int64
 22  (Volume, META)   752 non-null    int64
 23  (Volume, MSFT)   752 non-null    int64
 24  (Volume, NVDA)   752 non-null    int64
dtypes: float64(20), int64(5)
memory usage: 152.8 KB

In [14]:
df.describe()

Price        Close                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.828324  178.303726  510.032443  406.722718  110.174772
std      41.766704   59.267770  163.535076   64.594055   53.493754
min      78.209999   95.322166  194.086899  259.299286   24.206573
25%     112.002502  136.263771  335.286362  365.005562   48.840423
50%     141.760002  164.499840  524.088867  409.369659  116.998009
75%     169.445004  190.765556  645.484024  447.321579  146.969250
max     264.329987  343.448242  788.148987  539.825195  207.017273

Price         High                                                  ...  \
Ticker         AMD       GOOGL        META        MSFT        NVDA  ...
count   752.000000  752.000000  752.000000  752.000000  752.000000  ...
mean    149.719827  180.249596  516.432464  410.145542  111.981672  ...
std      42.878968   60.022627  165.473902   64.914352   54.248785  ...
min      85.480003   96.135444  196.240001  260.315235   24.264521  ...
25%     114.395002  137.528325  337.253422  368.108863   49.556454  ...
50%     144.289993  165.989432  532.311006  412.460406  119.131434  ...
75%     172.049995  192.186498  652.566306  450.570331  148.926147  ...
max     267.079987  348.754481  794.384398  552.242002  212.166717  ...

Price         Open                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.924468  178.153442  510.100257  406.707281  110.223178
std      41.941908   59.299621  164.119505   64.850846   53.622100
min      79.220001   92.455857  191.447607  253.965606   23.739986
25%     112.052500  136.271213  335.187120  364.869620   49.125130
50%     142.730003  164.479676  524.796307  410.068714  117.272925
75%     169.307503  190.554035  642.907274  446.764570  147.766464
max     264.190002  347.095646  789.296390  552.023241  208.057150

Price         Volume
Ticker           AMD         GOOGL          META          MSFT          NVDA
count   7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02
mean    5.305591e+07  3.181655e+07  1.695474e+07  2.381806e+07  3.364204e+08
std     2.434066e+07  1.357632e+07  9.409263e+06  1.046421e+07  1.752086e+08
min     7.956800e+06  1.009740e+07  4.726100e+06  5.855900e+06  6.552850e+07
25%     3.606890e+07  2.321348e+07  1.131440e+07  1.726135e+07  1.955628e+08
50%     4.822515e+07  2.849140e+07  1.495705e+07  2.121225e+07  3.052285e+08
75%     6.357465e+07  3.573692e+07  1.942280e+07  2.670622e+07  4.300298e+08
max     2.488596e+08  1.274901e+08  8.844010e+07  1.288553e+08  1.543911e+09

[8 rows x 25 columns]

In [15]:
df.tail()

Price            Close                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  202.679993  306.359985  646.836182  409.410004  182.640106
2026-03-10  203.229996  307.040009  653.510498  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.299805  404.880005  186.029999
2026-03-12  197.740005  303.549988  637.634094  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.184998  395.549988  180.250000

Price             High                                                  ...  \
Ticker             AMD       GOOGL        META        MSFT        NVDA  ...
Date                                                                    ...
2026-03-09  202.970001  306.799988  647.195859  410.209991  182.900102  ...
2026-03-10  206.589996  309.510010  659.735149  410.200012  186.429918  ...
2026-03-11  209.210007  311.420013  658.556170  409.010010  187.619995  ...
2026-03-12  203.619995  308.940002  652.940997  406.119995  184.940002  ...
2026-03-13  199.679993  307.690002  628.631733  404.799988  186.089996  ...

Price             Open                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  189.360001  294.359985  634.236984  404.920013  176.820429
2026-03-10  202.509995  306.170013  653.000925  410.029999  182.390128
2026-03-11  205.110001  306.750000  654.199915  405.570007  185.910004
2026-03-12  202.830002  306.820007  648.195060  404.630005  184.050003
2026-03-13  198.110001  307.010010  623.356281  401.000000  184.919998

Price         Volume
Ticker           AMD     GOOGL      META      MSFT       NVDA
Date
2026-03-09  38877200  29312100  13489700  30131900  177213600
2026-03-10  29139200  23239700   9859300  31706400  179118500
2026-03-11  23076400  24125700   8977200  25512100  145280400
2026-03-12  28886900  24928300  11617500  27263900  155762700
2026-03-13  27561900  23693100  18957600  26848000  160988400

[5 rows x 25 columns]

In [16]:
df["Low"]

Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2023-03-15   86.220001   91.880610  189.354036  253.213401   23.339341
2023-03-16   89.019997   94.717154  194.563185  257.189273   23.872863
2023-03-17   95.940002   99.279458  193.908292  269.927659   25.645293
2023-03-20   92.900002   99.051349  192.132231  263.607305   25.107771
2023-03-21   93.639999  100.390277  196.408696  263.284832   25.358553
...                ...         ...         ...         ...         ...
2026-03-09  189.020004  294.079987  626.243828  403.500000  175.550494
2026-03-10  202.199997  305.570007  648.444828  402.929993  182.000149
2026-03-11  203.630005  305.920013  647.805365  401.589996  184.449997
2026-03-12  196.669998  301.029999  636.355221  401.709991  181.750000
2026-03-13  192.270004  300.440002  609.028522  394.250000  179.940002

[752 rows x 5 columns]

In [17]:
df["Low"]["NVDA"]

Date
2023-03-15     23.339341
2023-03-16     23.872863
2023-03-17     25.645293
2023-03-20     25.107771
2023-03-21     25.358553
                 ...
2026-03-09    175.550494
2026-03-10    182.000149
2026-03-11    184.449997
2026-03-12    181.750000
2026-03-13    179.940002
Name: NVDA, Length: 752, dtype: float64

In [18]:
(df == 0).any().sum()

np.int64(0)

In [19]:
df["Close"]
close_prices = df["Close"]

In [20]:
yf.Ticker("NVDA").news

[{'id': '16708602-ff63-496b-84b7-6d6bbc9bcf45',
  'content': {'id': '16708602-ff63-496b-84b7-6d6bbc9bcf45',
   'contentType': 'STORY',
   'title': 'Nvidia CEO Jensen Huang says company now has zero market share in China',
   'description': '',
   'summary': "Nvidia CEO Jensen Huang says the company's market share in China has fallen to zero.",
   'pubDate': '2026-05-04T15:08:05Z',
   'displayTime': '2026-05-04T15:08:05Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2024-12/6f05a5f0-bc88-11ef-b2d4-0a5d1a1a4abe',
    'originalWidth': 5500,
    'originalHeight': 3667,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/JWolZpsuJt_uj1rpKuG3lQ--~B/aD0zNjY3O3c9NTUwMDthcHBpZD15dGFjaHlvbg--/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2024-12/6f05a5f0-bc88-11ef-b2d4-0a5d1a1a4abe',
      'width': 5500,
      'height': 3667,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/YhBiXaha2znCsc3LAWTKxQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2024-12/6f05a5f0-bc88-11ef-b2d4-0a5d1a1a4abe',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/nvidia-ceo-jensen-huang-says-company-now-has-zero-market-share-in-china-150805330.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/nvidia-ceo-jensen-huang-says-company-now-has-zero-market-share-in-china-150805330.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'b984da7d-b68c-32cf-a17d-639a927e346a',
  'content': {'id': 'b984da7d-b68c-32cf-a17d-639a927e346a',
   'contentType': 'STORY',
   'title': 'Big Tech pulled into growing AI capacity concerns',
   'description': '',
   'summary': 'Capacity concerns push government to widen partners',
   'pubDate': '2026-05-04T16:58:32Z',
   'displayTime': '2026-05-04T16:58:32Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': None,
   'provider': {'displayName': 'GuruFocus.com',
    'url': 'http://www.gurufocus.com/',
    'sourceId': 'us.finance.gurufocus'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/big-tech-pulled-growing-ai-165832927.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/big-tech-pulled-growing-ai-165832927.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '251d8a83-d1c1-3578-8fff-66b1c2ab24e3',
  'content': {'id': '251d8a83-d1c1-3578-8fff-66b1c2ab24e3',
   'contentType': 'STORY',
   'title': 'AI Chipmaker Cerebras Targets Raising Up To $4 billion in IPO',
   'description': '',
   'summary': 'Cerebras Systems plans to kick off the roadshow for its proposed initial public offering as the arti',
   'pubDate': '2026-05-04T16:50:27Z',
   'displayTime': '2026-05-04T16:50:27Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/mt_newswires_premium_news_706/7ebae9f5890c0b80e379bf0d0ceacb0f',
    'originalWidth': 1024,
    'originalHeight': 681,
    'caption': 'Cerebras CBRS.jpg - Shutterstock',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/jN8uHwp5_rJvOZSO6.7O2g--~B/aD02ODE7dz0xMDI0O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/mt_newswires_premium_news_706/7ebae9f5890c0b80e379bf0d0ceacb0f',
      'width': 1024,
      'height': 681,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/hf3YU33FjWySUddryZaIWg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/mt_newswires_premium_news_706/7ebae9f5890c0b80e379bf0d0ceacb0f',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'MT Newswires',
    'url': 'https://www.mtnewswires.com/',
    'sourceId': 'mt_newswires_premium_news_706'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/ai-chipmaker-cerebras-targets-raising-165027661.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/ai-chipmaker-cerebras-targets-raising-165027661.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': True,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'cb58f466-8671-3a13-9890-9c60a5ccdaa2',
  'content': {'id': 'cb58f466-8671-3a13-9890-9c60a5ccdaa2',
   'contentType': 'STORY',
   'title': 'SIVR Beats SLV. Here Is Why.',
   'description': '',
   'summary': 'This smaller silver ETF is a better long-term investment than the market leader.',
   'pubDate': '2026-05-04T16:50:00Z',
   'displayTime': '2026-05-04T16:50:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/3ced1a9561b6389a3be9f5bb40bb72b0',
    'originalWidth': 1400,
    'originalHeight': 787,
    'caption': 'Stacks of silver bars.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Cmue182DNjVeURwkzZyT0g--~B/aD03ODc7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/3ced1a9561b6389a3be9f5bb40bb72b0',
      'width': 1400,
      'height': 787,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/P4mc_iDApJjNU9p8HUrTqQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/3ced1a9561b6389a3be9f5bb40bb72b0',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/05/04/sivr-beats-slv-here-is-why/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/commodities/articles/sivr-beats-slv-why-165000784.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '8c62d9a2-b7d6-308f-88af-02b51899b0e2',
  'content': {'id': '8c62d9a2-b7d6-308f-88af-02b51899b0e2',
   'contentType': 'STORY',
   'title': 'Cerebras Systems seeks up to $26.6B valuation in US IPO',
   'description': '',
   'summary': 'Cerebras Systems is targeting a valuation of as much as $26.62 billion in its planned U.S. initial public offering, according to its prospectus filings. The semiconductor company, which is positioning itself as a rival to Nvidia in AI hardware, is looking to sell 28 million shares of its...',
   'pubDate': '2026-05-04T16:49:00Z',
   'displayTime': '2026-05-04T16:49:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/proactive_us_504/e11780f026fc6b0f9d69762e0a80a459',
    'originalWidth': 1243,
    'originalHeight': 720,
    'caption': 'Cerebras Systems seeks up to $26.6B valuation in US IPO',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/XNIz.Pi0XAB5ibYTcdR06A--~B/aD03MjA7dz0xMjQzO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/proactive_us_504/e11780f026fc6b0f9d69762e0a80a459',
      'width': 1243,
      'height': 720,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/FqpKXM5nH.0jVqiA9x1q1A--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/proactive_us_504/e11780f026fc6b0f9d69762e0a80a459',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Proactive',
    'url': 'https://www.proactiveinvestors.com/',
    'sourceId': 'proactive_us_504'},
   'canonicalUrl': {'url': 'https://www.proactiveinvestors.com/companies/news/1091666/cerebras-systems-seeks-up-to-26-6b-valuation-in-us-ipo-1091666.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/cerebras-systems-seeks-26-6b-164900124.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'cc998c88-986c-36a3-ba60-fe44dc580fa0',
  'content': {'id': 'cc998c88-986c-36a3-ba60-fe44dc580fa0',
   'contentType': 'STORY',
   'title': 'Did Anthropic Suck the Air From Palantir’s Commercial Contract Tailwinds?',
   'description': '',
   'summary': 'Palantir Technologies (NASDAQ: PLTR) reports Q1 2026 results after the close today. Management guided at least 115% U.S. commercial growth for the year just as Anthropic’s enterprise AI push reshaped software buying. I’ll be watching whether commercial momentum held. Commercial Acceleration Meets a New Competitor Last quarter Palantir delivered $1.41B in revenue, up 70% YoY, ... Did Anthropic Suck the Air From Palantir’s Commercial Contract Tailwinds?',
   'pubDate': '2026-05-04T16:45:21Z',
   'displayTime': '2026-05-04T16:45:21Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/a4ebaed4bb164c53ecf9eb14bd9f7f1a',
    'originalWidth': 1152,
    'originalHeight': 864,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ZYapsWJvKb5EOU1jPjEhow--~B/aD04NjQ7dz0xMTUyO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/a4ebaed4bb164c53ecf9eb14bd9f7f1a',
      'width': 1152,
      'height': 864,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/NtRprkONyMxojB4FZuGzTw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/a4ebaed4bb164c53ecf9eb14bd9f7f1a',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/05/04/did-anthropic-suck-the-air-from-palantirs-commercial-contract-tailwinds/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/did-anthropic-suck-air-palantir-164521868.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '3128fa92-e0b7-3b5d-a8af-d5f40d8eb409',
  'content': {'id': '3128fa92-e0b7-3b5d-a8af-d5f40d8eb409',
   'contentType': 'STORY',
   'title': 'AMD Sinks 6% Despite a Holding Pattern in Intel and NVIDIA: The Selective AI Chip Trade Is Here',
   'description': '',
   'summary': 'Shares of Advanced Micro Devices (NASDAQ:AMD) are sinking 6% in midday trading Monday, changing hands near $340 after closing Friday at $360.54. The selloff stands out because AMD’s peers are barely moving. Intel (NASDAQ:INTC) stock is down 2% and NVIDIA (NASDAQ:NVDA) stock is off just 1%. After months of correlated moves higher, the artificial intelligence ... AMD Sinks 6% Despite a Holding Pattern in Intel and NVIDIA: The Selective AI Chip Trade Is Here',
   'pubDate': '2026-05-04T16:27:42Z',
   'displayTime': '2026-05-04T16:27:42Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': None,
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/05/04/amd-sinks-6-despite-a-holding-pattern-in-intel-and-nvidia-the-selective-ai-chip-trade-is-here/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/amd-sinks-6-despite-holding-162742575.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '52c6b4aa-5457-3ea6-884b-c266bce6ca09',
  'content': {'id': '52c6b4aa-5457-3ea6-884b-c266bce6ca09',
   'contentType': 'STORY',
   'title': 'Wall Street Sees 21% Upside for Rivian Despite R2 Pricing Disappointment',
   'description': '',
   'summary': 'Rivian (NASDAQ:RIVN) currently trades around $15, while Wall Street’s average price target sits at $18.16. That means analysts see roughly 21% upside for the stock today. Rivian designs and builds premium electric trucks, SUVs, and commercial vans, and is now betting its future on the R2 platform, a next-generation, lower-cost SUV designed for the mass market. ... Wall Street Sees 21% Upside for Rivian Despite R2 Pricing Disappointment',
   'pubDate': '2026-05-04T16:23:07Z',
   'displayTime': '2026-05-04T16:23:07Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/b429e396c160b72ccb28817b4352afac',
    'originalWidth': 2070,
    'originalHeight': 2070,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/H_xIR9kb7gNeX5Q6sYMh0w--~B/aD0yMDcwO3c9MjA3MDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/24_7_wall_st__718/b429e396c160b72ccb28817b4352afac',
      'width': 2070,
      'height': 2070,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/YVp0HBpWWxBuCXaVj8gehw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/b429e396c160b72ccb28817b4352afac',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/05/04/wall-street-sees-21-upside-for-rivian-despite-r2-pricing-disappointment/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/wall-street-sees-21-upside-162307468.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '7d52c571-59d5-3a91-b048-c323ef29c400',
  'content': {'id': '7d52c571-59d5-3a91-b048-c323ef29c400',
   'contentType': 'STORY',
   'title': 'Jim Cramer Just Won’t Give Up on NVIDIA (NVDA)',
   'description': '',
   'summary': 'We recently published Jim Cramer Commented On Big Market Confusion & Discussed These 20 Stocks. NVIDIA Corporation (NASDAQ:NVDA) is one of the stocks discussed by Jim Cramer. NVIDIA Corporation (NASDAQ:NVDA) is one of Jim Cramer’s favorite stocks. Throughout 2025 and 2026, the CNBC TV host has defended the firm during periods of weak share price […]',
   'pubDate': '2026-05-04T16:20:58Z',
   'displayTime': '2026-05-04T16:20:58Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/insidermonkey.com/a31e549fe7490e734036c908eaa59b12',
    'originalWidth': 768,
    'originalHeight': 512,
    'caption': "Jim Cramer Just Won't Give Up on NVIDIA (NVDA)",
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/yAzN3PNcUcSEYZEzWuF15w--~B/aD01MTI7dz03Njg7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/insidermonkey.com/a31e549fe7490e734036c908eaa59b12',
      'width': 768,
      'height': 512,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/o7Omq2B8vXQiFgSErlFQrQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/insidermonkey.com/a31e549fe7490e734036c908eaa59b12',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Insider Monkey',
    'url': 'http://www.insidermonkey.com',
    'sourceId': 'insidermonkey.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/jim-cramer-just-won-t-162058779.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/jim-cramer-just-won-t-162058779.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'db42ad1a-fec9-38b1-8650-df8c50b8db5b',
  'content': {'id': 'db42ad1a-fec9-38b1-8650-df8c50b8db5b',
   'contentType': 'STORY',
   'title': "Intel's Stock Hits a New All-Time High: Is It Still a Buy?",
   'description': '',
   'summary': 'Shares of the tech giant are up around 170% this year.',
   'pubDate': '2026-05-04T16:20:00Z',
   'displayTime': '2026-05-04T16:20:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/120615b6a737079117b90f7a9f87271b',
    'originalWidth': 1400,
    'originalHeight': 787,
    'caption': 'Team of traders working in an office.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ljEGKUYalnUTtsZIm_EKEQ--~B/aD03ODc7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/120615b6a737079117b90f7a9f87271b',
      'width': 1400,
      'height': 787,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/QBZB6Jobz.uzdnw1ylwL1w--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/120615b6a737079117b90f7a9f87271b',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/05/04/intels-stock-hits-a-new-all-time-high-is-it-still/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/intels-stock-hits-time-high-162000103.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}}]

In [21]:
headlines = []

for stock in stocks:
    news = yf.Ticker(stock).news
    for article in news:
        headlines.append({
            "ticker": stock,
            "title": article["content"]["title"],
            "date": article["content"]["pubDate"]
        })

In [22]:
# Show all content and metadata for single headline
yf.Ticker("NVDA").news[0]

{'id': '16708602-ff63-496b-84b7-6d6bbc9bcf45',
 'content': {'id': '16708602-ff63-496b-84b7-6d6bbc9bcf45',
  'contentType': 'STORY',
  'title': 'Nvidia CEO Jensen Huang says company now has zero market share in China',
  'description': '',
  'summary': "Nvidia CEO Jensen Huang says the company's market share in China has fallen to zero.",
  'pubDate': '2026-05-04T15:08:05Z',
  'displayTime': '2026-05-04T15:08:05Z',
  'isHosted': True,
  'bypassModal': False,
  'previewUrl': None,
  'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2024-12/6f05a5f0-bc88-11ef-b2d4-0a5d1a1a4abe',
   'originalWidth': 5500,
   'originalHeight': 3667,
   'caption': '',
   'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/JWolZpsuJt_uj1rpKuG3lQ--~B/aD0zNjY3O3c9NTUwMDthcHBpZD15dGFjaHlvbg--/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2024-12/6f05a5f0-bc88-11ef-b2d4-0a5d1a1a4abe',
     'width': 5500,
     'height': 3667,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/YhBiXaha2znCsc3LAWTKxQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2024-12/6f05a5f0-bc88-11ef-b2d4-0a5d1a1a4abe',
     'width': 170,
     'height': 128,
     'tag': '170x128'}]},
  'provider': {'displayName': 'Yahoo Finance',
   'url': 'http://finance.yahoo.com/',
   'sourceId': 'yahoofinance.com'},
  'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/nvidia-ceo-jensen-huang-says-company-now-has-zero-market-share-in-china-150805330.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/article/nvidia-ceo-jensen-huang-says-company-now-has-zero-market-share-in-china-150805330.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'metadata': {'editorsPick': True},
  'finance': {'premiumFinance': {'isPremiumNews': False,
    'isPremiumFreeNews': False}},
  'storyline': None}}

In [23]:
headlines[0]

{'ticker': 'NVDA',
 'title': 'Nvidia CEO Jensen Huang says company now has zero market share in China',
 'date': '2026-05-04T15:08:05Z'}

In [24]:
len(headlines)

50

In [25]:
# Flatten data

headline_data = pd.DataFrame(headlines)

In [26]:
headline_data.head()

,ticker,title,date
0,NVDA,Nvidia CEO Jensen Huang says company now has z...,2026-05-04T15:08:05Z
1,NVDA,Big Tech pulled into growing AI capacity concerns,2026-05-04T16:58:32Z
2,NVDA,AI Chipmaker Cerebras Targets Raising Up To $4...,2026-05-04T16:50:27Z
3,NVDA,SIVR Beats SLV. Here Is Why.,2026-05-04T16:50:00Z
4,NVDA,Cerebras Systems seeks up to $26.6B valuation ...,2026-05-04T16:49:00Z

### PHASE 2 : Sentiment Scoring

In [27]:
from src.sentiment import analyze_sentiment

In [28]:
label_results = []
score_results = []

for title in headline_data["title"]:
    sentiment = analyze_sentiment(title)
    label_results.append(sentiment[0][0]["label"])
    score_results.append(sentiment[0][0]["score"])

In [29]:
headline_data["label"] = label_results
headline_data["score"] = score_results
headline_data

,ticker,title,date,label,score
0,NVDA,Nvidia CEO Jensen Huang says company now has z...,2026-05-04T15:08:05Z,neutral,0.755732
1,NVDA,Big Tech pulled into growing AI capacity concerns,2026-05-04T16:58:32Z,negative,0.987875
2,NVDA,AI Chipmaker Cerebras Targets Raising Up To $4...,2026-05-04T16:50:27Z,positive,0.999280
3,NVDA,SIVR Beats SLV. Here Is Why.,2026-05-04T16:50:00Z,neutral,0.999886
4,NVDA,Cerebras Systems seeks up to $26.6B valuation ...,2026-05-04T16:49:00Z,positive,0.998417
5,NVDA,Did Anthropic Suck the Air From Palantir’s Com...,2026-05-04T16:45:21Z,negative,0.546641
6,NVDA,AMD Sinks 6% Despite a Holding Pattern in Inte...,2026-05-04T16:27:42Z,negative,0.997712
7,NVDA,Wall Street Sees 21% Upside for Rivian Despite...,2026-05-04T16:23:07Z,positive,0.998614
8,NVDA,Jim Cramer Just Won’t Give Up on NVIDIA (NVDA),2026-05-04T16:20:58Z,neutral,0.996618
9,NVDA,Intel's Stock Hits a New All-Time High: Is It ...,2026-05-04T16:20:00Z,positive,0.999339
10,META,Tech stocks today: Semiconductor company earni...,2026-05-04T10:00:00Z,neutral,0.983314
11,META,3 AI Stocks to Buy to Shelter Your Wealth From...,2026-05-04T16:43:00Z,neutral,0.999611
12,META,Labour’s ‘sovereign’ AI fund backs American co...,2026-05-04T16:37:08Z,neutral,0.999796
13,META,Meta Faces New Mexico Trial That Could Force P...,2026-05-04T16:34:31Z,neutral,0.998632
14,META,Jim Cramer Makes Big Change of Mind for Meta (...,2026-05-04T16:18:18Z,neutral,0.999776
15,META,New Mexico seeks changes to Meta platforms in ...,2026-05-04T16:12:11Z,neutral,0.999705
16,META,Nvidia Rises With Rival Chip Maker Report Due;...,2026-05-04T15:40:00Z,positive,0.999346
17,META,Micron Jumps 7%: Is the Memory Maker Now a Str...,2026-05-04T15:28:18Z,positive,0.980254
18,META,"While NVDA Dominates Headlines, Here’s Where t...",2026-05-04T14:27:28Z,neutral,0.999199
19,META,"They're Getting A $150K Payout At 18, But Thei...",2026-05-04T14:01:03Z,neutral,0.997512
20,MSFT,Tech stocks today: Semiconductor company earni...,2026-05-04T10:00:00Z,neutral,0.983314
21,MSFT,'It's a boom': Wall Street sees more market ga...,2026-05-03T13:00:32Z,positive,0.999687
22,MSFT,AI Chipmaker Cerebras Targets Raising Up To $4...,2026-05-04T16:50:27Z,positive,0.999280
23,MSFT,Microsoft Faces Focus as Musk Sought OpenAI Se...,2026-05-04T16:38:05Z,neutral,0.999605
24,MSFT,Jim Cramer Left Unimpressed By Microsoft (MSFT),2026-05-04T16:18:07Z,negative,0.994282
25,MSFT,Microsoft Pentagon AI Deal Deepens Cloud Ties ...,2026-05-04T16:13:43Z,negative,0.614907
26,MSFT,Is Microsoft a Buy as Cloud Revenue Continues ...,2026-05-04T15:50:00Z,positive,0.999402
27,MSFT,Micron Jumps 7%: Is the Memory Maker Now a Str...,2026-05-04T15:28:18Z,positive,0.980254
28,MSFT,Microsoft Stock Needs Faster Cloud Growth. Fix...,2026-05-04T15:23:00Z,positive,0.996316
29,MSFT,"While NVDA Dominates Headlines, Here’s Where t...",2026-05-04T14:27:28Z,neutral,0.999199
30,AMD,Tech stocks today: Semiconductor company earni...,2026-05-04T10:00:00Z,neutral,0.983314
31,AMD,AMD Shares Sink After HSBC Downgrade Ahead of ...,2026-05-04T16:57:08Z,negative,0.998016
32,AMD,AI Chipmaker Cerebras Targets Raising Up To $4...,2026-05-04T16:50:27Z,positive,0.999280
33,AMD,AMD Sinks 6% Despite a Holding Pattern in Inte...,2026-05-04T16:27:42Z,negative,0.997712
34,AMD,Cathie Wood Cashes In On Surging AMD Stock Wit...,2026-05-04T16:20:10Z,positive,0.985994
35,AMD,Nvidia Rises With Rival Chip Maker Report Due;...,2026-05-04T15:40:00Z,positive,0.999346
36,AMD,Advanced Micro Devices Stock Is Downgraded Bef...,2026-05-04T15:29:00Z,negative,0.996338
37,AMD,Micron Jumps 7%: Is the Memory Maker Now a Str...,2026-05-04T15:28:18Z,positive,0.980254
38,AMD,"S&P 500 Companies' Quarterly Profit, Revenue G...",2026-05-04T15:27:32Z,positive,0.999589
39,AMD,HSBC Downgrades AMD to Hold After 77% Rally: I...,2026-05-04T15:07:19Z,negative,0.997536
40,GOOGL,Tech stocks today: Semiconductor company earni...,2026-05-04T10:00:00Z,neutral,0.983314
41,GOOGL,Big Tech profits are being inflated by stakes ...,2026-05-04T13:33:30Z,negative,0.994435
42,GOOGL,Big Tech pulled into growing AI capacity concerns,2026-05-04T16:58:32Z,negative,0.987875
43,GOOGL,Jim Cramer Makes Big Prediction About Alphabet...,2026-05-04T16:39:57Z,neutral,0.999743
44,GOOGL,"Broadcom, Google And Caterpillar Lead AI Charg...",2026-05-04T15:44:30Z,neutral,0.999793
45,GOOGL,Alphabet Eyes 20% Upside as Cloud Backlog Surges,2026-05-04T15:42:28Z,positive,0.996275
46,GOOGL,"Sierra raises $950M at $15.8B valuation, led b...",2026-05-04T15:41:25Z,neutral,0.996382
47,GOOGL,Nvidia Rises With Rival Chip Maker Report Due;...,2026-05-04T15:40:00Z,positive,0.999346
48,GOOGL,Intel’s Next Chapter Government Backing Foundr...,2026-05-04T15:28:09Z,neutral,0.999838
49,GOOGL,Microsoft Stock Needs Faster Cloud Growth. Fix...,2026-05-04T15:23:00Z,positive,0.996316

In [30]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322166  196.210236  259.299286  24.206573
2023-03-16  96.599998   99.497643  203.334351  269.810394  25.518408
2023-03-17  97.839996  100.787003  194.086899  272.965698  25.702244
2023-03-20  96.809998  100.390282  196.269760  265.932251  25.877090
2023-03-21  95.930000  104.059944  200.585922  267.446289  26.175829

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135444  196.240001  260.315235  24.264521  ...
2023-03-16  96.690002  100.360514  204.157890  270.162052  25.565365  ...
2023-03-17  98.750000  101.996996  200.327916  276.775470  26.375647  ...
2023-03-20  96.940002  100.915936  197.807694  271.060798  26.000981  ...
2023-03-21  99.459999  104.238469  201.965099  268.638066  26.368659  ...

Price            Open                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.455857  191.447607  253.965606  23.739986
2023-03-16  89.720001   95.411413  196.716287  259.074617  24.005747
2023-03-17  96.660004   99.438150  198.998353  271.822782  25.959016
2023-03-20  96.300003   99.299300  196.934541  270.572365  25.592343
2023-03-21  97.000000  100.420030  201.617818  268.520847  26.156847

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

### Phase 3 : Analyze data

In [31]:
# Reshape data

reshaped_data = df["Close"].stack().reset_index().rename(columns={0: "close", "Ticker": "ticker", "Date": "date"})
reshaped_data.head()

        date ticker       close
0 2023-03-15    AMD   89.680000
1 2023-03-15  GOOGL   95.322166
2 2023-03-15   META  196.210236
3 2023-03-15   MSFT  259.299286
4 2023-03-15   NVDA   24.206573

In [32]:
reshaped_data = reshaped_data.set_index("date")

In [33]:
reshaped_data.to_sql("prices", conn, if_exists="replace", index=True)

3760

In [65]:
headline_data.to_sql("headlines", conn, if_exists="replace", index=True)

50

In [66]:
cursor.execute("SELECT COUNT(*) FROM prices")
print(cursor.fetchone())

cursor.execute("SELECT COUNT(*) FROM headlines")
print(cursor.fetchone())

(3760,)
(50,)

In [34]:
# Group data by months

# reshaped_data.dtypes

reshaped_data.groupby(["ticker", pd.Grouper(freq="ME")])["close"].mean()

ticker  date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
                         ...
NVDA    2025-11-30    187.962520
        2025-12-31    182.324673
        2026-01-31    186.711894
        2026-02-28    185.701528
        2026-03-31    182.350104
Name: close, Length: 185, dtype: float64

In [35]:
# Explore monthly trends

monthly_close = reshaped_data.groupby(["ticker", pd.Grouper(freq="ME")])["close"].mean()
monthly_close.head()

ticker  date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
Name: close, dtype: float64

In [36]:
reshaped_data.groupby(["ticker", pd.Grouper(freq="QE")])["close"].mean()

ticker  date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
                         ...
NVDA    2025-03-31    126.703980
        2025-06-30    125.817829
        2025-09-30    174.281514
        2025-12-31    186.121490
        2026-03-31    185.429958
Name: close, Length: 65, dtype: float64

In [37]:
# Explore quarterly trends

quarterly_close = reshaped_data.groupby(["ticker", pd.Grouper(freq="QE")])["close"].mean()
quarterly_close.head()

ticker  date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
Name: close, dtype: float64

In [38]:
headline_data.groupby(["ticker", "label"])["label"].count()

ticker  label
AMD     negative    4
        neutral     1
        positive    5
GOOGL   negative    2
        neutral     5
        positive    3
META    neutral     8
        positive    2
MSFT    negative    2
        neutral     3
        positive    5
NVDA    negative    3
        neutral     3
        positive    4
Name: label, dtype: int64

In [39]:
sentiment_count = headline_data.groupby(["ticker", "label"])["label"].count()

In [40]:
headline_data.groupby(["ticker"])["score"].mean()

ticker
AMD      0.993738
GOOGL    0.995332
META     0.995715
MSFT     0.956625
NVDA     0.928011
Name: score, dtype: float64

In [41]:
score_avg = headline_data.groupby(["ticker"])["score"].mean()

In [42]:
first_close = quarterly_close.groupby("ticker").first()
last_close = quarterly_close.groupby("ticker").last()

In [43]:
((last_close - first_close) / first_close) * 100

ticker
AMD      123.770470
GOOGL    214.705770
META     224.733361
MSFT      57.974528
NVDA     603.180094
Name: close, dtype: float64

In [44]:
stock_roc = ((last_close - first_close) / first_close) * 100

In [45]:
# All my analysis variables

# sentiment_count — label counts per ticker
# score_avg — average confidence score per ticker
# quarterly_close — price trend over 12 quarterly_close
# stock_roc — overall % price change over 3 years

In [46]:
headline_data[headline_data["score"] < 0.80]

,ticker,title,date,label,score
0,NVDA,Nvidia CEO Jensen Huang says company now has z...,2026-05-04T15:08:05Z,neutral,0.755732
5,NVDA,Did Anthropic Suck the Air From Palantir’s Com...,2026-05-04T16:45:21Z,negative,0.546641
25,MSFT,Microsoft Pentagon AI Deal Deepens Cloud Ties ...,2026-05-04T16:13:43Z,negative,0.614907

In [47]:
low_confidence = headline_data[headline_data["score"] < 0.80]

### Phase 4 : Visualize data

In [48]:
quarterly_df = quarterly_close.reset_index()

In [49]:
px.line(
    data_frame=quarterly_df, 
    x="date", 
    y="close", 
    color="ticker", 
    title="Q1 '23—Q2 '26 Quarterly Stock Prices"
    )

In [50]:
sentiment_df = sentiment_count.reset_index(name="count")

In [51]:
# Stacked bar chart
# px.bar(data_frame=sentiment_df, x="ticker", y="count", color="label", title="Recent News Headlines Sentiment")

In [52]:
px.bar(
    data_frame=sentiment_df,
    x="ticker", 
    y="count", 
    color="label", 
    barmode="group",
    title="Recent News Headlines Sentiment", 
    color_discrete_map = {
        "positive": "#48a860", 
        "neutral": "#bebdb8", 
        "negative": "#cd5c5c"
        }
    )

In [53]:
price_chart = px.line(
    data_frame=quarterly_df, 
    x="date", 
    y="close", 
    color="ticker", 
    title="Q1 '23—Q2 '26 Quarterly Stock Prices"
    )

sentiment_chart = px.bar(
    data_frame=sentiment_df,
    x="ticker", 
    y="count", 
    color="label", 
    barmode="group",
    title="Recent News Headlines Sentiment", 
    color_discrete_map = {
        "positive": "#48a860", 
        "neutral": "#bebdb8", 
        "negative": "#cd5c5c"
        }
    )

In [54]:
price_chart.write_html("outputs/price_chart.html")
sentiment_chart.write_html("outputs/sentiment_chart.html")

In [55]:
# Creates empty subplot container

fig = make_subplots(
    rows=2,
    cols=1,
    subplot_titles=("Quarterly Close Price (2023-2026)", "Current News Sentiment by Ticker")
    )

In [56]:
for trace in price_chart.data:
    fig.add_trace(trace, row=1, col=1)

for trace in sentiment_chart.data:
    fig.add_trace(trace, row=2, col=1)

In [57]:
fig.update_layout(
    title_text="AI Stock Performance & Current Sentiment Analysis",
    height=800
)

In [58]:
fig.write_html("outputs/stock_dashboard.html")

In [59]:
quarterly_close.index.get_level_values("date").max()

Timestamp('2026-03-31 00:00:00')

In [60]:
last_close

ticker
AMD      216.165714
GOOGL    318.872785
META     653.582659
MSFT     427.593246
NVDA     185.429958
Name: close, dtype: float64

In [61]:
stock_roc

ticker
AMD      123.770470
GOOGL    214.705770
META     224.733361
MSFT      57.974528
NVDA     603.180094
Name: close, dtype: float64

In [62]:
for ticker in last_close.index:
    fig.add_annotation(
        x = "2026-03-31",
        y = last_close[ticker],
        text = f"+{stock_roc[ticker]:.1f}%",
        font = dict(size=10)
    )

In [63]:
fig

In [64]:
fig.write_html("outputs/stock_dashboard.html")