In [ ]:
# PHASE 1 : Collecting data

In [2]:
# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np

In [3]:
# List to capture AI stocks—AI infrastructure and AI-powered companies.
stocks = ["NVDA", "META", "MSFT", "AMD", "GOOGL"]

In [4]:
# df is Dataframe—function which passes in stocks and date range for df.
df = yf.download(tickers=stocks, start="2023-03-15", end="2026-03-15")

[*********************100%***********************]  5 of 5 completed

In [5]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322159  196.210251  259.299286  24.206572
2023-03-16  96.599998   99.497650  203.334335  269.810364  25.518410
2023-03-17  97.839996  100.787003  194.086899  272.965637  25.702246
2023-03-20  96.809998  100.390282  196.269775  265.932220  25.877090
2023-03-21  95.930000  104.059944  200.585907  267.446289  26.175831

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135437  196.240016  260.315235  24.264519  ...
2023-03-16  96.690002  100.360521  204.157874  270.162021  25.565367  ...
2023-03-17  98.750000  101.996996  200.327916  276.775408  26.375649  ...
2023-03-20  96.940002  100.915936  197.807710  271.060767  26.000981  ...
2023-03-21  99.459999  104.238469  201.965083  268.638066  26.368661  ...

Price            Open                                                \
Ticker            AMD      GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.45585  191.447622  253.965606  23.739984
2023-03-16  89.720001   95.41142  196.716272  259.074588  24.005749
2023-03-17  96.660004   99.43815  198.998353  271.822721  25.959018
2023-03-20  96.300003   99.29930  196.934557  270.572334  25.592343
2023-03-21  97.000000  100.42003  201.617802  268.520847  26.156849

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [6]:
df.columns

MultiIndex([( 'Close',   'AMD'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'META'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'NVDA'),
            (  'High',   'AMD'),
            (  'High', 'GOOGL'),
            (  'High',  'META'),
            (  'High',  'MSFT'),
            (  'High',  'NVDA'),
            (   'Low',   'AMD'),
            (   'Low', 'GOOGL'),
            (   'Low',  'META'),
            (   'Low',  'MSFT'),
            (   'Low',  'NVDA'),
            (  'Open',   'AMD'),
            (  'Open', 'GOOGL'),
            (  'Open',  'META'),
            (  'Open',  'MSFT'),
            (  'Open',  'NVDA'),
            ('Volume',   'AMD'),
            ('Volume', 'GOOGL'),
            ('Volume',  'META'),
            ('Volume',  'MSFT'),
            ('Volume',  'NVDA')],
           names=['Price', 'Ticker'])

In [7]:
df.shape

(752, 25)

In [8]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 752 entries, 2023-03-15 to 2026-03-13
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, AMD)     752 non-null    float64
 1   (Close, GOOGL)   752 non-null    float64
 2   (Close, META)    752 non-null    float64
 3   (Close, MSFT)    752 non-null    float64
 4   (Close, NVDA)    752 non-null    float64
 5   (High, AMD)      752 non-null    float64
 6   (High, GOOGL)    752 non-null    float64
 7   (High, META)     752 non-null    float64
 8   (High, MSFT)     752 non-null    float64
 9   (High, NVDA)     752 non-null    float64
 10  (Low, AMD)       752 non-null    float64
 11  (Low, GOOGL)     752 non-null    float64
 12  (Low, META)      752 non-null    float64
 13  (Low, MSFT)      752 non-null    float64
 14  (Low, NVDA)      752 non-null    float64
 15  (Open, AMD)      752 non-null    float64
 16  (Open, GOOGL)    752 non-null    float64
 17  (Open, META)     752 non-null    float64
 18  (Open, MSFT)     752 non-null    float64
 19  (Open, NVDA)     752 non-null    float64
 20  (Volume, AMD)    752 non-null    int64
 21  (Volume, GOOGL)  752 non-null    int64
 22  (Volume, META)   752 non-null    int64
 23  (Volume, MSFT)   752 non-null    int64
 24  (Volume, NVDA)   752 non-null    int64
dtypes: float64(20), int64(5)
memory usage: 152.8 KB

In [9]:
df.describe()

Price        Close                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.828324  178.303726  510.032441  406.722718  110.174772
std      41.766704   59.267770  163.535075   64.594056   53.493754
min      78.209999   95.322159  194.086899  259.299286   24.206572
25%     112.002502  136.263779  335.286362  365.005539   48.840422
50%     141.760002  164.499832  524.088867  409.369644  116.998009
75%     169.445004  190.765568  645.484070  447.321564  146.969250
max     264.329987  343.448242  788.148987  539.825256  207.017273

Price         High                                                  ...  \
Ticker         AMD       GOOGL        META        MSFT        NVDA  ...
count   752.000000  752.000000  752.000000  752.000000  752.000000  ...
mean    149.719827  180.249596  516.432462  410.145543  111.981672  ...
std      42.878968   60.022627  165.473901   64.914353   54.248785  ...
min      85.480003   96.135437  196.240016  260.315235   24.264519  ...
25%     114.395002  137.528314  337.253450  368.108833   49.556451  ...
50%     144.289993  165.989440  532.311023  412.460421  119.131442  ...
75%     172.049995  192.186486  652.566306  450.570331  148.926143  ...
max     267.079987  348.754481  794.384398  552.242002  212.166717  ...

Price         Open                                                  \
Ticker         AMD       GOOGL        META        MSFT        NVDA
count   752.000000  752.000000  752.000000  752.000000  752.000000
mean    146.924468  178.153442  510.100255  406.707281  110.223178
std      41.941908   59.299622  164.119504   64.850846   53.622100
min      79.220001   92.455850  191.447622  253.965606   23.739984
25%     112.052500  136.271209  335.187120  364.869650   49.125129
50%     142.730003  164.479669  524.796338  410.068699  117.272925
75%     169.307503  190.554032  642.907274  446.764578  147.766453
max     264.190002  347.095646  789.296390  552.023241  208.057150

Price         Volume
Ticker           AMD         GOOGL          META          MSFT          NVDA
count   7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02  7.520000e+02
mean    5.305591e+07  3.181655e+07  1.695474e+07  2.381806e+07  3.364204e+08
std     2.434066e+07  1.357632e+07  9.409263e+06  1.046421e+07  1.752086e+08
min     7.956800e+06  1.009740e+07  4.726100e+06  5.855900e+06  6.552850e+07
25%     3.606890e+07  2.321348e+07  1.131440e+07  1.726135e+07  1.955628e+08
50%     4.822515e+07  2.849140e+07  1.495705e+07  2.121225e+07  3.052285e+08
75%     6.357465e+07  3.573692e+07  1.942280e+07  2.670622e+07  4.300298e+08
max     2.488596e+08  1.274901e+08  8.844010e+07  1.288553e+08  1.543911e+09

[8 rows x 25 columns]

In [10]:
df.tail()

Price            Close                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  202.679993  306.359985  646.836182  409.410004  182.640106
2026-03-10  203.229996  307.040009  653.510498  405.760010  184.760010
2026-03-11  204.830002  308.700012  654.299805  404.880005  186.029999
2026-03-12  197.740005  303.549988  637.634094  401.859985  183.139999
2026-03-13  193.389999  302.279999  613.184998  395.549988  180.250000

Price             High                                                  ...  \
Ticker             AMD       GOOGL        META        MSFT        NVDA  ...
Date                                                                    ...
2026-03-09  202.970001  306.799988  647.195859  410.209991  182.900102  ...
2026-03-10  206.589996  309.510010  659.735149  410.200012  186.429918  ...
2026-03-11  209.210007  311.420013  658.556170  409.010010  187.619995  ...
2026-03-12  203.619995  308.940002  652.940997  406.119995  184.940002  ...
2026-03-13  199.679993  307.690002  628.631733  404.799988  186.089996  ...

Price             Open                                                  \
Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2026-03-09  189.360001  294.359985  634.236984  404.920013  176.820429
2026-03-10  202.509995  306.170013  653.000925  410.029999  182.390128
2026-03-11  205.110001  306.750000  654.199915  405.570007  185.910004
2026-03-12  202.830002  306.820007  648.195060  404.630005  184.050003
2026-03-13  198.110001  307.010010  623.356281  401.000000  184.919998

Price         Volume
Ticker           AMD     GOOGL      META      MSFT       NVDA
Date
2026-03-09  38877200  29312100  13489700  30131900  177213600
2026-03-10  29139200  23239700   9859300  31706400  179118500
2026-03-11  23076400  24125700   8977200  25512100  145280400
2026-03-12  28886900  24928300  11617500  27263900  155762700
2026-03-13  27561900  23693100  18957600  26848000  160988400

[5 rows x 25 columns]

In [11]:
df["Low"]

Ticker             AMD       GOOGL        META        MSFT        NVDA
Date
2023-03-15   86.220001   91.880602  189.354051  253.213401   23.339339
2023-03-16   89.019997   94.717161  194.563170  257.189244   23.872865
2023-03-17   95.940002   99.279458  193.908292  269.927599   25.645295
2023-03-20   92.900002   99.051349  192.132246  263.607275   25.107771
2023-03-21   93.639999  100.390277  196.408681  263.284832   25.358555
...                ...         ...         ...         ...         ...
2026-03-09  189.020004  294.079987  626.243828  403.500000  175.550494
2026-03-10  202.199997  305.570007  648.444828  402.929993  182.000149
2026-03-11  203.630005  305.920013  647.805365  401.589996  184.449997
2026-03-12  196.669998  301.029999  636.355221  401.709991  181.750000
2026-03-13  192.270004  300.440002  609.028522  394.250000  179.940002

[752 rows x 5 columns]

In [12]:
df["Low"]["NVDA"]

Date
2023-03-15     23.339339
2023-03-16     23.872865
2023-03-17     25.645295
2023-03-20     25.107771
2023-03-21     25.358555
                 ...
2026-03-09    175.550494
2026-03-10    182.000149
2026-03-11    184.449997
2026-03-12    181.750000
2026-03-13    179.940002
Name: NVDA, Length: 752, dtype: float64

In [13]:
(df == 0).any().sum()

np.int64(0)

In [14]:
df["Close"]
close_prices = df["Close"]

In [15]:
yf.Ticker("NVDA").news

[{'id': 'a6412659-4d41-447c-a5c6-9baa2354916d',
  'content': {'id': 'a6412659-4d41-447c-a5c6-9baa2354916d',
   'contentType': 'STORY',
   'title': '2 charts show why Magnificent 7 stocks are being loved again',
   'description': '',
   'summary': 'The earnings growth potential of the Mag 7 continues to stand out.',
   'pubDate': '2026-04-20T15:11:05Z',
   'displayTime': '2026-04-20T15:11:05Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/134c9320-3cc7-11f1-bfd7-d34848931aa2',
    'originalWidth': 4906,
    'originalHeight': 3270,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/kH4XtwuIYxmNBB6dKNZ2kg--~B/aD0zMjcwO3c9NDkwNjthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2026-04/134c9320-3cc7-11f1-bfd7-d34848931aa2',
      'width': 4906,
      'height': 3270,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/4M92AHBJS.xrNhz1afUUkg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2026-04/134c9320-3cc7-11f1-bfd7-d34848931aa2',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/2-charts-show-why-magnificent-7-stocks-are-being-loved-again-151105348.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/2-charts-show-why-magnificent-7-stocks-are-being-loved-again-151105348.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': {'storylineItems': [{'content': {'id': 'a0098897-4e64-4934-abc2-29a3b61f173a',
       'contentType': 'VIDEO',
       'isHosted': True,
       'title': 'Marvell–Google AI talks, Trump EO boosts psychedelic stocks',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/06K1cuOJlffAEkGc9PP3Vw--~B/aD0zMzc1O3c9NjAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/7efaf2b0-ca9b-4c1e-ba17-6a58cc82698b_f36cd03421b97fc973a106d7409e11d65e9c37f2df0490a23ca54a533c9f4366.net/images/2026-04/7efaf2b0-ca9b-4c1e-ba17-6a58cc82698b',
        'originalWidth': 6000,
        'originalHeight': 3375,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance Video',
        'sourceId': 'video.yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/video/marvell-google-ai-talks-trump-eo-boosts-psychedelic-stocks-150254801.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/marvell-google-ai-talks-trump-eo-boosts-psychedelic-stocks-150254801.html'}}},
     {'content': {'id': '308f44af-33c1-48ea-b12c-c9572cd19d50',
       'contentType': 'STORY',
       'isHosted': True,
       'title': 'Tech stocks today: Google and Marvell reportedly developing AI chips, Tesla falls with earnings set for Wednesday',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/R7t7s0hVe7_AaaE09_0zUA--~B/aD0yMjE5O3c9MzMyOTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/fd05360d-b667-4d98-b362-c348623c06f9',
        'originalWidth': 3329,
        'originalHeight': 2219,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/live/tech-stocks-today-google-and-marvell-reportedly-developing-ai-chips-tesla-falls-with-earnings-set-for-wednesday-144220621.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/live/tech-stocks-today-google-and-marvell-reportedly-developing-ai-chips-tesla-falls-with-earnings-set-for-wednesday-144220621.html'}}}]}}},
 {'id': '8b09d831-bb91-4d3e-aa0e-e2431e3aa16e',
  'content': {'id': '8b09d831-bb91-4d3e-aa0e-e2431e3aa16e',
   'contentType': 'STORY',
   'title': 'Why the tech stock rally may only be starting',
   'description': '',
   'summary': 'Good signs on tech stocks continue to emerge.',
   'pubDate': '2026-04-20T14:45:35Z',
   'displayTime': '2026-04-20T14:45:35Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/gfXa8W65t.tHiDRgDaTfww--~B/aD01MjA5O3c9NzgxNDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/a976999b-4852-4a8f-9aab-dbb602f225e7',
    'originalWidth': 7814,
    'originalHeight': 5209,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/gfXa8W65t.tHiDRgDaTfww--~B/aD01MjA5O3c9NzgxNDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/a976999b-4852-4a8f-9aab-dbb602f225e7',
      'width': 7814,
      'height': 5209,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/6vtwKweDI4hem8c5kgNIYw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-04/a976999b-4852-4a8f-9aab-dbb602f225e7',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/why-the-tech-stock-rally-may-only-be-starting-144535609.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/why-the-tech-stock-rally-may-only-be-starting-144535609.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': {'storylineItems': [{'content': {'id': '7abc3232-76d0-4171-a074-2b642b55005a',
       'contentType': 'STORY',
       'isHosted': True,
       'title': "Bitcoin's comeback won't happen in 2026: Deutsche Bank survey of consumers",
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2021-04/5af69a20-a8e5-11eb-bf7f-5f2e9fe992ce',
        'originalWidth': 3931,
        'originalHeight': 2502,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/news/bitcoins-comeback-wont-happen-in-2026-deutsche-bank-survey-of-consumers-134056305.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/bitcoins-comeback-wont-happen-in-2026-deutsche-bank-survey-of-consumers-134056305.html'}}},
     {'content': {'id': '6ad44c76-2c54-4f40-8446-0030a4cc41eb',
       'contentType': 'STORY',
       'isHosted': True,
       'title': "Semiconductor stocks haven't been this hot since the dot-com bubble — and it could end badly",
       'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/tTcDcyy8LK_GaaPJl8ZJmQ--~B/aD0yNjUwO3c9Mzk3NTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-03/71c3265c-a313-46cb-ba01-7c5b15b40928',
        'originalWidth': 3975,
        'originalHeight': 2650,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/news/semiconductor-stocks-havent-been-this-hot-since-the-dot-com-bubble--and-it-could-end-badly-131124176.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/semiconductor-stocks-havent-been-this-hot-since-the-dot-com-bubble--and-it-could-end-badly-131124176.html'}}}]}}},
 {'id': 'be889ffb-1cd9-344e-9b16-db7dd7ea7b02',
  'content': {'id': 'be889ffb-1cd9-344e-9b16-db7dd7ea7b02',
   'contentType': 'STORY',
   'title': 'Lucid Drops 5% Into New Lows: Could the Free-Fall Itself Trigger a Buyout Catalyst?',
   'description': '',
   'summary': 'Lucid Group (NASDAQ:LCID) stock is down 5% in Monday trading, sliding from $7.30 to $6.93 and touching fresh record lows. The stock has now shed 34% year-to-date, a collapse that’s moved well beyond a simple earnings story. What’s different today is the nature of the conversation surrounding LCID stock. The investor community is sharply divided ... Lucid Drops 5% Into New Lows: Could the Free-Fall Itself Trigger a Buyout Catalyst?',
   'pubDate': '2026-04-20T17:15:47Z',
   'displayTime': '2026-04-20T17:15:47Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/dff664b97040345ba97a530757e7afea',
    'originalWidth': 1366,
    'originalHeight': 768,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/k8BFBnXeF.V6vKDfSWUn4g--~B/aD03Njg7dz0xMzY2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/dff664b97040345ba97a530757e7afea',
      'width': 1366,
      'height': 768,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/2aBigHIcV.k0hK14qi4HIQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/dff664b97040345ba97a530757e7afea',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/04/20/lucid-drops-5-into-new-lows-could-the-free-fall-itself-trigger-a-buyout-catalyst/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/lucid-drops-5-lows-could-171547426.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '633ad1b4-d519-313d-94a3-42c15c3c41ed',
  'content': {'id': '633ad1b4-d519-313d-94a3-42c15c3c41ed',
   'contentType': 'STORY',
   'title': 'Nvidia is losing an industry that saved it from bankruptcy',
   'description': '',
   'summary': "Nvidia (NVDA) is now the world's most valuable chip company. The community that helped make it what it is feels like it has been left behind. Gamers are growing increasingly frustrated with Nvidia as the company's AI boom drives it to prioritize data-center chips over consumer gaming GPUs. The ...",
   'pubDate': '2026-04-20T17:07:00Z',
   'displayTime': '2026-04-20T17:07:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/thestreet_881/476ad3386e281121cdb37e70eabe5175',
    'originalWidth': 1200,
    'originalHeight': 675,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/hLvLnS8CHlh4kOotsDX8ow--~B/aD02NzU7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/thestreet_881/476ad3386e281121cdb37e70eabe5175',
      'width': 1200,
      'height': 675,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/zAGmAIVCkjzdYWi9.ULqAg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/thestreet_881/476ad3386e281121cdb37e70eabe5175',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'TheStreet',
    'url': 'https://www.thestreet.com/',
    'sourceId': 'thestreet_881'},
   'canonicalUrl': {'url': 'https://www.thestreet.com/technology/nvidia-is-losing-an-industry-that-saved-it-from-bankruptcy-gamers',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/nvidia-losing-industry-saved-bankruptcy-170700208.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'e841ad51-a165-3fe2-ba0d-2d522f276150',
  'content': {'id': 'e841ad51-a165-3fe2-ba0d-2d522f276150',
   'contentType': 'STORY',
   'title': 'Bull vs Bear: Is Tesla Stock a Buy or Sell?',
   'description': '',
   'summary': "Here's a look at the bullish and bearish cases for Tesla stock.",
   'pubDate': '2026-04-20T17:05:00Z',
   'displayTime': '2026-04-20T17:05:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/bd65194c0529cde148c7503fd1b00a3e',
    'originalWidth': 1200,
    'originalHeight': 800,
    'caption': 'Tesla logo.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/H7vUv.azDMIpyug5Q0ZX8w--~B/aD04MDA7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/bd65194c0529cde148c7503fd1b00a3e',
      'width': 1200,
      'height': 800,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/DNylRqZyBdEeesCzEr6LHA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/bd65194c0529cde148c7503fd1b00a3e',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/04/20/bull-vs-bear-is-tesla-stock-a-buy-or-sell/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/bull-vs-bear-tesla-stock-170500427.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'eb0ff88d-6203-3b32-b483-5da2153bf650',
  'content': {'id': 'eb0ff88d-6203-3b32-b483-5da2153bf650',
   'contentType': 'STORY',
   'title': 'Stock Market Today: Dow Dips As Trump Says This On Iran; This Stock Clears Entry (Live Coverage)',
   'description': '',
   'summary': 'The Dow Jones index fell after President Trump spoke on Iran. Nvidia and Amazon lagged on the stock market today. A finance stock climbed.',
   'pubDate': '2026-04-20T16:56:48Z',
   'displayTime': '2026-04-20T16:56:48Z',
   'isHosted': False,
   'bypassModal': False,
   'previewUrl': 'https://finance.yahoo.com/m/eb0ff88d-6203-3b32-b483-5da2153bf650/stock-market-today-dow-dips.html',
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/ibd.com/9e11147a31dc0bcecac9fce7ae56bed1',
    'originalWidth': 1000,
    'originalHeight': 563,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/gkAq0prvNkzcocx32fabZA--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/9e11147a31dc0bcecac9fce7ae56bed1',
      'width': 1000,
      'height': 563,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/cvKgAdj983TtcMnTBrjDyw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/ibd.com/9e11147a31dc0bcecac9fce7ae56bed1',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': "Investor's Business Daily",
    'url': 'http://www.investors.com/',
    'sourceId': 'ibd.com'},
   'canonicalUrl': {'url': 'https://www.investors.com/market-trend/stock-market-today/dow-jones-sp500-nasdaq-us-iran-oil-prices/?src=A00220&yptr=yahoo',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': None,
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '62059209-b47e-34a7-965c-b5d43c115dc9',
  'content': {'id': '62059209-b47e-34a7-965c-b5d43c115dc9',
   'contentType': 'STORY',
   'title': 'Nvidia Rival Cerebras Files For IPO After Scrapping Plans Last Year',
   'description': '',
   'summary': 'Artificial intelligence chipmaker Cerebras Systems filed for an initial public offering with the Securities and Exchange Commission on Friday, after withdrawing its IPO plans in October 2025, stating the 2024 filing document was "stale." Cerebras Systems, a California-based competitor to Nvidia, submitted a registration statement to the SEC for the proposed IPO of its Class A common stock. The number of shares and the price range for the offering are yet to be determined, contingent on market co',
   'pubDate': '2026-04-20T16:31:05Z',
   'displayTime': '2026-04-20T16:31:05Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/Benzinga/1cafcf1566a0f703a54ab2b62d89de98',
    'originalWidth': 1000,
    'originalHeight': 666,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/tsK9HPmOm3NYA1hb7yUWzA--~B/aD02NjY7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Benzinga/1cafcf1566a0f703a54ab2b62d89de98',
      'width': 1000,
      'height': 666,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/4fFR.ZUAeT2jGWT7bRU7FQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/Benzinga/1cafcf1566a0f703a54ab2b62d89de98',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Benzinga',
    'url': 'http://www.benzinga.com/',
    'sourceId': 'Benzinga'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/nvidia-rival-cerebras-files-ipo-163105781.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/nvidia-rival-cerebras-files-ipo-163105781.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'c68ea08b-1ba0-3d3f-9326-77c13f77e134',
  'content': {'id': 'c68ea08b-1ba0-3d3f-9326-77c13f77e134',
   'contentType': 'STORY',
   'title': 'BlackBerry Surges 15% on NVIDIA Deal: Is the Long-Awaited Revaluation Finally Here?',
   'description': '',
   'summary': 'BlackBerry (NYSE:BB) stock is up 15% in Monday afternoon trading, rising from $4.86 to $5.59, after the company announced an expanded collaboration with NVIDIA (NASDAQ:NVDA), partnering to integrate its QNX safety-critical operating system into advanced edge AI applications. BB stock is up 80% over the past year. The announcement lands at a moment when BlackBerry ... BlackBerry Surges 15% on NVIDIA Deal: Is the Long-Awaited Revaluation Finally Here?',
   'pubDate': '2026-04-20T16:26:20Z',
   'displayTime': '2026-04-20T16:26:20Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/93d6ff2a4c624c4ed050934fc91901c7',
    'originalWidth': 1376,
    'originalHeight': 768,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/.q2dfmG9U7wvUdl.hxWpyg--~B/aD03Njg7dz0xMzc2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/93d6ff2a4c624c4ed050934fc91901c7',
      'width': 1376,
      'height': 768,
      'tag': 'original'},

In [16]:
headlines = []

for stock in stocks:
    news = yf.Ticker(stock).news
    for article in news:
        headlines.append({
            "ticker": stock,
            "title": article["content"]["title"],
            "date": article["content"]["pubDate"]
        })

In [17]:
# Show all content and metadata for single headline
yf.Ticker("NVDA").news[0]

{'id': 'a6412659-4d41-447c-a5c6-9baa2354916d',
 'content': {'id': 'a6412659-4d41-447c-a5c6-9baa2354916d',
  'contentType': 'STORY',
  'title': '2 charts show why Magnificent 7 stocks are being loved again',
  'description': '',
  'summary': 'The earnings growth potential of the Mag 7 continues to stand out.',
  'pubDate': '2026-04-20T15:11:05Z',
  'displayTime': '2026-04-20T15:11:05Z',
  'isHosted': True,
  'bypassModal': False,
  'previewUrl': None,
  'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2026-04/134c9320-3cc7-11f1-bfd7-d34848931aa2',
   'originalWidth': 4906,
   'originalHeight': 3270,
   'caption': '',
   'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/kH4XtwuIYxmNBB6dKNZ2kg--~B/aD0zMjcwO3c9NDkwNjthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2026-04/134c9320-3cc7-11f1-bfd7-d34848931aa2',
     'width': 4906,
     'height': 3270,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/4M92AHBJS.xrNhz1afUUkg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2026-04/134c9320-3cc7-11f1-bfd7-d34848931aa2',
     'width': 170,
     'height': 128,
     'tag': '170x128'}]},
  'provider': {'displayName': 'Yahoo Finance',
   'url': 'http://finance.yahoo.com/',
   'sourceId': 'yahoofinance.com'},
  'canonicalUrl': {'url': 'https://finance.yahoo.com/news/2-charts-show-why-magnificent-7-stocks-are-being-loved-again-151105348.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/2-charts-show-why-magnificent-7-stocks-are-being-loved-again-151105348.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'metadata': {'editorsPick': True},
  'finance': {'premiumFinance': {'isPremiumNews': False,
    'isPremiumFreeNews': False}},
  'storyline': {'storylineItems': [{'content': {'id': 'a0098897-4e64-4934-abc2-29a3b61f173a',
      'contentType': 'VIDEO',
      'isHosted': True,
      'title': 'Marvell–Google AI talks, Trump EO boosts psychedelic stocks',
      'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/06K1cuOJlffAEkGc9PP3Vw--~B/aD0zMzc1O3c9NjAwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/7efaf2b0-ca9b-4c1e-ba17-6a58cc82698b_f36cd03421b97fc973a106d7409e11d65e9c37f2df0490a23ca54a533c9f4366.net/images/2026-04/7efaf2b0-ca9b-4c1e-ba17-6a58cc82698b',
       'originalWidth': 6000,
       'originalHeight': 3375,
       'caption': '',
       'resolutions': None},
      'provider': {'displayName': 'Yahoo Finance Video',
       'sourceId': 'video.yahoofinance.com'},
      'previewUrl': None,
      'providerContentUrl': '',
      'canonicalUrl': {'url': 'https://finance.yahoo.com/video/marvell-google-ai-talks-trump-eo-boosts-psychedelic-stocks-150254801.html'},
      'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/marvell-google-ai-talks-trump-eo-boosts-psychedelic-stocks-150254801.html'}}},
    {'content': {'id': '308f44af-33c1-48ea-b12c-c9572cd19d50',
      'contentType': 'STORY',
      'isHosted': True,
      'title': 'Tech stocks today: Google and Marvell reportedly developing AI chips, Tesla falls with earnings set for Wednesday',
      'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/R7t7s0hVe7_AaaE09_0zUA--~B/aD0yMjE5O3c9MzMyOTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-04/fd05360d-b667-4d98-b362-c348623c06f9',
       'originalWidth': 3329,
       'originalHeight': 2219,
       'caption': '',
       'resolutions': None},
      'provider': {'displayName': 'Yahoo Finance',
       'sourceId': 'yahoofinance.com'},
      'previewUrl': None,
      'providerContentUrl': '',
      'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/live/tech-stocks-today-google-and-marvell-reportedly-developing-ai-chips-tesla-falls-with-earnings-set-for-wednesday-144220621.html'},
      'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/live/tech-stocks-today-google-and-marvell-reportedly-developing-ai-chips-tesla-falls-with-earnings-set-for-wednesday-144220621.html'}}}]}}}

In [18]:
headlines[0]

{'ticker': 'NVDA',
 'title': '2 charts show why Magnificent 7 stocks are being loved again',
 'date': '2026-04-20T15:11:05Z'}

In [19]:
len(headlines)

50

In [ ]:
# PHASE 2 : Flattening data

In [20]:
headline_data = pd.DataFrame(headlines)

In [21]:
headline_data.head()

,ticker,title,date
0,NVDA,2 charts show why Magnificent 7 stocks are bei...,2026-04-20T15:11:05Z
1,NVDA,Why the tech stock rally may only be starting,2026-04-20T14:45:35Z
2,NVDA,Lucid Drops 5% Into New Lows: Could the Free-F...,2026-04-20T17:15:47Z
3,NVDA,Nvidia is losing an industry that saved it fro...,2026-04-20T17:07:00Z
4,NVDA,Bull vs Bear: Is Tesla Stock a Buy or Sell?,2026-04-20T17:05:00Z

In [22]:
from src.sentiment import analyze_sentiment

In [23]:
title_results = []
score_results = []

for title in headline_data["title"]:
    sentiment = analyze_sentiment(title)
    title_results.append(sentiment[0][0]["label"])
    score_results.append(sentiment[0][0]["score"])

In [24]:
headline_data["label"] = title_results
headline_data["score"] = score_results
headline_data

,ticker,title,date,label,score
0,NVDA,2 charts show why Magnificent 7 stocks are bei...,2026-04-20T15:11:05Z,positive,0.510385
1,NVDA,Why the tech stock rally may only be starting,2026-04-20T14:45:35Z,neutral,0.977323
2,NVDA,Lucid Drops 5% Into New Lows: Could the Free-F...,2026-04-20T17:15:47Z,negative,0.996910
3,NVDA,Nvidia is losing an industry that saved it fro...,2026-04-20T17:07:00Z,negative,0.997245
4,NVDA,Bull vs Bear: Is Tesla Stock a Buy or Sell?,2026-04-20T17:05:00Z,neutral,0.961115
5,NVDA,Stock Market Today: Dow Dips As Trump Says Thi...,2026-04-20T16:56:48Z,negative,0.798510
6,NVDA,Nvidia Rival Cerebras Files For IPO After Scra...,2026-04-20T16:31:05Z,neutral,0.999824
7,NVDA,BlackBerry Surges 15% on NVIDIA Deal: Is the L...,2026-04-20T16:26:20Z,positive,0.999180
8,NVDA,Could This High-Yield Dividend Stock Help Make...,2026-04-20T16:25:00Z,positive,0.996300
9,NVDA,Why Compass Pathways Stock Rocketed 40% Today,2026-04-20T16:22:35Z,positive,0.999408
10,META,2 charts show why Magnificent 7 stocks are bei...,2026-04-20T15:11:05Z,positive,0.510385
11,META,CEOs should be 'ringing the fire alarm' on AI ...,2026-04-20T13:14:09Z,neutral,0.999659
12,META,Meta vs. Alphabet: One Just Handed Investors a...,2026-04-20T17:05:08Z,negative,0.996342
13,META,US Equity Indexes Decline as Fate of Iran Peac...,2026-04-20T16:57:46Z,negative,0.998038
14,META,BofA Trims Meta Platforms Price Target to $820...,2026-04-20T15:24:20Z,positive,0.994667
15,META,The Stocks Billionaires Can’t Stop Buying Righ...,2026-04-20T15:08:32Z,neutral,0.999559
16,META,When Will Meta Begin Layoffs? Report Outlines ...,2026-04-20T14:31:08Z,neutral,0.999839
17,META,Should You Buy Meta Platforms (META) Before Ea...,2026-04-20T13:42:53Z,neutral,0.999874
18,META,Is Broadcom (AVGO) The Best AI Chip Stock Pick...,2026-04-20T13:17:40Z,neutral,0.999874
19,META,Broadcom’s 140% Surge Shows XMAG Investors Get...,2026-04-20T13:16:58Z,positive,0.999264
20,MSFT,Why Amazon's partnership with Anthropic could ...,2026-04-20T16:00:00Z,positive,0.999622
21,MSFT,Google Stock In Focus For Far More Than Just E...,2026-04-20T16:29:32Z,neutral,0.999875
22,MSFT,Marvell Stock Pops Amid AI Chip Talks With Goo...,2026-04-20T16:12:00Z,negative,0.911840
23,MSFT,Motley Fool Asset Management’s Top AI Stock Pi...,2026-04-20T15:42:50Z,neutral,0.999825
24,MSFT,"Alphabet Stock Has Further to Run, Analyst Say...",2026-04-20T15:11:00Z,negative,0.998004
25,MSFT,"Microsoft Is Having Its Worst Year Since 2022,...",2026-04-20T14:35:00Z,negative,0.996500
26,MSFT,Adobe launches AI suite for corporate clients ...,2026-04-20T14:13:00Z,neutral,0.952995
27,MSFT,Microsoft Corporation (MSFT) Slid Despite Deli...,2026-04-20T13:58:12Z,negative,0.998177
28,MSFT,Adobe Seeks to Beat Back Software Fears With N...,2026-04-20T13:48:00Z,positive,0.999288
29,MSFT,Microsoft is Being Thrown Out With the Bathwat...,2026-04-20T13:36:04Z,neutral,0.998603
30,AMD,Tech stocks today: Google and Marvell reported...,2026-03-13T14:42:20Z,negative,0.997835
31,AMD,Semiconductor stocks haven't been this hot sin...,2026-04-20T13:11:24Z,negative,0.998267
32,AMD,"AI-Driven 'CPU Renaissance' To Boost AMD, Arm ...",2026-04-20T16:29:38Z,positive,0.998478
33,AMD,Stifel Raises AMD Target to $320: Is the AI Ch...,2026-04-20T15:06:23Z,positive,0.999375
34,AMD,One Thing I'm Watching: The Market's Bad Breadth,2026-04-20T13:49:58Z,neutral,0.994704
35,AMD,Here's Why Advanced Micro Devices (AMD) is a S...,2026-04-20T13:45:01Z,positive,0.999449
36,AMD,"Advanced Micro Devices, Inc. (AMD) Is a Trendi...",2026-04-20T13:00:04Z,neutral,0.730097
37,AMD,"AI Stocks: Google Makes 'Agentic Cloud' Pitch,...",2026-04-20T11:50:44Z,neutral,0.999699
38,AMD,This Stock Will Be More Profitable Than Amazon...,2026-04-19T17:09:18Z,positive,0.990977
39,AMD,Prediction: This AI Stock Will Become the Firs...,2026-04-19T10:10:00Z,neutral,0.999867
40,GOOGL,Why Amazon's partnership with Anthropic could ...,2026-04-20T16:00:00Z,positive,0.999622
41,GOOGL,Tech stocks today: Google and Marvell reported...,2026-03-13T14:42:20Z,negative,0.997835
42,GOOGL,Meta vs. Alphabet: One Just Handed Investors a...,2026-04-20T17:05:08Z,negative,0.996342
43,GOOGL,US Equity Indexes Decline as Fate of Iran Peac...,2026-04-20T16:57:46Z,negative,0.998038
44,GOOGL,Why Intel Stock Is Sliding Today,2026-04-20T16:30:57Z,negative,0.996588
45,GOOGL,Google Stock In Focus For Far More Than Just E...,2026-04-20T16:29:32Z,neutral,0.999875
46,GOOGL,Xcel Energy Fire Risk Seen Overly Discounted b...,2026-04-20T16:26:38Z,negative,0.993767
47,GOOGL,Marvell Stock Pops Amid AI Chip Talks With Goo...,2026-04-20T16:12:00Z,negative,0.911840
48,GOOGL,The Quantum Threat Is Coming for Bitcoin and C...,2026-04-20T16:06:48Z,neutral,0.999796
49,GOOGL,This Strategy Pays You 8.2% While Lining Up NF...,2026-04-20T16:01:36Z,positive,0.593566

In [25]:
df.head()

Price           Close                                                 \
Ticker            AMD       GOOGL        META        MSFT       NVDA
Date
2023-03-15  89.680000   95.322159  196.210251  259.299286  24.206572
2023-03-16  96.599998   99.497650  203.334335  269.810364  25.518410
2023-03-17  97.839996  100.787003  194.086899  272.965637  25.702246
2023-03-20  96.809998  100.390282  196.269775  265.932220  25.877090
2023-03-21  95.930000  104.059944  200.585907  267.446289  26.175831

Price            High                                                 ...  \
Ticker            AMD       GOOGL        META        MSFT       NVDA  ...
Date                                                                  ...
2023-03-15  90.419998   96.135437  196.240016  260.315235  24.264519  ...
2023-03-16  96.690002  100.360521  204.157874  270.162021  25.565367  ...
2023-03-17  98.750000  101.996996  200.327916  276.775408  26.375649  ...
2023-03-20  96.940002  100.915936  197.807710  271.060767  26.000981  ...
2023-03-21  99.459999  104.238469  201.965083  268.638066  26.368661  ...

Price            Open                                                \
Ticker            AMD      GOOGL        META        MSFT       NVDA
Date
2023-03-15  86.769997   92.45585  191.447622  253.965606  23.739984
2023-03-16  89.720001   95.41142  196.716272  259.074588  24.005749
2023-03-17  96.660004   99.43815  198.998353  271.822721  25.959018
2023-03-20  96.300003   99.29930  196.934557  270.572334  25.592343
2023-03-21  97.000000  100.42003  201.617802  268.520847  26.156849

Price          Volume
Ticker            AMD     GOOGL      META      MSFT       NVDA
Date
2023-03-15   86177400  50622100  42123600  46028000  524486000
2023-03-16  115839200  65492000  50447100  54768800  583253000
2023-03-17   94080800  61028500  50141100  69527400  848547000
2023-03-20   92008900  32960400  25186300  43466600  432747000
2023-03-21   85285300  42110300  31827000  34558700  547408000

[5 rows x 25 columns]

In [26]:
reshaped_data = df["Close"].stack().reset_index().rename(columns={0: "Close"})
reshaped_data.head()

        Date Ticker       Close
0 2023-03-15    AMD   89.680000
1 2023-03-15  GOOGL   95.322159
2 2023-03-15   META  196.210251
3 2023-03-15   MSFT  259.299286
4 2023-03-15   NVDA   24.206572

In [27]:
reshaped_data = reshaped_data.set_index('Date')

In [ ]:
# Group data by months

# reshaped_data.dtypes

reshaped_data.groupby(["Ticker", pd.Grouper(freq='ME')])["Close"].mean()

In [30]:
monthly_close = reshaped_data.groupby(["Ticker", pd.Grouper(freq='ME')])["Close"].mean()
monthly_close.head()

Ticker  Date
AMD     2023-03-31     96.601537
        2023-04-30     90.810001
        2023-05-31    102.217273
        2023-06-30    117.791905
        2023-07-31    113.690000
Name: Close, dtype: float64

In [32]:
reshaped_data.groupby(["Ticker", pd.Grouper(freq='QE')])["Close"].mean()

Ticker  Date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
                         ...
NVDA    2025-03-31    126.703979
        2025-06-30    125.817830
        2025-09-30    174.281514
        2025-12-31    186.121489
        2026-03-31    185.429958
Name: Close, Length: 65, dtype: float64

In [33]:
quarterly_close = reshaped_data.groupby(["Ticker", pd.Grouper(freq='QE')])["Close"].mean()
quarterly_close.head()

Ticker  Date
AMD     2023-03-31     96.601537
        2023-06-30    103.996775
        2023-09-30    108.554127
        2023-12-31    117.857460
        2024-03-31    174.810654
Name: Close, dtype: float64